/**
 * Regenerates every file under docs/ from the code and the current configuration: the route registry, the
 * session and rate-limit constants, the security event catalog, crypto-inventory.json, package.json, and (when
 * present) securevibe.design.json / securevibe.features.json. Nothing here is hand-written prose that could drift
 * from the app — if the app changes, "npm run docs:build" changes the docs to match.
 *
 * Each generator is a pure function of the app's current state, so the same input always produces the same file
 * (no timestamps). That lets a compliance check regenerate a doc in memory and compare its hash with the file on
 * disk. Run with `--check` to do exactly that without writing anything (exit code 1 when a file is missing or stale).
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { APP_ROOT, config } from '../src/config.ts';
import { createApp } from '../src/app.ts';
import { closeDb, openDb } from '../src/db/index.ts';
import { runMigrations } from '../src/db/migrate.ts';
import { listEntities } from '../src/security/authz.ts';
import { SECURITY_EVENTS } from '../src/security/events.ts';
import { MAX_LENGTH, MIN_LENGTH } from '../src/security/password.ts';
import { presetDefinitions, type PresetDefinition, type RateLimitPreset } from '../src/security/rate-limit.ts';
import { routeSchemasAsJson, summariseRoutes, type RouteSummary } from '../src/security/routes.ts';
import { SESSION_COOKIE } from '../src/security/session.ts';

const DOCS_DIR = resolve(APP_ROOT, 'docs');

// ---------------------------------------------------------------------------------------------------------------
// Small helpers shared by several generators
// ---------------------------------------------------------------------------------------------------------------

function formatBytes(n: number): string {
  if (n >= 1024 * 1024) {
    const mb = n / (1024 * 1024);
    return `${Number.isInteger(mb) ? mb : mb.toFixed(1)} MB`;
  }
  if (n >= 1024) return `${Math.round(n / 1024)} KB`;
  return `${n} bytes`;
}

function table(headers: string[], rows: string[][]): string {
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.map(esc).join(' | ')} |`).join('\n');
  return rows.length > 0 ? `${head}\n${sep}\n${body}` : `${head}\n${sep}\n| ${headers.map(() => '—').join(' | ')} |`;
}

function pathToOpenApi(path: string): string {
  return path.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
}

function ownerText(r: RouteSummary): string {
  if (!r.owner) return '—';
  return `Must own the \`${r.owner.entity}\` record named by \`:${r.owner.param}\` (administrators may access any record).`;
}

function whoText(r: RouteSummary): string {
  if (r.auth === 'public') return 'Anyone (no sign-in required)';
  if (r.auth === 'user') return r.roles.length > 0 ? `Signed in, role ${r.roles.map((x) => `\`${x}\``).join(' or ')} (or an administrator)` : 'Any signed-in user';
  return `Role \`${r.auth.slice(5)}\` (or an administrator)`;
}

const PAGE = 'This file is generated by `npm run docs:build` from the app’s own code and configuration. Do not edit it by hand — change the code or configuration and run `npm run docs:build` again.';

function doc(title: string, intro: string, body: string): string {
  return `# ${title}\n\n${intro}\n\n${body}\n\n---\n\n*${PAGE}*\n`;
}

// ---------------------------------------------------------------------------------------------------------------
// docs/authorization.md — V8.1.1, V8.1.2
// ---------------------------------------------------------------------------------------------------------------

function genAuthorizationMd(routes: RouteSummary[]): string {
  const rows = routes
    .filter((r) => !r.path.startsWith('/__securevibe'))
    .map((r) => [`${r.method} \`${r.path}\``, whoText(r), ownerText(r), r.summary || '—']);
  return doc(
    'Who can do what',
    [
      'Every page and every API call in this app is checked against a single list before it runs — there is no page that is reachable just because no link points away from it.',
      'The rule is *deny by default*: a route only works for the people named here. Administrators can always do what a named role can do.',
    ].join(' '),
    [
      '## Routes',
      '',
      table(['Route', 'Who may use it', 'Ownership check', 'What it does'], rows),
      '',
      '## How this is enforced',
      '',
      '- Every route is registered with an explicit rule (`public`, `user`, or `role:<name>`) — the app refuses to start if any route was added without one.',
      '- A route with an ownership check loads the record first and compares it to the signed-in user before running the handler; a non-owner sees the same "not found" response as a record that does not exist, so the app never reveals that something exists that the visitor may not see.',
      '- Every refusal is written to the security event log as `authz.denied` (see docs/logging.md).',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/validation.md — V2.1.1, V2.1.3
// ---------------------------------------------------------------------------------------------------------------

function genValidationMd(routes: RouteSummary[], schemas: ReturnType<typeof routeSchemasAsJson>): string {
  const byRoute = new Map(schemas.map((s) => [`${s.method} ${s.path}`, s]));
  const sections = routes
    .filter((r) => !r.path.startsWith('/__securevibe'))
    .map((r) => {
      const s = byRoute.get(`${r.method} ${r.path}`);
      const parts: string[] = [`### ${r.method} \`${r.path}\``];
      const any = s && (s.params || s.query || s.body);
      if (!any) {
        parts.push('No fields are accepted beyond the path itself.');
      } else {
        if (s?.params) parts.push(`**Path parameters**\n\n\`\`\`json\n${JSON.stringify(s.params, null, 2)}\n\`\`\``);
        if (s?.query) parts.push(`**Query string**\n\n\`\`\`json\n${JSON.stringify(s.query, null, 2)}\n\`\`\``);
        if (s?.body) parts.push(`**Request body**\n\n\`\`\`json\n${JSON.stringify(s.body, null, 2)}\n\`\`\``);
      }
      return parts.join('\n\n');
    });
  return doc(
    'What every route accepts',
    [
      'Every route validates its input against a strict schema on the server before any of your data reaches the handler.',
      'A field that is not listed here is rejected — the app never silently ignores or guesses at an unexpected field, and it never accepts a list where a single value is expected.',
      'The schemas below are shown as JSON Schema, generated straight from the validation rules in the code.',
    ].join(' '),
    sections.join('\n\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/sessions.md — V7.1.1 (doc), V7.1.2 (doc)
// ---------------------------------------------------------------------------------------------------------------

function genSessionsMd(): string {
  return doc(
    'How sign-in works',
    'A signed-in visit is called a session. Sessions are tracked on the server; the browser only holds a random, unguessable id.',
    [
      table(
        ['Setting', 'Value'],
        [
          ['Cookie name', `\`${SESSION_COOKIE}\``],
          ['Cookie flags', `HttpOnly, SameSite=Strict${config.tlsEnabled ? ', Secure' : ''}, Path=/`],
          ['Session id', '256 random bits (32 bytes), generated by the operating system'],
          ['Stored as', 'A keyed hash of the id (HMAC-SHA256 with SESSION_SECRET) — a copy of the database alone cannot be used to sign in'],
          ['Ends after no activity', `${config.sessionIdleMinutes} minutes`],
          ['Ends no matter what, after', `${config.sessionAbsoluteHours} hours`],
          ['Devices signed in at once', `${config.sessionMaxConcurrent} (the oldest is signed out automatically when a new one starts)`],
          ['Re-issued on sign-in', 'Yes — the id used before signing in stops working the moment sign-in succeeds'],
          ['Re-issued after a one-time code', 'Yes, again, for the same reason'],
          ['Re-confirmation window for sensitive changes', '5 minutes (email address, one-time code settings)'],
        ],
      ),
      '',
      'Signing out (or an administrator ending a session) marks it ended on the server immediately; the id in the browser stops working even if the cookie is not cleared.',
      'Visit **Your account → Sessions** to see every device currently signed in and end any of them.',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/SECURITY.md — V6.1.1 (doc), V6.1.3 (doc), MT-06 (partial)
// ---------------------------------------------------------------------------------------------------------------

function contactLine(): string {
  const owner = config.design.profile?.deployment?.owner;
  const email = owner?.contactEmail || config.ADMIN_EMAIL;
  const name = owner?.name;
  if (email) return `${name ? `${name} — ` : ''}${email}`;
  return 'Not configured yet. Set ADMIN_EMAIL in .env (or the owner contact in your SecureVibe design) so this file names a real contact.';
}

function genSecurityMd(): string {
  const presets = presetDefinitions();
  const rows = (Object.entries(presets) as [RateLimitPreset, PresetDefinition][]).map(([name, p]) => [
    `\`${name}\``,
    p.description,
    [p.perIp !== undefined ? `${p.perIp} per address` : undefined, p.perUser !== undefined ? `${p.perUser} per signed-in user` : undefined, p.perAccount !== undefined ? `${p.perAccount} per account` : undefined]
      .filter(Boolean)
      .join(', '),
    `${Math.round(p.windowMs / 60_000)} minute(s)`,
    p.backoff ? 'Yes, doubling, capped, never permanent' : 'No',
  ]);
  return doc(
    'Security policy',
    'How this app protects accounts from automated abuse, and how to report a security problem.',
    [
      '## Reporting a security problem',
      '',
      `Contact: ${contactLine()}`,
      '',
      'Please describe what you found and how to reproduce it. Do not use this app with real customer data to test a report — use a copy running locally.',
      '',
      '## Automated-abuse protection',
      '',
      'Every sensitive action is rate limited, and repeated sign-in failures on one account trigger a temporary slow-down (never a permanent lock):',
      '',
      table(['Limit', 'Applies to', 'Allowed', 'Per', 'Grows after repeated failures'], rows),
      '',
      '## Passwords',
      '',
      `A password must be at least ${MIN_LENGTH} characters long (a short sentence works well) and at most ${MAX_LENGTH}.`,
      '',
      'These words cannot be used as a password, or inside one, because they are the first thing an attacker tries:',
      '',
      `- Any password on the list of commonly used passwords that ships with this app.`,
      `- The name of this app (“${config.appName}”), and any word of four letters or more in it.`,
      '- The person\'s own name, and any word of four letters or more in it.',
      '- The part of the person\'s email address before the @ sign.',
      '',
      'Nothing else is banned: no forced mixture of capitals, digits and symbols, and no expiry date, because those rules push people towards worse passwords.',
      '',
      '## Two-factor authentication',
      '',
      `Administrators ${config.ADMIN_MFA_REQUIRED ? 'must' : 'may'} set up a one-time code app before using the app. ${config.USER_MFA_AVAILABLE ? 'Every user may turn on one-time codes for their own account.' : 'One-time codes are only available to administrators.'}`,
      '',
      '## Incident response',
      '',
      'If you believe the security event log or an account was tampered with, follow docs/incident-response.md and run `npm run audit:verify` to check the tamper-evident log.',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/crypto.md — V11.1.1 (doc), V11.1.2 (doc)
// ---------------------------------------------------------------------------------------------------------------

interface CryptoInventory {
  principles: string[];
  entries: { id: string; purpose: string; algorithm: string; keyOrSalt: string; storage: string; where: string; rotation: string }[];
}

function genCryptoMd(inventory: CryptoInventory): string {
  const rows = inventory.entries.map((e) => [e.purpose, e.algorithm, e.keyOrSalt, e.where, e.rotation]);
  return doc(
    'How this app uses cryptography',
    'Every place this app encrypts, hashes or signs something, listed from crypto-inventory.json so this document can never drift from what the code does.',
    [
      '## Principles', '', inventory.principles.map((p) => `- ${p}`).join('\n'), '',
      '## Inventory', '',
      table(['Used for', 'Algorithm and parameters', 'Key / salt', 'Where in the code', 'How it is rotated'], rows),
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/logging.md — V16.1.1 (doc), V16.2.3 (doc)
// ---------------------------------------------------------------------------------------------------------------

function genLoggingMd(): string {
  const rows = (Object.entries(SECURITY_EVENTS) as [string, { outcome: string; description: string }][]).map(([name, e]) => [`\`${name}\``, e.outcome, e.description]);
  return doc(
    'What is logged',
    'Two things are written for every security-relevant action: a structured log line, and a row in a tamper-evident security event table.',
    [
      '## Where',
      '',
      table(
        ['What', 'Detail'],
        [
          ['Application log', `JSON lines, ${config.LOG_LEVEL} level and above, at \`${config.logFile.replace(config.dataDir, 'DATA_DIR')}\``],
          ['Security event log', `\`audit_log\` table in the database — append-only and hash-chained (each row includes the hash of the row before it), kept for at least ${config.AUDIT_RETENTION_DAYS} days`],
          ['Checking the security event log', 'Run `npm run audit:verify` — it recomputes every hash and reports the first row that does not match'],
        ],
      ),
      '',
      '## What is never written to a log',
      '',
      'Passwords, one-time codes, tokens, API keys, cookies and any field an entity marks `sensitive` are replaced with `[redacted]` wherever they would otherwise appear, at any depth. A session is only ever identified by the first 8 characters of its hash.',
      '',
      '## Security events',
      '',
      table(['Event', 'Default outcome', 'What it means'], rows),
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/communications.md — V13.1.1 (doc)
// ---------------------------------------------------------------------------------------------------------------

function genCommunicationsMd(): string {
  const hosts = config.outboundAllowedHosts;
  return doc(
    'Talking to other services',
    'This app can only call other web services through one function, and only to hosts you explicitly allow.',
    [
      '## Currently allowed',
      '',
      hosts.length > 0 ? hosts.map((h) => `- \`${h}\``).join('\n') : '*(none — OUTBOUND_ALLOWED_HOSTS is empty, so the app cannot call out to anything)*',
      '',
      '## Rules that always apply',
      '',
      '- Only `https://` and `http://` addresses; credentials embedded in the URL are refused.',
      '- Redirects from the other service are never followed automatically.',
      '- Every call times out after 10 seconds and stops reading after 1 MB.',
      '- Certificate checks are never turned off.',
      '- After 5 failures in a row, calls to that host pause for 30 seconds (a "circuit breaker") so one broken service cannot slow the rest of the app down.',
      '- A blocked or failed call is written to the security event log (`outbound.blocked`, `outbound.failure`, `breaker.open`).',
      '',
      'To allow a new host, add it to `OUTBOUND_ALLOWED_HOSTS` in `.env` (comma-separated, `host` or `host:port`) and restart the app.',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/uploads.md — V5.1.1 (doc)
// ---------------------------------------------------------------------------------------------------------------

function genUploadsMd(): string {
  const types = config.UPLOAD_ALLOWED_TYPES.split(',').map((t) => t.trim()).filter(Boolean);
  return doc(
    'File uploads',
    config.features.uploads ? 'This app accepts file uploads under the following rules.' : 'File uploads are currently switched off (`uploads` is not enabled in securevibe.features.json). The rules below apply if it is turned on.',
    [
      table(
        ['Rule', 'Value'],
        [
          ['Largest file accepted', formatBytes(config.UPLOAD_MAX_BYTES)],
          ['Allowed types', types.map((t) => `\`${t}\``).join(', ') || 'none configured'],
          ['Storage limit per user', formatBytes(config.UPLOAD_USER_QUOTA_BYTES)],
          ['Where files are stored', 'Outside the web root, under a random file name; never at a path a visitor can guess or choose'],
          ['How the type is checked', "The file's first bytes are checked against a known table (not just the file name or the browser's claimed type); mismatches are refused"],
          ['Types that are always refused', '`svg`, `html`, `xml`, `zip` — regardless of the allow-list above, because they can contain active content'],
          ['Downloading a file', "Sent with `Content-Disposition: attachment`, `X-Content-Type-Options: nosniff` and a sandboxed content policy; only the file's owner (or an administrator) may download it"],
        ],
      ),
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/data-protection.md — V14.1.1 (doc), V14.1.2 (doc), DM-01, DM-05
// ---------------------------------------------------------------------------------------------------------------

/** The kinds of information a person chose in the wizard, written out for a reader rather than as code words. */
const CATEGORY_WORDS: Record<string, string> = {
  contact: 'contact details — names, email addresses, phone numbers, postal addresses',
  financial: 'financial information — bank details, salaries, invoices, balances',
  'payment-card': 'payment card details — never stored here; payment happens at the provider',
  health: 'health information — medical, wellbeing or disability details',
  'government-id': 'government id numbers — passport, national id, tax numbers',
  credentials: 'credentials — the passwords and one-time code secrets of the people who sign in',
  children: 'information about children under 16',
  location: 'location — where somebody is or has been',
  files: 'files people upload — documents and images',
  'business-confidential': 'business-confidential information — internal data, pricing, plans',
  'other-personal': 'other personal information about identifiable people',
};

function genDataProtectionMd(): string {
  const categories = config.design.profile?.data?.categories ?? [];
  const entities = listEntities();
  const entityRows = entities.map((e) => [e.label ?? e.name, e.table, (e.sensitiveFields ?? []).length > 0 ? e.sensitiveFields!.map((f) => `\`${f}\``).join(', ') : 'none'].map((s) => String(s)));
  const retention = config.design.profile?.data?.retention;
  const regulatedHint = categories.some((c) => ['health', 'financial', 'government-id', 'children'].includes(c));
  return doc(
    'How data is protected',
    'What kinds of information this app is set up to handle, and what protects it.',
    [
      [
        '## Data this app is designed to hold',
        categories.length > 0
          ? categories.map((c) => `- ${CATEGORY_WORDS[c] ?? c.replace(/-/g, ' ')}`).join('\n')
          : 'No data categories were specified at design time; treat any personal information you add as sensitive by default.',
      ].join('\n\n'),
      [
        '## Protections that apply to every record',
        [
          '- Every list query has an upper bound (no query returns unlimited rows).',
          '- Only DTOs (chosen fields) are ever sent to a page or the API — a raw database row is never returned.',
          `- Fields an entity marks \`sensitive\` are encrypted at rest (AES-256-GCM, see docs/crypto.md) and redacted from logs. ${config.features.fieldEncryption ? 'Field encryption is switched on.' : 'Field encryption is currently switched off.'}`,
        ].join('\n'),
      ].join('\n\n'),
      ['## Records this app currently tracks', table(['Kind of record', 'Database table', 'Encrypted fields'], entityRows)].join('\n\n'),
      [
        '## Keeping data no longer than needed',
        retention === 'auto-delete-after-period' && config.design.profile?.data?.retentionMonths
          ? `Records are kept for ${config.design.profile.data.retentionMonths} months (see docs/data-retention.md for how deletion works).`
          : 'See docs/data-retention.md for the retention policy and how a person can ask for their data to be exported or deleted.',
      ].join('\n\n'),
      regulatedHint
        ? '## A note on regulation\n\nThe data categories above can be subject to rules such as GDPR, CCPA or HIPAA depending on who your users are and where they live. This app gives you the building blocks (export, deletion, encryption, an audit trail) but does not tell you which rules apply to your business — check with a professional if you are not sure.'
        : '',
    ]
      .filter(Boolean)
      .join('\n\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/dependencies.md — V15.1.1 (doc), V15.1.2, V15.2.1 (partial)
// ---------------------------------------------------------------------------------------------------------------

interface PackageJson {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

function genDependenciesMd(pkg: PackageJson): string {
  const deps = Object.entries(pkg.dependencies ?? {}).map(([n, v]) => [`\`${n}\``, v]);
  const devDeps = Object.entries(pkg.devDependencies ?? {}).map(([n, v]) => [`\`${n}\``, v]);
  return doc(
    'Dependencies',
    'This app installs from a locked, tested set of packages (`package-lock.json`) so what runs on your computer is exactly what was tested.',
    [
      '## How they are installed',
      '',
      '- `npm install` uses `package-lock.json`; the agent that customises this app is not allowed to add new packages.',
      '- `.npmrc` sets `ignore-scripts=true`, so no package can run its own install scripts (a common supply-chain attack path).',
      '- Run `npm audit` from time to time to check for newly discovered vulnerabilities in these versions.',
      '',
      '## What keeps checking, after this app is handed over',
      '',
      'If this app lives in a GitHub repository, `.github/workflows/security.yml` runs on every change and once a week even when nothing changes:',
      '',
      "- it runs this app's own security tests and `npm audit`;",
      '- it writes a bill of materials in CycloneDX form — the list of every package and version inside the app — and keeps it with the run;',
      '- it builds the container and scans it for known problems, in the app and in the operating system underneath it, and fails if anything serious is found.',
      '',
      '`.github/dependabot.yml` opens a pull request when a package or a workflow step needs updating, and those checks run on the pull request before you merge it.',
      '',
      'Publishing the container image is off until you switch it on (repository variable `PUBLISH_IMAGE=true`). When it is on, every published image is signed by that workflow with no key for anyone to steal, carries its bill of materials, and records how it was built. Whoever runs the image can check all three with `cosign verify` and `gh attestation verify`, and know it came from your repository and holds what it says it holds.',
      '',
      '## Runtime dependencies', '', table(['Package', 'Version range'], deps),
      '',
      '## Development-only dependencies', '', table(['Package', 'Version range'], devDeps),
      '',
      '## How quickly to act on a known vulnerability',
      '',
      table(['Severity', 'Fix within'], [['Critical', '7 days'], ['High', '30 days'], ['Medium', '90 days'], ['Low', 'Next convenient update']]),
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/api.md + docs/openapi.json — AS-05, MT-05
// ---------------------------------------------------------------------------------------------------------------

function genApiMd(routes: RouteSummary[]): string {
  const api = routes.filter((r) => r.kind === 'api' && !r.path.startsWith('/__securevibe'));
  const rows = api.map((r) => [`${r.method} \`${r.path}\``, whoText(r), r.rateLimit, r.csrf ? 'Yes' : 'No', r.idempotent ? 'Yes' : 'No', r.summary || '—']);
  return doc(
    'JSON API',
    'The JSON endpoints this app exposes under `/api`. A full machine-readable description is in `docs/openapi.json`. Page routes (the parts of the app meant to be opened in a browser) are documented in docs/authorization.md.',
    table(['Route', 'Who may use it', 'Rate limit', 'CSRF token required', 'Idempotency-Key supported', 'What it does'], rows),
  );
}

function genOpenApi(routes: RouteSummary[], schemas: ReturnType<typeof routeSchemasAsJson>): object {
  const byRoute = new Map(schemas.map((s) => [`${s.method} ${s.path}`, s]));
  const paths: Record<string, Record<string, unknown>> = {};
  for (const r of routes) {
    if (r.path.startsWith('/__securevibe')) continue;
    const p = pathToOpenApi(r.path);
    const s = byRoute.get(`${r.method} ${r.path}`);
    const parameters: unknown[] = [];
    for (const name of r.params) parameters.push({ name, in: 'path', required: true, schema: { type: 'string' } });
    if (s?.query && typeof s.query === 'object') parameters.push({ name: 'query', in: 'query', style: 'form', explode: true, schema: s.query });
    const operation: Record<string, unknown> = {
      summary: r.summary || `${r.method} ${r.path}`,
      tags: [r.kind],
      security: r.auth === 'public' ? [] : [{ sessionCookie: [] }],
      ...(parameters.length > 0 ? { parameters } : {}),
      ...(s?.body ? { requestBody: { required: true, content: { 'application/json': { schema: s.body } } } } : {}),
      responses: {
        '200': { description: 'Success' },
        ...(r.auth !== 'public' ? { '401': { description: 'Not signed in' }, '403': { description: 'Not allowed' } } : {}),
        '400': { description: 'The request did not pass validation' },
      },
    };
    paths[p] ??= {};
    paths[p]![r.method.toLowerCase()] = operation;
  }
  return {
    openapi: '3.1.0',
    info: { title: `${config.appName} API`, version: '1.0.0', description: 'Generated by npm run docs:build from the live route registry.' },
    servers: [{ url: '/' }],
    components: { securitySchemes: { sessionCookie: { type: 'apiKey', in: 'cookie', name: SESSION_COOKIE } } },
    paths,
  };
}

// ---------------------------------------------------------------------------------------------------------------
// docs/ai.md — C3.1.1, C6.2.1 (partial)
// ---------------------------------------------------------------------------------------------------------------

// Structural types only: naming the AI modules' own types would make this script fail to compile in apps
// where the AI feature was removed.
interface AiModules {
  dataScope(): 'nothing' | 'users-own-records' | 'all-records';
  featureOn(...names: string[]): boolean;
  SYSTEM_PROMPT_HASH: string;
  allTools(): { name: string; description: string; mutates: boolean }[];
}

/** The AI feature is removed from apps that do not use it, so its modules are loaded only if present. */
async function loadAiModules(): Promise<AiModules | undefined> {
  const at = (rel: string) => new URL(rel, import.meta.url).href;
  try {
    const context = (await import(at('../src/features/ai/context.ts'))) as Pick<AiModules, 'dataScope' | 'featureOn'>;
    const prompt = (await import(at('../src/features/ai/prompt.ts'))) as Pick<AiModules, 'SYSTEM_PROMPT_HASH'>;
    const tools = (await import(at('../src/features/ai/tools.ts'))) as Pick<AiModules, 'allTools'>;
    return { dataScope: context.dataScope, featureOn: context.featureOn, SYSTEM_PROMPT_HASH: prompt.SYSTEM_PROMPT_HASH, allTools: tools.allTools };
  } catch (err) {
    if ((err as { code?: string }).code === 'ERR_MODULE_NOT_FOUND') return undefined;
    throw err;
  }
}

function genAiMdAbsent(): string {
  return ['# AI assistant', '', 'This app has no AI assistant, so no AI model is called and no data is sent to an AI provider.', ''].join('\n');
}

function genAiMd(ai: AiModules): string {
  const { dataScope, featureOn, SYSTEM_PROMPT_HASH, allTools } = ai;
  const scope = dataScope();
  const tools = allTools();
  return doc(
    'The AI assistant',
    config.features.ai ? 'This app includes an AI assistant backed by Anthropic’s Claude. Here is what it can see and the limits that apply to it.' : 'The AI assistant is currently switched off (`ai` is not enabled in securevibe.features.json). The rules below apply if it is turned on.',
    [
      '## The model this app uses',
      '',
      table(
        ['Setting', 'Value'],
        [
          ['Provider', 'Anthropic (the `@anthropic-ai/sdk` package, called from `src/features/ai/client.ts` and nowhere else)'],
          ['Model', `\`${config.AI_MODEL}\` (pinned — never chosen by the model itself or by a visitor)`],
          ['Instructions', `fixed in \`src/features/ai/prompt.ts\`, fingerprint \`${SYSTEM_PROMPT_HASH.slice(0, 16)}…\` (recorded with every request)`],
          ['Answer shape', 'a fixed structure (answer, refused, reason); anything else is replaced by a standard message'],
          ['Longest question accepted', `${config.AI_MAX_INPUT_CHARS} characters (longer input is refused, never cut short)`],
          ['Longest answer', `${config.AI_MAX_OUTPUT_TOKENS} tokens, and at most 4000 characters`],
          ['Time limit per call', '30 seconds'],
          ['Daily budget per user', `${config.AI_USER_DAILY_TOKENS} tokens`],
          ['Requests per user', '20 an hour'],
          ['Content moderation', config.AI_MODERATION || featureOn('aiModeration', 'ai-moderation') ? 'On — questions and answers are classified before use' : 'Off'],
          ['Conversation memory', featureOn('aiHistory', 'ai-history') ? 'Kept per person; each person can clear their own at any time' : 'Not kept'],
          ['Kill switch', 'AI_ENABLED=0 in .env, or an administrator can switch it off at runtime; both are logged'],
        ],
      ),
      '',
      '## What the assistant can see',
      '',
      scope === 'nothing'
        ? 'Nothing from the app. It answers from the question alone.'
        : "Only data that belongs to the person asking, fetched through the app's normal data-access functions — never a raw database query built from the question. Anything it reads is clearly marked as untrusted data, separate from its instructions, so text inside a record cannot make it act differently, and it is screened with the same list of manipulation patterns as the question.",
      '',
      'Before an answer is shown it is checked again: it must match the expected shape and length, it must not repeat the assistant’s own instructions, and any record identifier or email address belonging to somebody else is removed. The answer is shown as plain text — never as HTML, markdown or a link.',
      '',
      '## What the assistant can do',
      '',
      tools.length === 0
        ? 'Nothing beyond answering questions.'
        : table(
            ['Action', 'What it does', 'Needs confirmation'],
            tools.map((tool) => [`\`${tool.name}\``, tool.description, tool.mutates ? 'Yes — a person confirms it before anything happens' : 'No (reading only)']),
          ),
      '',
      featureOn('aiActions', 'ai-actions')
        ? 'Actions that change something are only ever suggestions. They are stored as a proposal, shown to the person, and carried out by the app through its ordinary code path with that person’s own permissions once they confirm. The model never carries anything out itself.'
        : 'Actions are switched off in this app: the assistant can only answer questions.',
      '',
      '## What is recorded',
      '',
      'Every call is written to the security event log as `ai.request` and to the `ai_interactions` table with the model, the provider, the token counts and a fingerprint of the question and answer — never their text. Token use is counted per person, per session and per page in `ai_usage`, which is what the daily budget is read from. Refused and flagged questions are recorded as `ai.input.rejected` and `ai.input.flagged` with the rule that matched.',
      '',
      '## Your Anthropic API key',
      '',
      'Read only from the environment; never sent to the model, written to the database, or included in a log line.',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/deployment.md — MT-06, DM-05, ADRs
// ---------------------------------------------------------------------------------------------------------------

function genDeploymentMd(): string {
  const target = config.design.profile?.deployment?.target;
  return doc(
    'Where this app can run',
    target ? `By default this app only answers on this computer. It was designed for: **${target}**.` : 'By default this app only answers on this computer.',
    [
      '## The three modes',
      '',
      table(
        ['Mode', 'How to turn it on', 'What it means'],
        [
          ['Just this computer (default)', 'Nothing to do — `BIND_LAN=0`, `TLS_MODE=off`', 'Only someone sitting at this computer can reach the app. No certificate is needed.'],
          ['Other devices on your network', '`BIND_LAN=1` in `.env`, and normally `TLS_MODE=selfsigned` (`npm run gen-cert` first)', 'Phones and laptops on the same Wi-Fi or office network can reach the app. Browsers will warn about the self-signed certificate — that is expected on a private network.'],
          ['The internet', 'Put a real reverse proxy (with a certificate from a service like Let’s Encrypt) in front of the app and set `TLS_MODE=proxy` with `TRUST_PROXY_HOPS=1` (or however many proxies sit in front of it)', 'Anyone can reach the app. Do this only once you are ready — see the checklist below.'],
        ],
      ),
      '',
      '## Moving this app to another computer',
      '',
      'The app is ordinary Node.js: it needs Node 22.13 or newer, its `.env` file and its `data` folder, and nothing else. Copy those three things to another computer, run `npm ci --omit=dev` and then `npm start`, and it runs exactly as it does here.',
      '',
      'There is also a container, which is the same thing in one step:',
      '',
      '```',
      'docker compose up --build',
      '```',
      '',
      'The image carries the code only. Your secrets and your records stay outside it: `.env` is read when the container starts and the `data` folder lives next to `compose.yaml`, so an image you copy or publish holds neither. The container publishes the app to this computer only (`127.0.0.1`), runs as an unprivileged user, and cannot write anywhere but its data folder. Letting other people reach it is the same decision as the table above, and the same checklist applies.',
      '',
      '## Before you go on the internet',
      '',
      '- Put a real TLS certificate in front of the app (a reverse proxy such as Caddy, nginx or a managed load balancer is the simplest way).',
      '- Re-check `docs/data-protection.md` and `docs/data-retention.md` — sensitive data over the internet usually needs field encryption on and a retention period set.',
      '- Consider a secret manager instead of the `.env` file for production secrets.',
      '- Review `docs/SECURITY.md` and make sure the contact address is real.',
      '- Take a fresh look at rate limits: the defaults assume a small number of trusted users.',
      '',
      'This guidance is generated from the SbD (Secure by Design) checklist controls AC-01 and DM-02, which are honestly reported as *not applicable yet* for a loopback-only app and re-evaluated once you set `TLS_MODE`.',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/incident-response.md — MT-06 (partial), AC-06 (partial)
// ---------------------------------------------------------------------------------------------------------------

function genIncidentResponseMd(): string {
  return doc(
    'If you suspect a security incident',
    'A short, concrete plan for the moment something looks wrong — a leaked password, unexpected admin activity, or a report from a user.',
    [
      `**Contact:** ${contactLine()}`,
      '',
      '## 1. Check what actually happened',
      '',
      '- Run `npm run audit:verify` to confirm the security event log has not been tampered with.',
      '- Look at recent events for the account or IP address in question (the `audit_log` table, or the log file at `DATA_DIR/app.log`).',
      '- In test/staging, the same data is available at `GET /__securevibe/events` — never in production.',
      '',
      '## 2. Contain it',
      '',
      '- Sign the affected account out everywhere: **Administration → Users → (the account) → Sign out everywhere**.',
      '- If a password may be known to someone else, force a reset: the same page can disable the account or remove its one-time codes so it cannot be used until the owner resets their password.',
      '- If the API key feature is enabled, revoke the key in question.',
      '',
      '## 3. Fix the cause',
      '',
      'Patch the vulnerability or misconfiguration, redeploy, and confirm with `npm test` and `npm run typecheck` before bringing the app back if it was taken offline.',
      '',
      '## 4. Tell the people affected',
      '',
      'If personal data may have been exposed, tell the people affected in plain language: what happened, what data, what you have done about it, and what they should do (for example, changing a re-used password elsewhere). Rules on when you must notify people or a regulator vary by where your users live — check docs/data-protection.md and, if unsure, a professional.',
      '',
      '## 5. Write it down',
      '',
      'Keep a short record of what happened and what changed as a result — even a few lines. It is the fastest way to improve the plan above next time.',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/data-retention.md — DM-05, MT-06
// ---------------------------------------------------------------------------------------------------------------

function genDataRetentionMd(): string {
  const months = config.retentionMonths;
  const entities = listEntities().filter((e) => e.deleteForUser);
  return doc(
    'How long data is kept, and how it is removed',
    months !== undefined
      ? `This app is configured to act on records older than **${months} months**.`
      : 'No automatic retention period is configured yet. Data is kept until a person deletes their own account or an administrator deletes it.',
    [
      '## What a person can do themselves',
      '',
      '- **Download a copy of their data** — Your account → Download your data — exports everything the app has recorded for their account as a single file.',
      '- **Delete their account** — Your account → Delete account (asks them to confirm their password first). This removes their sign-in details and, for each kind of record listed below, either deletes or removes the personal parts of their records.',
      '',
      '## Records affected by deletion',
      '',
      entities.length > 0
        ? table(
            ['Kind of record', 'What happens on deletion'],
            entities.map((e) => [e.label ?? e.name, 'Deleted or personal fields removed, as implemented in the feature’s code']),
          )
        : 'No entities have registered a deletion handler yet — add one with `registerEntity({ deleteForUser })` as new features are added.',
      '',
      '## Automatic retention',
      '',
      months !== undefined
        ? `Set \`RETENTION_MONTHS=${months}\` in \`.env\`. A scheduled job (when the scheduler feature is enabled) applies the same deletion or pseudonymisation described above to records older than that.`
        : 'To turn this on, set `RETENTION_MONTHS` in `.env` to the number of months you want to keep records for.',
      '',
      '## The security event log',
      '',
      `Kept for at least ${config.AUDIT_RETENTION_DAYS} days (\`AUDIT_RETENTION_DAYS\`) so an incident can still be investigated after records are deleted; it never stores the personal data itself, only that an action happened.`,
      '',
      'Every deletion is recorded as a `data.deleted` security event before the data disappears (see docs/logging.md).',
    ].join('\n'),
  );
}

// ---------------------------------------------------------------------------------------------------------------
// docs/adr/*.md — ADRs from the design, or the baseline template's own defaults
// ---------------------------------------------------------------------------------------------------------------

interface AdrOut {
  file: string;
  content: string;
}

function slug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'decision';
}

function genAdrFiles(): AdrOut[] {
  const designAdrs = config.design.adrs;
  if (designAdrs.length > 0) {
    return designAdrs.map((a, i) => ({
      file: `${String(i + 1).padStart(4, '0')}-${slug(a.title)}.md`,
      content: doc(
        `ADR ${i + 1}: ${a.title}`,
        `Status: ${a.status}${a.date ? ` · ${a.date}` : ''}`,
        [
          ['## Context', a.context || '*(not recorded)*'].join('\n\n'),
          ['## Decision', a.decision || '*(not recorded)*'].join('\n\n'),
          a.alternatives.length > 0 ? `## Alternatives considered\n\n${a.alternatives.map((x) => `- ${x}`).join('\n')}` : '',
          ['## Consequences', a.consequences || '*(not recorded)*'].join('\n\n'),
          a.relatedControls.length > 0 ? `Related SbD controls: ${a.relatedControls.map((c) => `\`${c}\``).join(', ')}` : '',
          a.relatedRequirements.length > 0 ? `Related requirements: ${a.relatedRequirements.map((c) => `\`${c}\``).join(', ')}` : '',
        ]
          .filter(Boolean)
          .join('\n\n'),
      ),
    }));
  }
  // No design was supplied (the template is being inspected on its own): document the baseline's own decisions.
  const baseline: { title: string; context: string; decision: string; consequences: string }[] = [
    {
      title: 'Built-in node:sqlite instead of a native database driver',
      context: 'The app needs a local database with zero native compilation, so that `npm install --ignore-scripts` is always safe.',
      decision: 'Use Node.js’s built-in `node:sqlite` module through a single parameterised-query wrapper (`src/db/index.ts`).',
      consequences: 'No native modules to compile or audit; one file owns every SQL query, which is what makes the SAST rule against raw SQL concatenation possible.',
    },
    {
      title: 'Server-rendered pages plus a JSON API, not a separate front-end build',
      context: 'Fewer moving parts to secure (one CSP, one session mechanism, one CSRF story) and no separate build step for a small business owner to manage.',
      decision: 'EJS templates with auto-escaping for pages; the same route registry also serves JSON under `/api` for anything that needs it.',
      consequences: 'No client-side framework, no bundler, nothing to keep patched beyond the packages in package.json.',
    },
    {
      title: 'Secrets come from a seam, not from a bundled secret manager',
      context:
        'Secure by Design AC-05 asks for secrets in a secret manager with automatic rotation. This app usually runs on one person\u2019s computer, where a secret manager solves problems that do not exist: access control between people, audit of who read what, revocation across machines. Running one beside the app would add a service to unseal, back up and keep alive, and its own credential would end up in a file on the same disk with the same permissions as the .env file it replaced.',
      decision:
        'Keep the .env file with strict permissions as the default, and read every secret through one small seam (`src/lib/secrets.ts`) so a host\u2019s own store can supply them instead: a folder of files (Docker secrets, systemd credentials) supplied by whatever writes them there. Deliberately no \u201crun a command\u201d source: that would have every app start an operating-system command at boot, and SecureVibe\u2019s own scanner raised two high findings against the first version that had one. Tools like sops and Vault produce an environment or a file before the process starts, so nothing is lost. Values already in the environment always win. Rotate the session and token keys with `npm run rotate:keys`; the field-encryption key has its own script because it re-encrypts stored data.',
      consequences:
        'Moving to a hosted secret store needs configuration rather than code changes, which is what makes the deployment-time answer reachable instead of aspirational. AC-05 still reads "no" until secrets actually live in such a store and rotate automatically \u2014 a seam and a manual rotation command are real hardening, not the control itself, and recording them as one would overstate what the app does.',
    },
    {
      title: 'A hardened baseline that the AI only extends, never rewrites',
      context: 'Security controls implemented once, tested once, and evidenced mechanically are more trustworthy than controls re-generated by a language model for every app.',
      decision: 'Core security files (session, CSRF, headers, password, authorization, the route registry) are protected paths; the generator adds features that follow the same registry and conventions shown in `src/features/_example/`.',
      consequences: 'A generated app inherits every fix made to the baseline template; the compliance report can credit a control mechanically because the code that implements it did not change.',
    },
  ];
  return baseline.map((b, i) => ({
    file: `${String(i + 1).padStart(4, '0')}-${slug(b.title)}.md`,
    content: doc(`ADR ${i + 1}: ${b.title}`, 'Status: accepted (baseline template decision)', ['## Context', '', b.context, '', '## Decision', '', b.decision, '', '## Consequences', '', b.consequences].join('\n')),
  }));
}

// ---------------------------------------------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------------------------------------------

export interface GeneratedDoc {
  path: string;
  content: string;
}

export async function generateDocs(): Promise<GeneratedDoc[]> {
  openDb(':memory:');
  try {
    runMigrations();
    await createApp();
    const ai = await loadAiModules();
    const routes = summariseRoutes();
    const schemas = routeSchemasAsJson();
    const pkg = JSON.parse(readFileSync(resolve(APP_ROOT, 'package.json'), 'utf8')) as PackageJson;
    const inventory = JSON.parse(readFileSync(resolve(APP_ROOT, 'crypto-inventory.json'), 'utf8')) as CryptoInventory;

    const docs: GeneratedDoc[] = [
      { path: 'authorization.md', content: genAuthorizationMd(routes) },
      { path: 'validation.md', content: genValidationMd(routes, schemas) },
      { path: 'sessions.md', content: genSessionsMd() },
      { path: 'SECURITY.md', content: genSecurityMd() },
      { path: 'crypto.md', content: genCryptoMd(inventory) },
      { path: 'logging.md', content: genLoggingMd() },
      { path: 'communications.md', content: genCommunicationsMd() },
      { path: 'uploads.md', content: genUploadsMd() },
      { path: 'data-protection.md', content: genDataProtectionMd() },
      { path: 'dependencies.md', content: genDependenciesMd(pkg) },
      { path: 'api.md', content: genApiMd(routes) },
      { path: 'openapi.json', content: `${JSON.stringify(genOpenApi(routes, schemas), null, 2)}\n` },
      { path: 'ai.md', content: ai ? genAiMd(ai) : genAiMdAbsent() },
      { path: 'deployment.md', content: genDeploymentMd() },
      { path: 'incident-response.md', content: genIncidentResponseMd() },
      { path: 'data-retention.md', content: genDataRetentionMd() },
    ];
    for (const adr of genAdrFiles()) docs.push({ path: `adr/${adr.file}`, content: adr.content });
    return docs;
  } finally {
    closeDb();
  }
}

function hash(text: string): string {
  return createHash('sha256').update(text).digest('hex');
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes('--check');
  const docs = await generateDocs();
  mkdirSync(resolve(DOCS_DIR, 'adr'), { recursive: true });

  if (checkOnly) {
    const stale: string[] = [];
    for (const d of docs) {
      const file = resolve(DOCS_DIR, d.path);
      const current = existsSync(file) ? readFileSync(file, 'utf8') : undefined;
      if (current === undefined || hash(current) !== hash(d.content)) stale.push(d.path);
    }
    if (stale.length === 0) {
      process.stdout.write(`docs/ is up to date with the code (${docs.length} files checked).\n`);
      return;
    }
    process.stdout.write(`docs/ is out of date. Run "npm run docs:build" to refresh:\n${stale.map((s) => `  - docs/${s}`).join('\n')}\n`);
    process.exitCode = 1;
    return;
  }

  for (const d of docs) {
    const file = resolve(DOCS_DIR, d.path);
    mkdirSync(dirnameOf(file), { recursive: true });
    writeFileSync(file, d.content);
  }
  process.stdout.write(`Wrote ${docs.length} files to docs/\n`);
}

function dirnameOf(file: string): string {
  return file.slice(0, Math.max(file.lastIndexOf('/'), 0));
}

const isMain = process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((err: Error) => {
    process.stderr.write(`\nCould not build the docs.\n${err.message}\n${err.stack ?? ''}\n\n`);
    process.exitCode = 1;
  });
}
