/**
 * The AI review only counts when its citations are real. These tests pin the citation check, the hallucination
 * metric and the fact that an unverified answer never looks like a verified one.
 */
import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import {
  aiReview,
  buildSentFiles,
  toAiReviewResult,
  verifyCitation,
  type RequirementBatch,
  type ReviewFile,
} from '../../src/llm/flows/ai-review.js';
import { NullProvider } from '../../src/llm/null.js';
import { ScriptedProvider } from '../../src/llm/scripted.js';
import { FIXTURE_DIR, makeDesign } from './helpers.js';

const ROUTES = [
  '// Generated by SecureVibe (AI-generated) - run run-test',
  "import { defineRoute } from '../../security/routes.ts';",
  '',
  'export function registerNotes(router: unknown): void {',
  "  defineRoute(router, { method: 'GET', path: '/notes', auth: 'user' }, async () => {});",
  '}',
].join('\n');

const FILES: ReviewFile[] = [
  { path: 'src/features/notes/routes.ts', sha256: createHash('sha256').update(ROUTES).digest('hex'), content: ROUTES },
];

const BATCHES: RequirementBatch[] = [
  {
    chapterId: 'V8',
    chapterName: 'Authorization',
    standard: 'asvs',
    requirements: [
      { id: 'V8.2.1', description: 'Access control decisions are taken on the server.', level: 1 },
      { id: 'V2.2.1', description: 'Input is validated against a strict schema.', level: 1 },
      { id: 'V16.2.1', description: 'Logs are structured and carry a correlation id.', level: 2 },
      { id: 'V11.3.1', description: 'Sensitive data is encrypted at rest.', level: 2 },
      { id: 'V9.9.9', description: 'A requirement the model was never asked about.', level: 1 },
    ],
  },
];

describe('ai review', () => {
  const run = () =>
    aiReview(new ScriptedProvider({ dir: FIXTURE_DIR, scenario: 'ai-review' }), {
      files: FILES,
      requirements: BATCHES,
      design: makeDesign(),
      runId: 'run-test',
      projectId: 'p1',
    });

  it('keeps an answer whose quote is really at the cited place', async () => {
    const result = await run();
    const pass = result.assessments.find((a) => a.id === 'V8.2.1')!;
    expect(pass.status).toBe('pass');
    expect(pass.citations[0]?.verified).toBe(true);
  });

  it('turns an answer with a citation at the wrong line into "not verified"', async () => {
    const result = await run();
    const wrongLine = result.assessments.find((a) => a.id === 'V2.2.1')!;
    expect(wrongLine.status).toBe('not-verified');
    expect(wrongLine.citations[0]?.verified).toBe(false);
    expect(wrongLine.rationale).toContain('could not find the quoted code');
  });

  it('turns an answer quoting code that does not exist into "not verified"', async () => {
    const result = await run();
    const invented = result.assessments.find((a) => a.id === 'V16.2.1')!;
    expect(invented.status).toBe('not-verified');
    expect(invented.citations.every((c) => !c.verified)).toBe(true);
  });

  it('leaves a not-applicable answer alone and drops answers nobody asked for', async () => {
    const result = await run();
    expect(result.assessments.find((a) => a.id === 'V11.3.1')?.status).toBe('not-applicable');
    expect(result.assessments.map((a) => a.id)).not.toContain('V9.9.9');
    expect(result.reviewedRequirementIds).toHaveLength(5);
  });

  it('counts the unverified citations as a hallucination rate', async () => {
    const result = await run();
    expect(result.totalCitations).toBe(5); // three assessment citations plus two findings
    expect(result.unverifiedCitations).toBe(3);
    expect(result.hallucinationRate).toBeCloseTo(3 / 5, 4);
  });

  it('marks an unconfirmed finding as unconfirmed instead of hiding it', async () => {
    const result = await run();
    const good = result.findings.find((f) => f.title.includes('notes list'))!;
    const bad = result.findings.find((f) => f.title.includes('password'))!;
    expect(good.citationVerified).toBe(true);
    expect(good.confidence).toBe('medium');
    expect(bad.citationVerified).toBe(false);
    expect(bad.confidence).toBe('low');
    expect(bad.evidence).toContain('could not find the quoted line');
    expect(result.findings.every((f) => f.source === 'ai-review')).toBe(true);
    expect(new Set(result.findings.map((f) => f.fingerprint)).size).toBe(2);
  });

  it('is skipped honestly in preview mode', async () => {
    const result = await aiReview(new NullProvider(), { files: FILES, requirements: BATCHES, design: makeDesign() });
    expect(result.performed).toBe(false);
    expect(result.assessments).toEqual([]);
    expect(result.skippedReason).toContain('not configured');
    expect(result.hallucinationRate).toBe(0);
  });

  it('stops at the review spending limit instead of running every chapter', async () => {
    const result = await aiReview(new ScriptedProvider({ dir: FIXTURE_DIR, scenario: 'ai-review' }), {
      files: FILES,
      requirements: [BATCHES[0]!, { ...BATCHES[0]!, chapterId: 'V16' }],
      design: makeDesign(),
      budget: { maxIterations: 2, maxUsd: 0.0001, maxWallClockMs: 60_000, maxOutputTokens: 100_000 },
    });
    expect(result.batches[0]?.ok).toBe(true);
    expect(result.batches[1]?.ok).toBe(false);
    expect(result.batches[1]?.message).toContain('spending limit');
  });

  it('does not start a chapter that would likely go past the limit', async () => {
    const provider = () => new ScriptedProvider({ dir: FIXTURE_DIR, scenario: 'ai-review' });
    const one = await aiReview(provider(), { files: FILES, requirements: [BATCHES[0]!], design: makeDesign() });
    const perCall = one.usage.estimatedCostUsd;
    expect(perCall).toBeGreaterThan(0);
    const result = await aiReview(provider(), {
      files: FILES,
      requirements: [BATCHES[0]!, { ...BATCHES[0]!, chapterId: 'V16' }],
      design: makeDesign(),
      budget: { maxIterations: 2, maxUsd: perCall * 1.5, maxWallClockMs: 60_000, maxOutputTokens: 100_000 },
    });
    expect(result.batches.map((b) => b.ok)).toEqual([true, false]);
    expect(result.usage.estimatedCostUsd).toBeLessThanOrEqual(perCall * 1.5);
  });

  it('converts into the shape the compliance engine reads', async () => {
    const result = toAiReviewResult(await run());
    expect(result.performed).toBe(true);
    expect(result.assessments.find((a) => a.requirementId === 'V2.2.1')?.status).toBe('unknown');
    expect(result.unverifiedCitations).toBe(3);
    expect(result.promptHash).toMatch(/^[0-9a-f]{64}$/);
  });
});

describe('citation checking', () => {
  const index = new Map([['a.ts', ROUTES.split('\n')]]);

  it('accepts a quote within five lines of the cited line', () => {
    expect(verifyCitation(index, 'a.ts', 5, "auth: 'user'")).toBe(true);
    expect(verifyCitation(index, 'a.ts', 1, "auth: 'user'")).toBe(true); // within tolerance
    expect(verifyCitation(index, 'a.ts', 5, "auth:   'user'")).toBe(true); // whitespace is normalised
  });

  it('rejects a quote that is not there, a file that was not sent, and an empty quote', () => {
    expect(verifyCitation(index, 'a.ts', 5, "auth: 'admin'")).toBe(false);
    expect(verifyCitation(index, 'b.ts', 5, "auth: 'user'")).toBe(false);
    expect(verifyCitation(index, 'a.ts', 5, '')).toBe(false);
    expect(verifyCitation(index, 'a.ts', 99, "auth: 'user'")).toBe(false);
  });

  it('verifies against the text that was actually sent, not the file on disk', () => {
    const long = { path: 'big.ts', sha256: 'x', content: `${'a'.repeat(70_000)}\nconst secret = 1;\n` };
    const sent = buildSentFiles([long]);
    expect(sent.get('big.ts')!.length).toBeLessThan(long.content.length);
    expect(sent.get('big.ts')!).not.toContain('const secret = 1;');
  });
});

describe('review stops on account problems', () => {
  it('makes no further calls once the account has no credit', async () => {
    let calls = 0;
    const provider = {
      name: 'anthropic',
      model: 'claude-opus-5',
      structured: async () => {
        calls++;
        return { ok: false, reason: 'error', message: 'Your Anthropic account has run out of credit.', accountProblem: true, usage: { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, costUsd: 0, servedModel: 'claude-opus-5', fallbackUsed: false, refused: false } };
      },
    } as unknown as Parameters<typeof aiReview>[0];
    const result = await aiReview(provider, {
      files: FILES,
      requirements: [BATCHES[0]!, { ...BATCHES[0]!, chapterId: 'V16' }, { ...BATCHES[0]!, chapterId: 'V17' }],
      design: makeDesign(),
    });
    expect(calls).toBe(1);
    expect(result.batches.slice(1).every((b) => !b.ok && b.message.includes('run out of credit'))).toBe(true);
    expect(result.reviewedRequirementIds).toEqual([]);
  });
});

describe('review batching', () => {
  it('sends fewer requirements per call when the review reasons more', async () => {
    const { requirementsPerCall } = await import('../../src/llm/flows/ai-review.js');
    expect([requirementsPerCall('low'), requirementsPerCall('medium'), requirementsPerCall('high'), requirementsPerCall('max')]).toEqual([10, 5, 2, 1]);
  });

  it('splits a large chapter into calls small enough to always finish', async () => {
    const { splitBatches, MAX_REQUIREMENTS_PER_CALL } = await import('../../src/llm/flows/ai-review.js');
    const requirements = Array.from({ length: 22 }, (_, i) => ({ id: `V1.${i + 1}`, description: 'x', level: 1 }));
    const parts = splitBatches([{ chapterId: 'V1', chapterName: 'Encoding', standard: 'asvs', requirements }]);
    expect(parts.map((p) => p.requirements.length)).toEqual([MAX_REQUIREMENTS_PER_CALL, MAX_REQUIREMENTS_PER_CALL, 2]);
    expect(parts.flatMap((p) => p.requirements.map((r) => r.id))).toEqual(requirements.map((r) => r.id));
  });
});

describe('review stops on repeated failures', () => {
  it('stops after two failed calls in a row', async () => {
    let calls = 0;
    const provider = {
      name: 'anthropic',
      model: 'claude-opus-5',
      structured: async () => {
        calls++;
        return { ok: false, reason: 'error', message: 'The connection failed.', usage: { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, costUsd: 0, servedModel: 'claude-opus-5', fallbackUsed: false, refused: false } };
      },
    } as unknown as Parameters<typeof aiReview>[0];
    const result = await aiReview(provider, {
      files: FILES,
      requirements: ['V1', 'V2', 'V3', 'V4'].map((chapterId) => ({ ...BATCHES[0]!, chapterId })),
      design: makeDesign(),
    });
    expect(calls).toBe(2);
    expect(result.batches.slice(2).every((b) => b.message.includes('two calls in a row failed'))).toBe(true);
  });
});
