[package]
name = "sv-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sv"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
sv-frameworks = { path = "../sv-frameworks" }
sv-manifest = { path = "../sv-manifest" }
sv-report = { path = "../sv-report" }
sv-scan = { path = "../sv-scan" }
sv-run = { path = "../sv-run" }
sv-check = { path = "../sv-check" }
