/**
 * Small, self-contained file-tree helpers for the generator (kept local rather than reaching into another
 * module's internals): listing a generated app's files, hashing them, and matching the manifest's glob path
 * lists (which use a leading `!` to re-open an otherwise-protected file, e.g. `src/features/ai/prompt.ts`).
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

export interface AppFile {
  /** Posix path relative to the app root. */
  relPath: string;
  absPath: string;
}

export const DEFAULT_WALK_IGNORE = ['node_modules', '.git', 'data', 'dist', 'coverage', 'home', 'tmp', 'certs', '.DS_Store'];

function toPosix(p: string): string {
  return sep === '/' ? p : p.split(sep).join('/');
}

/** Lists every regular file under `root` (sorted, posix-relative), skipping the given top-level-or-anywhere names. */
export function listFiles(root: string, ignore: string[] = DEFAULT_WALK_IGNORE): AppFile[] {
  const out: AppFile[] = [];
  const ignoreSet = new Set(ignore);
  const walk = (dir: string): void => {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    for (const name of entries.sort()) {
      if (ignoreSet.has(name)) continue;
      const abs = join(dir, name);
      let st;
      try {
        st = statSync(abs);
      } catch {
        continue;
      }
      if (st.isDirectory()) walk(abs);
      else if (st.isFile()) out.push({ relPath: toPosix(relative(root, abs)), absPath: abs });
    }
  };
  walk(root);
  return out;
}

export function sha256(data: string | Buffer): string {
  return createHash('sha256').update(data).digest('hex');
}

export function sha256File(absPath: string): string | undefined {
  try {
    return sha256(readFileSync(absPath));
  } catch {
    return undefined;
  }
}

/**
 * The provenance header SecureVibe writes as the first line of every file it generates, in the comment syntax of
 * whichever language the file is in ("// Generated by SecureVibe (recipe record-type) — run r_…").
 */
const PROVENANCE_HEADER_LINE = /^(?:\/\/|--|#|<%#)[^\S\r\n]*Generated by SecureVibe\b[^\r\n]*\r?\n/;

/**
 * Hash of a generated file's *content*: the same bytes as `sha256File`, but with the provenance header line
 * removed when the file starts with one. The header carries the run id, so two builds of the same unchanged file
 * never share a `sha256` — this hash does, which is what lets a rebuild tell "this file is byte-for-byte what the
 * earlier check read" from "this file was merely written again". Returns undefined when the file cannot be read.
 */
export function contentSha256File(absPath: string): string | undefined {
  let buf;
  try {
    buf = readFileSync(absPath);
  } catch {
    return undefined;
  }
  // Only text files can carry a header; a binary file hashes as it is.
  if (buf.includes(0)) return sha256(buf);
  const text = buf.toString('utf8');
  return sha256(text.replace(PROVENANCE_HEADER_LINE, ''));
}

/**
 * Converts one glob (`*` within a segment, `**` any depth, `?` one character) into an anchored regular
 * expression. This must stay in step with the agent's own matcher (`matchesGlob` in llm/tools.ts): both read the
 * same path lists out of the template manifest, and `recipes-contract.test.ts` checks that they agree — a
 * disagreement means the fence a recipe is held to is not the fence the agent is held to.
 */
export function globToRegex(glob: string): RegExp {
  let out = '';
  for (let i = 0; i < glob.length; i++) {
    const ch = glob[i]!;
    if (ch === '*') {
      if (glob[i + 1] === '*') {
        const slashAfter = glob[i + 2] === '/';
        i += slashAfter ? 2 : 1;
        out += slashAfter ? '(?:.*/)?' : '.*';
      } else {
        out += '[^/]*';
      }
    } else if (ch === '?') out += '[^/]';
    else if ('\\^$.|+()[]{}'.includes(ch)) out += `\\${ch}`;
    else out += ch;
  }
  return new RegExp(`^${out}$`);
}

/** True when `relPath` matches any glob in `globs`; a `!glob` entry removes an earlier match (order matters). */
export function matchesAnyGlob(relPath: string, globs: string[]): boolean {
  let matched = false;
  for (const g of globs) {
    if (g.startsWith('!')) {
      if (globToRegex(g.slice(1)).test(relPath)) matched = false;
    } else if (globToRegex(g).test(relPath)) {
      matched = true;
    }
  }
  return matched;
}

/**
 * Hash of the security-critical (protected) files of an app, as a person reviews them: a recorded human code
 * review counts only while this hash is unchanged.
 */
export function protectedTreeHash(appDir: string, protectedPaths: string[]): { hash: string; files: string[] } {
  const files = listFiles(appDir)
    .filter((f) => matchesAnyGlob(f.relPath, protectedPaths))
    .sort((a, b) => a.relPath.localeCompare(b.relPath));
  const hash = createHash('sha256');
  for (const f of files) hash.update(`${f.relPath}:${sha256File(f.absPath) ?? ''}\n`);
  return { hash: hash.digest('hex'), files: files.map((f) => f.relPath) };
}
