/**
 * Code emitters for the record-reminder recipe: a scheduled job that emails the owner of a record shortly before
 * the date on it.
 *
 * Three decisions shape the emitted code, and each one is a test rather than a promise:
 *  - the address comes from the record's `owner_id`, looked up in `users` — never from a field of the record — so a
 *    reminder cannot be sent anywhere the record does not already belong;
 *  - a run sends at most `MAX_PER_RUN` messages, and a record is marked before its message is sent, so neither a
 *    clock jump nor a second run can flood a mailbox;
 *  - the message carries the date and a link and nothing else. Mail sits on disks and servers the app does not
 *    control, so no record content travels in it.
 *
 * Sending goes through the template's own mailer (`src/lib/mailer.ts`), which sanitises the headers and writes to a
 * local outbox when no SMTP server is configured; the job itself is declared in code and registered through
 * `src/lib/scheduler.ts`, which gives it a lease so two ticks cannot run it at once.
 */
import { dateFieldOf, type EntityPlan } from '../record-type/fields.js';

const HEADER = (runId: string) => `// Generated by SecureVibe (recipe record-reminder) — run ${runId}\n`;

export interface ReminderField {
  column: string;
  prop: string;
  label: string;
  /** A date alone, or a date and a time. */
  granularity: 'date' | 'datetime';
}

export interface ReminderPlan {
  entity: EntityPlan;
  /** The date the reminder is about. */
  field: ReminderField;
  moduleDir: string;
  jobName: string;
  /** How far ahead the job looks, in hours. */
  horizonHours: number;
  /** The most messages one run may send. */
  maxPerRun: number;
}

/**
 * The date a reminder is about, read off the one shared rule (`dateFieldOf`) so this recipe and the what-is-coming-up
 * page can never disagree about which date a record type is about.
 *
 * That rule leaves out a date the person marked sensitive, and for a reminder that matters more than it does for a
 * page: the message is an email, and a reminder carries the date itself. Sending a date somebody marked sensitive to
 * a mail server is exactly the thing the rest of this recipe is careful about, so a record type whose only date is
 * sensitive gets no reminder and the owner is told why (see `declined`).
 */
export function reminderFieldOf(entity: EntityPlan): ReminderField | undefined {
  const field = dateFieldOf(entity);
  if (!field) return undefined;
  return { column: field.column, prop: field.prop, label: field.label, granularity: field.granularity };
}

/** Dates that would have carried a reminder but are left alone because the person marked them sensitive. */
export function sensitiveDatesOf(entity: EntityPlan): { label: string }[] {
  if (dateFieldOf(entity)) return [];
  return entity.fields
    .filter((f) => f.field.sensitive && (f.control === 'date' || f.control === 'datetime-local'))
    .map((f) => ({ label: f.field.label }));
}

export function reminderPlan(entity: EntityPlan): ReminderPlan | undefined {
  const field = reminderFieldOf(entity);
  if (!field) return undefined;
  return {
    entity,
    field,
    moduleDir: `${entity.moduleDir}-reminders`,
    jobName: `${entity.moduleDir}-reminder`,
    horizonHours: 24,
    maxPerRun: 50,
  };
}

export function emitMigration(plan: ReminderPlan, runId: string): string {
  return `-- Generated by SecureVibe (recipe record-reminder) — run ${runId}
-- Remembers when a reminder about ${plan.entity.entity.label} was sent, so nobody is reminded about the same one twice.
ALTER TABLE ${plan.entity.table} ADD COLUMN reminded_at TEXT;
CREATE INDEX IF NOT EXISTS idx_${plan.entity.table}_reminder ON ${plan.entity.table}(${plan.field.column}, reminded_at);
`;
}

export function emitJob(plan: ReminderPlan, runId: string): string {
  const entity = plan.entity;
  const label = entity.entity.label;
  const lower = label.toLowerCase();
  const article = /^[aeiou]/.test(lower) ? 'an' : 'a';
  // The date is stored exactly as it was typed ("2026-03-04T09:00"), so the window is compared in the same shape.
  const keyLength = plan.field.granularity === 'date' ? 10 : 16;

  return `${HEADER(runId)}/**
 * Reminds the owner of ${article} ${lower} shortly before its ${plan.field.label.toLowerCase()}.
 *
 * The job is declared here in code — nothing about it comes from a request — and is registered through
 * src/lib/scheduler.ts, which gives it a lease so two ticks can never run it at once. Three rules make it safe:
 *
 *  - the address is looked up from the record's owner, never taken from the record, so a reminder cannot reach
 *    anybody the record does not already belong to;
 *  - a record is marked as reminded before its message is sent, and one run sends at most ${plan.maxPerRun}, so neither a
 *    second run nor a clock jump can flood a mailbox. A message that fails to send is logged and not retried, which
 *    is the safer way round for something that arrives in a person's inbox;
 *  - the message carries the date and a link and nothing else. Mail rests on disks this app does not control, so no
 *    ${lower} content travels in it.
 */
import type { Router } from 'express';
import { all, nowIso, run } from '../../db/index.ts';
import { config } from '../../config.ts';
import { logger } from '../../lib/logger.ts';
import { sendMail } from '../../lib/mailer.ts';
import { registerJob } from '../../lib/scheduler.ts';

/**
 * The record type's table. Written out here rather than imported so that every query below is plainly a fixed
 * string: nothing about a query is assembled while the app runs.
 */
const TABLE = '${entity.table}';

export const JOB_NAME = '${plan.jobName}';

/** How far ahead the job looks, and the most messages one run may send. */
const HORIZON_MS = ${plan.horizonHours} * 60 * 60 * 1000;
export const MAX_PER_RUN = ${plan.maxPerRun};

/** Runs often enough that a reminder is never more than an hour late, and cheaply enough that it costs nothing. */
const EVERY_HOUR_MS = 60 * 60 * 1000;

const DUE_SQL = \`SELECT r.id AS id, r.${plan.field.column} AS due_at, u.email AS email, u.status AS status
   FROM \${TABLE} r JOIN users u ON u.id = r.owner_id
   WHERE r.reminded_at IS NULL AND r.${plan.field.column} IS NOT NULL AND r.${plan.field.column} >= ? AND r.${plan.field.column} <= ?
   ORDER BY r.${plan.field.column} ASC LIMIT ?\`;
const MARK_SQL = \`UPDATE \${TABLE} SET reminded_at = ? WHERE id = ? AND reminded_at IS NULL\`;

interface DueRow {
  id: string;
  due_at: string;
  email: string;
  status: string;
}

/**
 * The window, in the same shape the date is stored in: the value came from a date picker in this computer's own
 * time zone, so it is compared against a local-time key rather than a UTC one.
 */
function windowKeys(): { from: string; to: string } {
  const offsetMs = new Date().getTimezoneOffset() * 60_000;
  const localKey = (at: number): string => new Date(at - offsetMs).toISOString().slice(0, ${keyLength});
  const now = Date.now();
  return { from: localKey(now), to: localKey(now + HORIZON_MS) };
}

/** What the owner is told: when it is, and where to look. Never what the ${lower} says. */
function messageFor(row: DueRow): { subject: string; text: string } {
  return {
    subject: \`\${config.appName}: ${lower} coming up\`,
    text: [
      \`You have ${article} ${lower} on \${row.due_at.replace('T', ' at ')}.\`,
      '',
      \`Sign in to see it: ${entity.base}/\${row.id}\`,
      '',
      'You are told this once. Nothing you wrote is repeated in this message, because email is not a private place.',
    ].join('\\n'),
  };
}

/**
 * Sends the reminders that are due. Exported so the app's own tests can run it; the scheduler is what calls it in
 * a running app.
 */
export async function remindDue${entity.pascalName}(): Promise<{ sent: number; failed: number }> {
  const { from, to } = windowKeys();
  const due = all<DueRow>(DUE_SQL, [from, to, MAX_PER_RUN]);
  let sent = 0;
  let failed = 0;
  for (const row of due) {
    // A disabled or deleted account is not written to at all.
    if (row.status !== 'active') continue;
    // Marked first: if sending fails, nobody is reminded twice about the same ${lower}.
    if (run(MARK_SQL, [nowIso(), row.id]).changes !== 1) continue;
    const message = messageFor(row);
    try {
      await sendMail({ to: row.email, subject: message.subject, text: message.text });
      sent += 1;
    } catch (err) {
      failed += 1;
      logger.error({ job: JOB_NAME, record: row.id, err: err instanceof Error ? err.message : String(err) }, 'a reminder could not be sent');
    }
  }
  if (sent > 0 || failed > 0) logger.info({ job: JOB_NAME, sent, failed, window: { from, to } }, 'reminders processed');
  return { sent, failed };
}

export function register(_router: Router): void {
  registerJob({
    name: JOB_NAME,
    description: 'Emails the owner of ${article} ${lower} up to ${plan.horizonHours} hours before its ${plan.field.label.toLowerCase()}.',
    intervalMs: EVERY_HOUR_MS,
    // The job's own signature returns nothing; the counts are for the app's tests and the log line.
    run: async () => {
      await remindDue${entity.pascalName}();
    },
  });
}
`;
}
