/**
 * compliance-report.{md,html,json} (CONTRACTS §9.6, DESIGN §13.12 report section list — exact 13 sections).
 */
import type { RequirementResult, StandardId } from '@shared/compliance.js';
import type { Threat } from '@shared/design.js';
import { escapeHtml } from './escape.js';
import { htmlList, htmlTable } from './html-table.js';
import { statusBadge, sbdBadge, sbdText, ratingBadge, ratingText, statusText, priorityText } from './badges.js';
import { mdBullets, mdTable } from './md.js';
import { adrAnchor, adrSectionHtml, adrSectionMarkdown, readAppAdrs } from './adrs.js';
import { glossaryHtml, glossaryMarkdown } from './glossary.js';
import { renderPage, type Banner, type TocEntry } from './page.js';
import { coverageRanText, type ReportModel } from './types.js';

const NON_GOALS = [
  'Native mobile apps',
  'Microservice topologies',
  'Automated cloud deployment',
  'Social/OAuth sign-in (a later step, reported as Not applicable)',
  'Retrieval-augmented generation or vector stores',
];

function standardLabel(id: StandardId): string {
  return id === 'asvs' ? 'ASVS' : id === 'aisvs' ? 'AISVS' : 'AISVS Appendix C';
}

function findingsAffecting(input: ReportModel): { id: string; result: RequirementResult }[] {
  const rows: { id: string; result: RequirementResult }[] = [];
  const all = [...input.compliance.asvs.results, ...(input.compliance.aisvs?.results ?? []), ...(input.compliance.appendixC?.results ?? [])];
  for (const r of all) for (const fid of r.findingIds) rows.push({ id: fid, result: r });
  return rows;
}

function threatRowMd(t: Threat): (string | number)[] {
  return [t.id, t.stride, t.target, t.riskLevel, t.status, t.description];
}

/** Section number of the architecture decision records (after provenance). */
const ADR_SECTION = 14;

export function renderComplianceReport(input: ReportModel): { md: string; html: string; json: string } {
  const { design, compliance } = input;
  const profile = input.profile;
  const json = JSON.stringify(compliance, null, 2);

  // ---- shared row computations -------------------------------------------------------------
  const requirementsByChapter = (results: RequirementResult[]) => {
    const map = new Map<string, { name: string; rows: RequirementResult[] }>();
    for (const r of results) {
      if (!map.has(r.chapterId)) map.set(r.chapterId, { name: r.chapterName, rows: [] });
      map.get(r.chapterId)!.rows.push(r);
    }
    return [...map.entries()].sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }));
  };

  const findingsRows = findingsAffecting(input);
  const findingsById = new Map(input.findings.map((f) => [f.id, f]));
  const uniqueFindingIds = [...new Set(findingsRows.map((r) => r.id))];

  const manualByWho = new Map<string, typeof compliance.manualVerification>();
  for (const m of compliance.manualVerification) {
    const list = manualByWho.get(m.manual.whoCanDo) ?? [];
    list.push(m);
    manualByWho.set(m.manual.whoCanDo, list);
  }

  // ---- Markdown ------------------------------------------------------------------------------
  const md: string[] = [];
  md.push(`# ${profile?.app.name ?? design.plainLanguageSummary.split('.')[0]} — compliance report`);
  md.push('');
  md.push(
    `This report says which of the OWASP Application Security Verification Standard (ASVS), the OWASP AI Security Verification Standard (AISVS) and the Secure by Design checklist SecureVibe could verify for this app, and how. It is an automated and AI-assisted assessment, not a certification.`,
  );
  if (!compliance.humanReview.performed) {
    md.push('', '**This code was generated by an AI and has not been reviewed by a qualified human engineer.**');
  }

  md.push('', '## 1. Scope & what was assessed', '');
  md.push(
    mdBullets([
      `App: **${profile?.app.name ?? 'this app'}** — ${profile?.app.description ?? ''}`,
      `Audience: ${profile?.users.audience ?? 'unknown'}. Deployment: ${profile?.deployment.target ?? 'unknown'}.`,
      `Target verification level: **${design.applicability.targetLevel}** — ${design.applicability.targetLevelRule}`,
      `ASVS ${compliance.asvs.summary.version}: ${compliance.asvs.summary.applicableCount} applicable requirements.`,
      `AISVS ${compliance.aisvs?.summary.version ?? '1.0'}: ${compliance.aisvs ? `${compliance.aisvs.summary.applicableCount} applicable requirements.` : `not evaluated — ${design.applicability.aisvs.reason}`}`,
      `AISVS Appendix C (the AI-assisted build process): ${compliance.appendixC?.summary.applicableCount ?? 0} applicable requirements.`,
    ]),
  );
  md.push('', '**Not built by SecureVibe (v1 scope):**', '', mdBullets(NON_GOALS));

  md.push('', '## 2. Coverage limits & methodology', '');
  md.push(compliance.methodology);
  md.push('', '**Limitations:**', '', mdBullets(compliance.limitations));
  md.push(
    '',
    '**Tool coverage:**',
    '',
    mdTable(
      ['Tool', 'Ran', 'What it covers'],
      input.coverage.map((c) => [c.tool, coverageRanText(c), c.covers ?? '']),
    ),
  );

  md.push('', '## 3. Design summary', '');
  md.push('### Secure by Design process', '', mdTable(['Step', 'Name', 'Done', 'Performed by'], compliance.sbd.processSteps.map((s) => [s.step, s.name, s.completed ? 'Yes' : 'No', s.performedBy])));
  md.push(
    '',
    '### Security requirements',
    '',
    mdTable(
      ['Id', 'Requirement', 'Category', 'ASVS', 'AISVS', 'SbD'],
      design.securityRequirements.map((r) => [r.id, r.statement, r.category, r.asvs.join(', '), r.aisvs.join(', '), r.sbd.join(', ')]),
    ),
  );
  md.push('', '### Architecture', '', design.architecture.plainLanguage, '', '```mermaid', design.architecture.mermaid, '```');
  md.push('', '### Assumptions', '', mdBullets([...design.architecture.assumptions, ...design.assumptionsMade]));
  md.push(
    '',
    '### Patterns applied',
    '',
    mdTable(['Pattern', 'Principle', 'Why'], design.patterns.map((p) => [p.name, p.principle, p.why])),
  );
  const appAdrs = readAppAdrs(input.appDir);
  md.push(
    '',
    '### Architecture decisions (ADRs)',
    '',
    mdTable(['Id', 'Title', 'Date'], design.adrs.map((a) => [`[${a.id}](#${adrAnchor(a.id)})`, a.title, a.date])),
    '',
    `Full text: see section ${ADR_SECTION} (${appAdrs.length} more decision record(s) come with the starter application).`,
  );
  const peer = design.peerReview;
  md.push(
    '',
    '### Second opinion (independent AI review of the design)',
    '',
    peer
      ? `Performed by **${peer.performedBy}**${peer.model ? ` (${peer.model})` : ''} on ${peer.performedAt.slice(0, 10)}. ${peer.summary}`
      : 'Not performed for this build.',
  );
  if (peer?.suggestions.length) {
    md.push(
      '',
      mdTable(
        ['Suggestion', 'Severity', 'Decision'],
        peer.suggestions.map((s) => [s.title, s.severity, s.accepted === null ? 'Pending' : s.accepted ? 'Accepted' : `Dismissed${s.dismissReason ? `: ${s.dismissReason}` : ''}`]),
      ),
    );
  }
  const triage = design.riskTriage;
  md.push(
    '',
    '### Extra-care review (risk triage)',
    '',
    mdBullets([
      `Care level: **${triage.extraCareLabel}**`,
      `Checklist score: ${compliance.sbd.score} (escalation threshold ${compliance.sbd.threshold})`,
      `Controls marked "Not applicable": ${compliance.sbd.notApplicableIds.length}`,
      `Escalation: ${compliance.sbd.escalate ? 'required' : 'not required'} — ${compliance.sbd.escalationHandling}`,
    ]),
  );
  if (design.threatModel) {
    md.push(
      '',
      '### Threat model / risk register',
      '',
      design.threatModel.summary,
      '',
      mdTable(['Id', 'STRIDE', 'Target', 'Risk', 'Status', 'Threat'], design.threatModel.threats.map(threatRowMd)),
    );
  }

  md.push('', '## 4. Traceability matrix', '');
  md.push(
    mdTable(
      ['Requirement', 'Statement', 'Controls', 'ASVS', 'AISVS', 'SbD', 'Status'],
      compliance.traceability.map((r) => [r.requirementId, r.statement, r.controls.join(', '), r.asvs.join(', '), r.aisvs.join(', '), r.sbd.join(', '), statusText(r.status === 'verified' ? 'pass' : r.status === 'failing' ? 'fail' : r.status === 'partially-verified' ? 'partial' : 'not-verified')]),
    ),
  );

  md.push('', '## 5. Secure by Design checklist', '');
  md.push(
    mdTable(
      ['Id', 'Statement', 'Critical', 'Status', 'Justification', 'Severity if No', 'Comment', 'Evidence', 'Actions'],
      compliance.sbd.entries.map((e) => [
        e.id,
        e.statement,
        e.critical ? '⚠️ Critical' : '',
        `${sbdText(e.status)} (${e.verification})`,
        e.justification,
        e.severityIfNo,
        e.comment ?? e.note ?? '',
        e.evidence.join(', '),
        e.actions.map((a) => `${a.text} (${a.owner}${a.dueBy ? `, ${a.dueBy}` : ''})`).join('; '),
      ]),
    ),
  );
  md.push(
    '',
    '### Deployment-time view (if this app goes on the internet)',
    '',
    mdTable(['Id', 'Status once online', 'What changes'], compliance.sbd.deploymentTime.map((d) => [d.id, d.status, d.note])),
  );

  for (const [standardId, results, summary] of [
    ['asvs', compliance.asvs.results, compliance.asvs.summary],
    ...(compliance.aisvs ? [['aisvs', compliance.aisvs.results, compliance.aisvs.summary] as const] : []),
  ] as const) {
    md.push(
      '',
      `## ${standardId === 'asvs' ? '6' : '7'}. ${standardLabel(standardId)} results`,
      '',
      `${summary.counts.pass} pass · ${summary.counts['ai-assessed']} AI-assessed · ${summary.counts.documented} documented · ${summary.counts.attested} attested · ${summary.counts.partial} partial · ${summary.counts.fail} fail · ${summary.counts['not-verified']} not verified · ${summary.counts['not-applicable']} not applicable · ${summary.counts['out-of-level']} out of level. Rating: ${ratingText(summary.rating)} — ${summary.ratingReason}`,
    );
    for (const [chapterId, chapter] of requirementsByChapter(results)) {
      md.push('', `### ${chapterId} — ${chapter.name}`, '', mdTable(['Id', 'Requirement', 'Status', 'Rationale'], chapter.rows.map((r) => [r.id, r.description, statusText(r.status), r.rationale])));
    }
  }
  if (!compliance.aisvs) {
    md.push('', '## 7. AISVS results', '', `Not evaluated: ${design.applicability.aisvs.reason}`);
  }

  md.push('', '## 8. AI-assisted development process (AISVS Appendix C)', '');
  if (compliance.appendixC) {
    md.push(
      `${compliance.appendixC.summary.counts.pass} pass · ${compliance.appendixC.summary.counts.partial} partial · ${compliance.appendixC.summary.counts.fail} fail · ${compliance.appendixC.summary.counts['not-verified']} not verified.`,
      '',
      mdTable(['Id', 'Requirement', 'Status', 'Rationale'], compliance.appendixC.results.map((r) => [r.id, r.description, statusText(r.status), r.rationale])),
    );
  }

  md.push('', '## 9. Findings affecting compliance', '');
  md.push(
    mdTable(
      ['Finding', 'Title', 'Priority', 'Status', 'Affects requirement(s)'],
      uniqueFindingIds.map((id) => {
        const f = findingsById.get(id);
        const reqs = findingsRows.filter((r) => r.id === id).map((r) => r.result.id);
        return [id, f?.title ?? '(unknown)', f ? priorityText(f.priority) : '', f?.status ?? '', reqs.join(', ')];
      }),
    ),
  );

  md.push('', '## 10. Manual verification', '');
  for (const [who, items] of manualByWho) {
    md.push('', `### For the ${who}`, '');
    if (who === 'owner') {
      md.push(mdBullets(items.map((m) => `**${m.requirementId}** — ${m.manual.question ?? 'Please confirm this is in place.'} \`[ ] Yes  [ ] No\``)));
    } else {
      md.push(mdTable(['Requirement', 'What to do', 'Effort'], items.map((m) => [m.requirementId, m.manual.steps.join(' ') || (m.manual.question ?? ''), m.manual.estimatedEffort])));
    }
  }

  md.push('', '## 11. Prioritised recommendations', '');
  md.push(mdTable(['Priority', 'Title', 'Who', 'Effort'], compliance.recommendations.map((r) => [priorityLabelForRec(r.priority), r.title, r.who, r.effort ?? ''])));

  md.push('', '## 12. Human sign-off', '');
  md.push(
    mdBullets([
      compliance.humanReview.performed
        ? `Human code review performed by **${compliance.humanReview.reviewedBy}** on ${compliance.humanReview.reviewedAt?.slice(0, 10)} (${compliance.humanReview.filesReviewed.length} file(s)).`
        : 'No human code review has been recorded yet for this build.',
      design.riskTriage.escalate
        ? input.project.escalationAcknowledgedAt
          ? `Extra-care review acknowledged by the owner on ${input.project.escalationAcknowledgedAt.slice(0, 10)}.`
          : 'Extra-care review has not yet been acknowledged by the owner.'
        : 'No extra-care escalation was required for this design.',
      `${input.project.attestations.length} owner attestation(s) recorded.`,
    ]),
  );

  md.push('', '## 13. Provenance', '');
  md.push(
    mdBullets([
      `Run: ${input.provenance.runId} on ${input.provenance.generatedAt.slice(0, 10)} (mode: ${input.provenance.mode}).`,
      `SecureVibe ${input.provenance.securevibeVersion}, template ${input.provenance.templateVersion}.`,
      `Frameworks: ASVS ${input.provenance.frameworkVersions.asvs}, AISVS ${input.provenance.frameworkVersions.aisvs}, SbD ${input.provenance.frameworkVersions.sbd}.`,
      `Human involvement: ${input.provenance.humanInvolvement.summary}`,
      `Code tree hash: \`${input.provenance.codeTreeHash}\`.`,
      `Sandbox: ${input.provenance.sandbox.note}`,
    ]),
  );
  md.push(...adrSectionMarkdown(design.adrs, appAdrs, ADR_SECTION));
  md.push('', glossaryMarkdown(input.knowledge.glossary));

  // ---- HTML --------------------------------------------------------------------------------
  const toc: TocEntry[] = [
    { id: 'scope', label: '1. Scope & what was assessed' },
    { id: 'methodology', label: '2. Coverage limits & methodology' },
    { id: 'design-summary', label: '3. Design summary' },
    { id: 'traceability', label: '4. Traceability matrix' },
    { id: 'sbd-checklist', label: '5. Secure by Design checklist' },
    { id: 'asvs-results', label: '6. ASVS results' },
    { id: 'aisvs-results', label: '7. AISVS results' },
    { id: 'appendix-c', label: '8. AI-assisted development process' },
    { id: 'findings', label: '9. Findings affecting compliance' },
    { id: 'manual-verification', label: '10. Manual verification' },
    { id: 'recommendations', label: '11. Prioritised recommendations' },
    { id: 'sign-off', label: '12. Human sign-off' },
    { id: 'provenance', label: '13. Provenance' },
    { id: 'adrs', label: `${ADR_SECTION}. Architecture decision records` },
  ];

  const banners: Banner[] = [];
  if (!compliance.humanReview.performed) {
    banners.push({ kind: 'ai-disclaimer', text: 'This code was generated by an AI and has not been reviewed by a qualified human engineer.' });
  }
  if (input.run.mode === 'demo') banners.push({ kind: 'preview', text: 'PREVIEW — built without AI generation or AI review.' });

  const body: string[] = [];
  body.push(`<section id="scope" class="chapter"><h2>1. Scope &amp; what was assessed</h2>`);
  body.push(
    htmlList([
      `App: <strong>${escapeHtml(profile?.app.name ?? 'this app')}</strong> — ${escapeHtml(profile?.app.description ?? '')}`,
      `Audience: ${escapeHtml(profile?.users.audience ?? 'unknown')}. Deployment: ${escapeHtml(profile?.deployment.target ?? 'unknown')}.`,
      `Target verification level: <strong>${design.applicability.targetLevel}</strong> — ${escapeHtml(design.applicability.targetLevelRule)}`,
      `ASVS ${escapeHtml(compliance.asvs.summary.version)}: ${compliance.asvs.summary.applicableCount} applicable requirements.`,
      compliance.aisvs
        ? `AISVS ${escapeHtml(compliance.aisvs.summary.version)}: ${compliance.aisvs.summary.applicableCount} applicable requirements.`
        : `AISVS: not evaluated — ${escapeHtml(design.applicability.aisvs.reason)}`,
    ]),
  );
  body.push(`<p><strong>Not built by SecureVibe (v1 scope):</strong></p>${htmlList(NON_GOALS.map(escapeHtml))}</section>`);

  body.push(`<section id="methodology" class="chapter"><h2>2. Coverage limits &amp; methodology</h2><p>${escapeHtml(compliance.methodology)}</p>`);
  body.push(`<p><strong>Limitations:</strong></p>${htmlList(compliance.limitations.map(escapeHtml))}`);
  body.push(
    htmlTable(
      ['Tool', 'Ran', 'What it covers'],
      input.coverage.map((c) => [escapeHtml(c.tool), coverageRanText(c, escapeHtml), escapeHtml(c.covers ?? '')]),
    ),
  );
  body.push('</section>');

  body.push(`<section id="design-summary" class="chapter"><h2>3. Design summary</h2>`);
  body.push(
    `<details open><summary>Secure by Design process</summary>${htmlTable(
      ['Step', 'Name', 'Done', 'Performed by'],
      compliance.sbd.processSteps.map((s) => [String(s.step), escapeHtml(s.name), s.completed ? 'Yes' : 'No', escapeHtml(s.performedBy)]),
    )}</details>`,
  );
  body.push(
    `<details><summary>Security requirements</summary>${htmlTable(
      ['Id', 'Requirement', 'Category', 'ASVS', 'AISVS', 'SbD'],
      design.securityRequirements.map((r) => [escapeHtml(r.id), escapeHtml(r.statement), escapeHtml(r.category), escapeHtml(r.asvs.join(', ')), escapeHtml(r.aisvs.join(', ')), escapeHtml(r.sbd.join(', '))]),
    )}</details>`,
  );
  body.push(
    `<details><summary>Architecture</summary><p>${escapeHtml(design.architecture.plainLanguage)}</p><pre>${escapeHtml(design.architecture.mermaid)}</pre></details>`,
  );
  body.push(`<details><summary>Assumptions</summary>${htmlList([...design.architecture.assumptions, ...design.assumptionsMade].map(escapeHtml))}</details>`);
  body.push(`<details><summary>Patterns applied</summary>${htmlTable(['Pattern', 'Principle', 'Why'], design.patterns.map((p) => [escapeHtml(p.name), escapeHtml(p.principle), escapeHtml(p.why)]))}</details>`);
  body.push(
    `<details open><summary>Architecture decisions (ADRs)</summary>${htmlTable(
      ['Id', 'Title', 'Date'],
      design.adrs.map((a) => [`<a href="#${adrAnchor(a.id)}">${escapeHtml(a.id)}</a>`, escapeHtml(a.title), escapeHtml(a.date)]),
    )}<p>Full text of every decision, including ${appAdrs.length} that come with the starter application: <a href="#adrs">section ${ADR_SECTION}</a>.</p></details>`,
  );
  body.push(
    `<details><summary>Second opinion</summary><p>${
      peer ? `Performed by <strong>${escapeHtml(peer.performedBy)}</strong>${peer.model ? ` (${escapeHtml(peer.model)})` : ''} on ${escapeHtml(peer.performedAt.slice(0, 10))}. ${escapeHtml(peer.summary)}` : 'Not performed for this build.'
    }</p>${
      peer?.suggestions.length
        ? htmlTable(
            ['Suggestion', 'Severity', 'Decision'],
            peer.suggestions.map((s) => [escapeHtml(s.title), escapeHtml(s.severity), s.accepted === null ? 'Pending' : s.accepted ? 'Accepted' : `Dismissed${s.dismissReason ? `: ${escapeHtml(s.dismissReason)}` : ''}`]),
          )
        : ''
    }</details>`,
  );
  body.push(
    `<details open><summary>Extra-care review (risk triage)</summary>${htmlList([
      `Care level: <strong>${escapeHtml(triage.extraCareLabel)}</strong>`,
      `Checklist score: ${compliance.sbd.score} (escalation threshold ${compliance.sbd.threshold})`,
      `Controls marked "Not applicable": ${compliance.sbd.notApplicableIds.length}`,
      `Escalation: ${compliance.sbd.escalate ? 'required' : 'not required'} — ${escapeHtml(compliance.sbd.escalationHandling)}`,
    ])}</details>`,
  );
  if (design.threatModel) {
    body.push(
      `<details><summary>Threat model / risk register</summary><p>${escapeHtml(design.threatModel.summary)}</p>${htmlTable(
        ['Id', 'STRIDE', 'Target', 'Risk', 'Status', 'Threat'],
        design.threatModel.threats.map((t) => [escapeHtml(t.id), escapeHtml(t.stride), escapeHtml(t.target), escapeHtml(t.riskLevel), escapeHtml(t.status), escapeHtml(t.description)]),
      )}</details>`,
    );
  }
  body.push('</section>');

  body.push(
    `<section id="traceability" class="chapter"><h2>4. Traceability matrix</h2>${htmlTable(
      ['Requirement', 'Statement', 'Controls', 'ASVS', 'AISVS', 'SbD', 'Status'],
      compliance.traceability.map((r) => [
        `<span id="tr-${escapeHtml(r.requirementId)}">${escapeHtml(r.requirementId)}</span>`,
        escapeHtml(r.statement),
        escapeHtml(r.controls.join(', ')),
        escapeHtml(r.asvs.join(', ')),
        escapeHtml(r.aisvs.join(', ')),
        escapeHtml(r.sbd.join(', ')),
        r.status,
      ]),
    )}</section>`,
  );

  body.push(`<section id="sbd-checklist" class="chapter"><h2>5. Secure by Design checklist</h2>`);
  body.push(
    htmlTable(
      ['Id', 'Statement', 'Critical', 'Status', 'Justification', 'Severity if No', 'Comment', 'Evidence', 'Actions'],
      compliance.sbd.entries.map((e) => [
        `<span id="sbd-${escapeHtml(e.id)}">${escapeHtml(e.id)}</span>`,
        escapeHtml(e.statement),
        e.critical ? '<span class="critical-flag">⚠️ Critical</span>' : '',
        `${sbdBadge(e.status)} <span class="muted">(${escapeHtml(e.verification)})</span>`,
        escapeHtml(e.justification),
        escapeHtml(e.severityIfNo),
        escapeHtml(e.comment ?? e.note ?? ''),
        escapeHtml(e.evidence.join(', ')),
        escapeHtml(e.actions.map((a) => `${a.text} (${a.owner}${a.dueBy ? `, ${a.dueBy}` : ''})`).join('; ')),
      ]),
    ),
  );
  body.push(
    `<details><summary>Deployment-time view (if this app goes on the internet)</summary>${htmlTable(
      ['Id', 'Status once online', 'What changes'],
      compliance.sbd.deploymentTime.map((d) => [escapeHtml(d.id), escapeHtml(d.status), escapeHtml(d.note)]),
    )}</details></section>`,
  );

  function requirementsSectionHtml(id: string, heading: string, results: RequirementResult[], summary: (typeof compliance.asvs)['summary']): string {
    const chapters = requirementsByChapter(results);
    const parts = chapters
      .map(
        ([chapterId, chapter]) =>
          `<details><summary>${escapeHtml(chapterId)} — ${escapeHtml(chapter.name)} (${chapter.rows.length})</summary>${htmlTable(
            ['Id', 'Requirement', 'Status', 'Rationale'],
            chapter.rows.map((r) => [`<span id="req-${escapeHtml(r.id)}">${escapeHtml(r.id)}</span>`, escapeHtml(r.description), statusBadge(r.status), escapeHtml(r.rationale)]),
            { rowClass: (i) => (chapter.rows[i]!.status === 'not-applicable' || chapter.rows[i]!.status === 'out-of-level' ? 'hideable default-hidden' : undefined) },
          )}</details>`,
      )
      .join('\n');
    return `<section id="${id}" class="chapter"><h2>${escapeHtml(heading)}</h2><p>${summary.counts.pass} pass · ${summary.counts['ai-assessed']} AI-assessed · ${summary.counts.documented} documented · ${summary.counts.attested} attested · ${summary.counts.partial} partial · ${summary.counts.fail} fail · ${summary.counts['not-verified']} not verified · ${summary.counts['not-applicable']} not applicable · ${summary.counts['out-of-level']} out of level. Rating: ${ratingBadge(summary.rating)} — ${escapeHtml(summary.ratingReason)}</p>${parts}</section>`;
  }

  body.push(requirementsSectionHtml('asvs-results', '6. ASVS results by chapter', compliance.asvs.results, compliance.asvs.summary));
  body.push(
    compliance.aisvs
      ? requirementsSectionHtml('aisvs-results', '7. AISVS results', compliance.aisvs.results, compliance.aisvs.summary)
      : `<section id="aisvs-results" class="chapter"><h2>7. AISVS results</h2><p>Not evaluated: ${escapeHtml(design.applicability.aisvs.reason)}</p></section>`,
  );
  body.push(
    compliance.appendixC
      ? requirementsSectionHtml('appendix-c', '8. AI-assisted development process (AISVS Appendix C)', compliance.appendixC.results, compliance.appendixC.summary)
      : '',
  );

  body.push(
    `<section id="findings" class="chapter"><h2>9. Findings affecting compliance</h2>${htmlTable(
      ['Finding', 'Title', 'Priority', 'Status', 'Affects requirement(s)'],
      uniqueFindingIds.map((id) => {
        const f = findingsById.get(id);
        const reqs = findingsRows.filter((r) => r.id === id).map((r) => r.result.id);
        return [`<a href="#finding-${escapeHtml(id)}">${escapeHtml(id)}</a>`, escapeHtml(f?.title ?? '(unknown)'), f ? escapeHtml(priorityText(f.priority)) : '', escapeHtml(f?.status ?? ''), escapeHtml(reqs.join(', '))];
      }),
    )}</section>`,
  );

  const manualSections = [...manualByWho.entries()]
    .map(([who, items]) => {
      const rows =
        who === 'owner'
          ? htmlList(items.map((m) => `<strong>${escapeHtml(m.requirementId)}</strong> — ${escapeHtml(m.manual.question ?? 'Please confirm this is in place.')} &nbsp; ☐ Yes &nbsp; ☐ No`))
          : htmlTable(['Requirement', 'What to do', 'Effort'], items.map((m) => [escapeHtml(m.requirementId), escapeHtml(m.manual.steps.join(' ') || (m.manual.question ?? '')), escapeHtml(m.manual.estimatedEffort)]));
      return `<details open><summary>For the ${escapeHtml(who)} (${items.length})</summary>${rows}</details>`;
    })
    .join('\n');
  body.push(`<section id="manual-verification" class="chapter"><h2>10. Manual verification</h2>${manualSections || '<p class="muted">Nothing needs a manual check.</p>'}</section>`);

  body.push(
    `<section id="recommendations" class="chapter"><h2>11. Prioritised recommendations</h2>${htmlTable(
      ['Priority', 'Title', 'Who', 'Effort'],
      compliance.recommendations.map((r) => [escapeHtml(priorityLabelForRec(r.priority)), escapeHtml(r.title), escapeHtml(r.who), escapeHtml(r.effort ?? '')]),
    )}</section>`,
  );

  body.push(
    `<section id="sign-off" class="chapter"><h2>12. Human sign-off</h2>${htmlList([
      compliance.humanReview.performed
        ? `Human code review performed by <strong>${escapeHtml(compliance.humanReview.reviewedBy)}</strong> on ${escapeHtml(compliance.humanReview.reviewedAt?.slice(0, 10) ?? '')} (${compliance.humanReview.filesReviewed.length} file(s)).`
        : 'No human code review has been recorded yet for this build.',
      design.riskTriage.escalate
        ? input.project.escalationAcknowledgedAt
          ? `Extra-care review acknowledged by the owner on ${escapeHtml(input.project.escalationAcknowledgedAt.slice(0, 10))}.`
          : 'Extra-care review has not yet been acknowledged by the owner.'
        : 'No extra-care escalation was required for this design.',
      `${input.project.attestations.length} owner attestation(s) recorded.`,
    ])}</section>`,
  );

  body.push(
    `<section id="provenance" class="chapter"><h2>13. Provenance</h2>${htmlList([
      `Run: <code>${escapeHtml(input.provenance.runId)}</code> on ${escapeHtml(input.provenance.generatedAt.slice(0, 10))} (mode: ${escapeHtml(input.provenance.mode)}).`,
      `SecureVibe ${escapeHtml(input.provenance.securevibeVersion)}, template ${escapeHtml(input.provenance.templateVersion)}.`,
      `Frameworks: ASVS ${escapeHtml(input.provenance.frameworkVersions.asvs)}, AISVS ${escapeHtml(input.provenance.frameworkVersions.aisvs)}, SbD ${escapeHtml(input.provenance.frameworkVersions.sbd)}.`,
      `Human involvement: ${escapeHtml(input.provenance.humanInvolvement.summary)}`,
      `Code tree hash: <code>${escapeHtml(input.provenance.codeTreeHash)}</code>.`,
      `Sandbox: ${escapeHtml(input.provenance.sandbox.note)}`,
    ])}</section>`,
  );

  body.push(adrSectionHtml(design.adrs, appAdrs, ADR_SECTION));

  const html = renderPage({
    title: `${profile?.app.name ?? 'App'} — compliance report`,
    subtitle: compliance.overall.headline,
    generatedAt: compliance.generatedAt,
    banners,
    toc,
    bodyHtml: body.join('\n'),
    glossaryHtml: glossaryHtml(input.knowledge.glossary),
  });

  return { md: md.join('\n'), html, json };
}

function priorityLabelForRec(p: 'high' | 'medium' | 'low'): string {
  return { high: 'High', medium: 'Medium', low: 'Low' }[p];
}
