/** overview.html (DESIGN §13.12): the first thing a non-technical owner reads. HTML only. */
import type { StandardSummary } from '@shared/compliance.js';
import { escapeHtml } from './escape.js';
import { needsGoingOnline } from './going-online.js';
import { htmlList, htmlTable } from './html-table.js';
import { ratingBadge } from './badges.js';
import { renderPage, type Banner, type TocEntry } from './page.js';
import type { ReportModel } from './types.js';

function scorecard(summary: StandardSummary): string {
  const c = summary.counts;
  return `<div class="scorecard" role="group" aria-label="${escapeHtml(summary.name)} scorecard">
<div class="cell"><span class="n">${c.pass}</span>Verified pass</div>
<div class="cell"><span class="n">${c['ai-assessed'] + c.documented + c.attested}</span>AI-assessed / documented / attested</div>
<div class="cell"><span class="n">${c['not-verified']}</span>Not verified</div>
<div class="cell"><span class="n">${c.fail}</span>Fail</div>
</div>`;
}

export function renderOverview(input: ReportModel): string {
  const { compliance, design } = input;
  const toc: TocEntry[] = [
    { id: 'what-you-built', label: 'What you built and how it was assessed' },
    { id: 'can-i-use-it', label: 'Can I use it?' },
    { id: 'top-actions', label: 'Top actions' },
    ...(input.run.ownerTasks && input.run.ownerTasks.length > 0 ? [{ id: 'only-you', label: 'What only you can do' }] : []),
    { id: 'scorecards', label: 'Scorecards' },
    { id: 'not-checked', label: 'What was not checked and why' },
    { id: 'recheck', label: 'How to re-check' },
  ];

  const banners: Banner[] = [];
  if (!compliance.humanReview.performed) banners.push({ kind: 'ai-disclaimer', text: 'This code was generated by an AI and has not been reviewed by a qualified human engineer.' });
  if (input.run.mode === 'demo') banners.push({ kind: 'preview', text: 'PREVIEW — built without AI generation or AI review.' });

  const body: string[] = [];
  body.push(
    `<section id="what-you-built" class="chapter"><h2>What you built and how it was assessed</h2><p>${escapeHtml(design.plainLanguageSummary)}</p><p>${escapeHtml(compliance.methodology)}</p></section>`,
  );

  body.push(
    `<section id="can-i-use-it" class="chapter"><h2>Can I use it?</h2><p><strong>${ratingBadge(compliance.overall.rating)}</strong> — ${escapeHtml(compliance.overall.headline)}</p>${compliance.overall.ratingReason ? `<p class="muted">${escapeHtml(compliance.overall.ratingReason)}</p>` : ''}<p class="muted">${escapeHtml(compliance.overall.canIUseIt)}</p>${
      // What was read, next to what was concluded from it. A score whose coverage is a paragraph away is a score
      // people quote without the coverage.
      compliance.codeCoverage
        ? `<p class="muted"><strong>What was read:</strong> ${escapeHtml(compliance.codeCoverage.summary)}${
            compliance.codeCoverage.languages.length > 0
              ? ` (${compliance.codeCoverage.languages.map((l) => `${escapeHtml(l.language)}: ${l.files} file${l.files === 1 ? '' : 's'}${l.read ? '' : ', not read'}`).join('; ')})`
              : ''
          }</p>`
        : ''
    }</section>`,
  );

  body.push(
    `<section id="top-actions" class="chapter"><h2>Top actions (at most 5)</h2>${htmlTable(
      ['Priority', 'Action', 'Who', 'Effort'],
      compliance.overall.topActions.map((r) => [escapeHtml(r.priority), escapeHtml(r.title), escapeHtml(r.who), escapeHtml(r.effort ?? '')]),
    )}</section>`,
  );

  if (input.run.ownerTasks && input.run.ownerTasks.length > 0) {
    body.push(
      `<section id="only-you" class="chapter"><h2>What only you can do</h2><p class="muted">Worked out from the app itself and your answers. Each one says what stays switched off until it is done.</p>${htmlList(
        input.run.ownerTasks.map((t) => `<strong>${escapeHtml(t.title)}</strong><br>${escapeHtml(t.because)}<br><span class="muted">${escapeHtml(t.staysOff)}</span>`),
      )}</section>`,
    );
  }

  const cards = [scorecard(compliance.asvs.summary), compliance.aisvs ? scorecard(compliance.aisvs.summary) : undefined].filter((s): s is string => Boolean(s));
  body.push(
    `<section id="scorecards" class="chapter"><h2>Scorecards</h2><h3>ASVS ${escapeHtml(compliance.asvs.summary.version)} — Level ${compliance.asvs.summary.targetLevel} ${ratingBadge(compliance.asvs.summary.rating)}</h3>${cards[0]}${
      compliance.aisvs ? `<h3>AISVS ${escapeHtml(compliance.aisvs.summary.version)} ${ratingBadge(compliance.aisvs.summary.rating)}</h3>${cards[1]}` : `<p class="muted">AISVS: not evaluated — ${escapeHtml(design.applicability.aisvs.reason)}</p>`
    }</section>`,
  );

  body.push(
    `<section id="not-checked" class="chapter"><h2>What was not checked and why</h2>${htmlList(compliance.limitations.map(escapeHtml))}${htmlTable(
      ['Requirement', 'Who can check it', 'Effort'],
      compliance.manualVerification.slice(0, 20).map((m) => [escapeHtml(m.requirementId), escapeHtml(m.manual.whoCanDo), escapeHtml(m.manual.estimatedEffort)]),
    )}</section>`,
  );

  body.push(
    `<section id="recheck" class="chapter"><h2>How to re-check</h2><p>Open the full reports for every detail and exact commands.</p>${htmlList([
      'Compliance report — <a href="compliance-report.html"><code>compliance-report.html</code></a>',
      'Security report — <a href="security-report.html"><code>security-report.html</code></a> (section 11 has the exact commands to re-run every check)',
      ...(needsGoingOnline(input)
        ? ['Going-online checklist — <a href="going-online.html"><code>going-online.html</code></a> (before this app is shared beyond this computer)']
        : []),
    ])}</section>`,
  );

  return renderPage({
    title: `${input.profile?.app.name ?? 'Your app'} — overview`,
    subtitle: compliance.overall.headline,
    generatedAt: compliance.generatedAt,
    banners,
    toc,
    bodyHtml: body.join('\n'),
    glossaryHtml: undefined,
    filterLabel: 'Show everything, including items not applicable to this app',
  });
}
