/**
 * Code emitters for the record-attachment recipe: the migration that adds the file columns, the routes that attach
 * and remove a file, and the page a person does it on.
 *
 * The one rule that shapes all of it: uploading is done by the template's own uploads module and nowhere else
 * (SC-12). The attach route calls `receiveUpload` from `src/features/uploads/index.ts`, so the Origin check, the
 * form token, the byte cap, the magic-byte sniff, the storage location and the per-person storage limit are the
 * ones that module already implements and the template already tests. This recipe only decides *which record* a
 * stored file belongs to — and it can never be told which *file*, because the file is the one the caller just sent.
 */
import type { AttachmentField, EntityPlan } from '../record-type/fields.js';
import { commentText } from '../js-literal.js';

const HEADER = (runId: string) => `// Generated by SecureVibe (recipe record-attachment) — run ${runId}\n`;

export interface AttachmentPlan {
  entity: EntityPlan;
  fields: AttachmentField[];
  /** `src/features/<dir>` and `src/views/<dir>`. */
  moduleDir: string;
  /** Where the record's own pages live, e.g. `/bookings`. */
  base: string;
  /** `/bookings/:id/files`. */
  filesPath: string;
}

export function attachmentPlan(entity: EntityPlan): AttachmentPlan {
  return {
    entity,
    fields: entity.attachments,
    moduleDir: `${entity.moduleDir}-files`,
    base: entity.base,
    filesPath: `${entity.base}/:id/files`,
  };
}

/** The page is never public: a file's name can say as much as its contents. */
export function pageAuth(plan: AttachmentPlan): string {
  return plan.entity.publicRead ? "'user'" : plan.entity.readAuth;
}

export function emitMigration(plan: AttachmentPlan, runId: string): string {
  const columns = plan.fields.map((f) => `ALTER TABLE ${plan.entity.table} ADD COLUMN ${f.column} TEXT;`).join('\n');
  return `-- Generated by SecureVibe (recipe record-attachment) — run ${runId}
-- Files attached to ${plan.entity.entity.label}: each column holds the id of a row in \`uploads\`, and is only ever
-- written by the attach route in src/features/${plan.moduleDir}/index.ts.
${columns}
`;
}

export function emitRoutes(plan: AttachmentPlan, runId: string): string {
  const entity = plan.entity;
  const label = entity.entity.label;
  const lower = label.toLowerCase();
  const owner = entity.ownerScoped ? 'owner: OWNER, ' : '';
  const columnList = plan.fields.map((f) => f.column).join(', ');
  const specs = plan.fields
    .map((f) => `  { column: ${JSON.stringify(f.column)}, label: ${JSON.stringify(f.label)}, path: ${JSON.stringify(`${plan.base}/:id/files/${f.column}`)} },`)
    .join('\n');
  // Each column's statements are written out with the column name in the text, so the emitted query is fixed.
  const sqlEntries = plan.fields
    .map(
      (f) => `  ${JSON.stringify(f.column)}: {
    read: \`SELECT ${f.column} AS previous FROM \${TABLE} WHERE id = ?\`,
    write: \`UPDATE \${TABLE} SET ${f.column} = ?, updated_at = ? WHERE id = ?\`,
  },`,
    )
    .join('\n');
  const routes = plan.fields
    .map(
      (f) => `
  // ---------- ${f.label} ----------
  defineRoute(
    router,
    {
      method: 'POST',
      path: '${plan.base}/:id/files/${f.column}',
      auth: ${entity.writeAuth},
      ${owner}entity: '${entity.entity.name}',
      kind: 'page',
      schema: { params: ${entity.pascalName}Params },
      // A multipart body is read by the uploads module itself, so the registry's own token check (which needs a
      // parsed body) cannot run first; the module checks the Origin and the form token as the stream arrives.
      csrf: false,
      rateLimit: 'uploads',
      summary: ${JSON.stringify(`Attach ${f.label.toLowerCase()} to ${/^[aeiou]/.test(lower) ? 'an' : 'a'} ${lower}`)},
    },
    async (req: Request, res: Response) => {
      const record = recordOrNotFound(req);
      const outcome = await receiveUpload(req);
      if (outcome.error) throw new HttpError(outcome.error.status, outcome.error.code, outcome.error.message);
      const replaced = setAttachment(record.id, ${JSON.stringify(f.column)}, outcome.body!.id);
      // The file that was there before is only deleted when it belongs to the person replacing it.
      if (replaced) discardUpload(req, replaced);
      req.session.flash('success', ${JSON.stringify(`${f.label} saved.`)});
      res.redirect(303, \`${plan.base}/\${record.id}/files\`);
    },
  );

  defineRoute(
    router,
    {
      method: 'POST',
      path: '${plan.base}/:id/files/${f.column}/remove',
      auth: ${entity.writeAuth},
      ${owner}entity: '${entity.entity.name}',
      kind: 'page',
      schema: { params: ${entity.pascalName}Params },
      summary: ${JSON.stringify(`Remove ${f.label.toLowerCase()} from ${/^[aeiou]/.test(lower) ? 'an' : 'a'} ${lower}`)},
    },
    (req, res) => {
      const record = recordOrNotFound(req);
      const removed = setAttachment(record.id, ${JSON.stringify(f.column)}, null);
      if (removed) discardUpload(req, removed);
      req.session.flash('success', ${JSON.stringify(`${f.label} removed.`)});
      res.redirect(303, \`${plan.base}/\${record.id}/files\`);
    },
  );`,
    )
    .join('\n');

  return `${HEADER(runId)}/**
 * Files attached to ${commentText(label)} records: the page that shows them, and the routes that attach one and remove one.
 *
 * Uploading itself is done by the template's uploads module (SC-12): \`receiveUpload\` checks the form token, the
 * size, the real file type and the person's storage limit, stores the file outside the web root under a random
 * name, and records it as owned by whoever sent it. This module only points a record's column at what came back,
 * which is why a person can never attach a file belonging to somebody else — the only file they can name is the
 * one they just sent.
 */
import type { Request, Response, Router } from 'express';
import { get, nowIso, run, withTransaction } from '../../db/index.ts';
import { errors, HttpError } from '../../lib/errors.ts';
import { renderPage } from '../../lib/views.ts';
import { defineRoute } from '../../security/routes.ts';
import { receiveUpload } from '../uploads/index.ts';
import { deleteUpload, getUpload } from '../uploads/repo.ts';
import { ${entity.pascalName}Params } from '../${entity.moduleDir}/schema.ts';

const OWNER = { entity: '${entity.entity.name}', param: 'id' } as const;

/**
 * The record type's table. Written out here rather than imported so that every query below is plainly a fixed
 * string: nothing about a query is assembled while the app runs.
 */
const TABLE = '${entity.table}';

interface FileFieldSpec {
  column: string;
  label: string;
  path: string;
}

/** Every file this record type can carry. The columns come from the design, never from a request. */
const FILE_FIELDS: FileFieldSpec[] = [
${specs}
];

/**
 * The query text for each column, written out in full. Reading and writing a file's column therefore picks a fixed
 * statement out of this table instead of building one, and the column name can never come from a request.
 */
const FIELD_SQL: Record<string, { read: string; write: string }> = {
${sqlEntries}
};

interface RecordKeys {
  id: string;
  owner_id: string;
}

/**
 * The record this request is about. For records that belong to one person the route's own ownership rule has
 * already refused anyone else; this only turns a missing record into a plain 404.
 */
function recordOrNotFound(req: Request): RecordKeys {
  const id = (req.valid.params as { id: string }).id;
  const row = get<RecordKeys>(\`SELECT id, owner_id FROM \${TABLE} WHERE id = ?\`, [id]);
  if (!row) throw errors.notFound();
  return row;
}

/** Points one column at an upload (or clears it) and returns the upload id that was there before. */
function setAttachment(recordId: string, column: string, uploadId: string | null): string | null {
  const sql = FIELD_SQL[column];
  if (!sql) throw errors.notFound(); // unreachable: the column comes from FILE_FIELDS, never from the request
  return withTransaction<string | null>(() => {
    const before = get<{ previous: string | null }>(sql.read, [recordId])?.previous ?? null;
    run(sql.write, [uploadId, nowIso(), recordId]);
    return before;
  });
}

/**
 * Deletes a file that is no longer attached — but only when it belongs to the person doing this, or they are an
 * administrator. Another person's file is left alone: they may be using it elsewhere, and it is theirs.
 */
function discardUpload(req: Request, uploadId: string): void {
  const upload = getUpload(uploadId);
  if (!upload) return;
  if (upload.owner_id !== req.user?.id && !req.user?.isAdmin) return;
  deleteUpload(uploadId);
}

export interface AttachmentView {
  column: string;
  label: string;
  attachPath: string;
  removePath: string;
  file: { id: string; name: string } | null;
  /** True when the column names a file that is no longer in the library (its owner deleted it). */
  missing: boolean;
}

/** What the files page shows: one entry per file this record type can carry, filled in or empty. */
function attachmentsFor(recordId: string): AttachmentView[] {
  const row = get<Record<string, string | null>>(\`SELECT ${columnList} FROM \${TABLE} WHERE id = ?\`, [recordId]) ?? {};
  return FILE_FIELDS.map((spec) => {
    const stored = row[spec.column] ?? null;
    const upload = stored ? getUpload(stored) : undefined;
    const attachPath = spec.path.replace(':id', recordId);
    return {
      column: spec.column,
      label: spec.label,
      attachPath,
      removePath: \`\${attachPath}/remove\`,
      file: upload ? { id: upload.id, name: upload.original_name } : null,
      missing: stored !== null && upload === undefined,
    };
  });
}

export function register(router: Router): void {
  defineRoute(
    router,
    {
      method: 'GET',
      path: '${plan.filesPath}',
      auth: ${pageAuth(plan)},
      ${owner}entity: '${entity.entity.name}',
      kind: 'page',
      schema: { params: ${entity.pascalName}Params },
      summary: ${JSON.stringify(`Files kept with ${/^[aeiou]/.test(lower) ? 'an' : 'a'} ${lower}`)},
    },
    (req, res) => {
      const record = recordOrNotFound(req);
      renderPage(req, res, '${plan.moduleDir}/index', {
        title: ${JSON.stringify(plan.fields.length === 1 ? plan.fields[0]!.label : `Files for this ${lower}`)},
        recordId: record.id,
        recordPath: \`${plan.base}/\${record.id}\`,
        attachments: attachmentsFor(record.id),
      });
    },
  );
${routes}
}
`;
}

export function emitView(plan: AttachmentPlan): string {
  const lower = plan.entity.entity.label.toLowerCase();
  return `<section class="card narrow">
  <h1><%= title %></h1>
  <% for (const a of attachments) { %>
    <div class="field">
      <h2><%= a.label %></h2>
      <% if (a.file) { %>
        <p><a href="/uploads/<%= a.file.id %>"><%= a.file.name %></a></p>
        <form method="post" action="<%= a.removePath %>" data-confirm="Remove this file?">
          <input type="hidden" name="_csrf" value="<%= csrfToken %>">
          <button type="submit" class="button button-danger button-small">Remove</button>
        </form>
        <p class="hint">Attaching another file replaces this one.</p>
      <% } else if (a.missing) { %>
        <p class="muted">The file that was here has been deleted from your files.</p>
      <% } else { %>
        <p class="muted">No file yet.</p>
      <% } %>
      <form method="post" action="<%= a.attachPath %>" enctype="multipart/form-data">
        <input type="hidden" name="_csrf" value="<%= csrfToken %>">
        <input id="file-<%= a.column %>" name="file" type="file" required>
        <button type="submit" class="button">Attach</button>
      </form>
    </div>
  <% } %>
  <p class="muted"><a href="<%= recordPath %>">Back to this ${lower}</a></p>
</section>
`;
}
