/**
 * Code emitters for the needs-attention recipe: one page across every record type that has a date on it, showing
 * what falls in a window around today.
 *
 * This is the only page a recipe writes that reads more than one record type, and that is the whole of its
 * difficulty. Each record type carries its own answer to "who may see this", and those answers differ inside one
 * app: one kind of record belongs to the person who added it, another is shared with everybody signed in, a third
 * is for administrators only. A page that showed them all together would quietly hand each person the union of all
 * of it. So the page is built section by section, each section carrying the rule its own record type was given:
 *
 *  - **belongs to one person** — the signed-in person's own records; an administrator, who may already read every
 *    record, sees them all;
 *  - **administrators only** — the section is not built at all for anybody else. Not hidden, not empty: the query
 *    never runs and the records never reach the page;
 *  - **shared, or public to read** — every record, as the record type's own list already shows.
 *
 * The page needs a sign-in even where a record type is public to read, for the reason the report and chart pages do:
 * a list shows one page of records, and this gathers what is near today across everything at once.
 *
 * Two things it refuses to say. It never calls a record late, overdue or due: `dateFieldOf` gives the first date
 * the person described, and that is a point in time, not a deadline — it may as easily be a birthday or the day
 * something was recorded. The page says "on 14 March" and lets the reader decide what that means. And a record whose
 * title was marked sensitive is listed by its date alone, with a link, because a page that gathers records from
 * across the app is read in more places than the record's own page is.
 */
import type { DateField, EntityPlan } from '../record-type/fields.js';

const HEADER = (runId: string) => `// Generated by SecureVibe (recipe needs-attention) — run ${runId}\n`;

/** One record type's section of the page. */
export interface AttentionSection {
  entity: EntityPlan;
  date: DateField;
  /** The field whose text names a record, or nothing when there is none to show. */
  title: { column: string; label: string } | undefined;
  /** Why no name is shown, when a name exists but may not be. */
  titleWithheld: string | undefined;
}

export interface AttentionPlan {
  sections: AttentionSection[];
  moduleDir: string;
  path: string;
  title: string;
  /** Days back the page always looks. Fixed, so there is one fewer thing to get wrong in an address bar. */
  daysBack: number;
  /** Rows per section. A page that gathers from everywhere has to stop somewhere. */
  perSection: number;
}

/**
 * The text that names a record on this page, or nothing.
 *
 * A record's own display title is the first required text field (`titleField`). Here it is shown only when the
 * person did not mark it sensitive: a sensitive title is stored encrypted, and putting it on a page that gathers
 * records from across the app would undo the point of that. The record is still listed — by its date, with a link —
 * because leaving it out silently would be worse than listing it plainly.
 */
export function titleOf(entity: EntityPlan): { title: AttentionSection['title']; withheld: string | undefined } {
  const field = entity.titleField;
  if (!field) return { title: undefined, withheld: undefined };
  if (field.field.sensitive) return { title: undefined, withheld: field.field.label };
  return { title: { column: field.column, label: field.field.label }, withheld: undefined };
}

export function attentionPlan(entities: { entity: EntityPlan; date: DateField }[]): AttentionPlan {
  return {
    sections: entities.map(({ entity, date }) => {
      const { title, withheld } = titleOf(entity);
      return { entity, date, title, titleWithheld: withheld };
    }),
    moduleDir: 'coming-up',
    path: '/coming-up',
    title: 'Coming up',
    daysBack: 7,
    perSection: 10,
  };
}

/** A section only administrators may see is built behind a check on the server, never hidden in the page. */
function guardFor(section: AttentionSection): string {
  if (section.entity.adminOnly) return 'req.user?.isAdmin === true';
  return 'true';
}

export function emitRoutes(plan: AttentionPlan, runId: string): string {
  const sectionConsts = plan.sections
    .map((s) => {
      const cols = ['id', `${s.date.column} AS at`, ...(s.title ? [`${s.title.column} AS name`] : [])].join(', ');
      const where = `${s.date.column} >= ? AND ${s.date.column} <= ?`;
      const order = `ORDER BY ${s.date.column} ASC LIMIT ${plan.perSection}`;
      return `  ${JSON.stringify(s.entity.entity.name)}: {
    all: \`SELECT ${cols} FROM ${s.entity.table} WHERE ${where} ${order}\`,
    owner: \`SELECT ${cols} FROM ${s.entity.table} WHERE ${where} AND owner_id = ? ${order}\`,
  },`;
    })
    .join('\n');

  const sectionLines = plan.sections
    .map(
      (s) => `    {
      entity: ${JSON.stringify(s.entity.entity.name)},
      heading: ${JSON.stringify(s.entity.entity.pluralLabel ?? `${s.entity.entity.label}s`)},
      dateLabel: ${JSON.stringify(s.date.label)},
      href: ${JSON.stringify(s.entity.base)},
      // Only the signed-in person's own records where records belong to one person; an administrator, who may
      // already read every record, sees them all.
      ownerScoped: ${s.entity.ownerScoped ? 'true' : 'false'},
      // A section for a record type only administrators may read is not built for anybody else: the query below
      // never runs and no record of that kind reaches the page.
      visible: ${guardFor(s)},
      hasName: ${s.title ? 'true' : 'false'},
      nameWithheld: ${s.titleWithheld ? JSON.stringify(s.titleWithheld) : 'undefined'},
    },`,
    )
    .join('\n');

  return `${HEADER(runId)}/**
 * ${plan.title}: what falls near today, across every kind of record that has a date on it.
 *
 * Each section carries the rule its own record type was given, because those rules differ inside one app. A record
 * type that belongs to one person is read for that person only; one that only administrators may read has no
 * section at all for anybody else, so its records are never fetched rather than fetched and hidden; a shared one is
 * read in full, as its own list page already shows it.
 *
 * Nothing here calls a record late or due. The date is the first one the person described, which is a point in
 * time and not a deadline, so the page says when it is and leaves the meaning to the reader.
 */
import type { Request, Response, Router } from 'express';
import { z } from 'zod';
import { all } from '../../db/index.ts';
import { renderPage } from '../../lib/views.ts';
import { defineRoute } from '../../security/routes.ts';

/** Every statement this page can run, written out in full at generation time. Nothing is assembled while it runs. */
const SQL: Record<string, { all: string; owner: string }> = {
${sectionConsts}
};

/** How far ahead to look. A number the person chose, within limits, or thirty days. */
const AttentionQuery = z.strictObject({
  days: z.preprocess((v) => (v === '' || v === null ? undefined : v), z.coerce.number().int().min(1).max(365).optional()),
});

/** Days back is fixed: one number in an address bar is enough to have to check. */
const DAYS_BACK = ${plan.daysBack};

interface Row {
  id: string;
  at: string | null;
  name?: string | null;
}

interface Entry {
  href: string;
  /** The text that names the record, or an empty string when this page may not show one. */
  name: string;
  /** The date as it is stored, which is what the page shows. */
  at: string;
}

interface Section {
  heading: string;
  dateLabel: string;
  href: string;
  entries: Entry[];
  /** True when this record type has more near today than the page is showing. */
  more: boolean;
  /** Set when the record type has a name but this page may not show it. */
  nameWithheld: string | undefined;
}

export function register(router: Router): void {
  defineRoute(
    router,
    {
      method: 'GET',
      path: '${plan.path}',
      auth: 'user',
      kind: 'page',
      schema: { query: AttentionQuery },
      summary: ${JSON.stringify(plan.title)},
      // A page that belongs to no single record type has to ask for its place in the menu, or nothing links to it.
      menu: ${JSON.stringify(plan.title)},
    },
    (req: Request, res: Response) => {
      const days = (req.valid.query as { days?: number }).days ?? 30;
      const now = Date.now();
      const from = new Date(now - DAYS_BACK * 86400000).toISOString().slice(0, 10);
      const to = new Date(now + days * 86400000).toISOString().slice(0, 10);
      // Both ends are compared as text, which is why they are widened to cover a whole day: a date column holds
      // "2026-03-14" and a date-and-time column holds "2026-03-14T09:00", and both sort correctly as strings.
      const earliest = \`\${from}T00:00:00.000Z\`;
      const latest = \`\${to}T23:59:59.999Z\`;

      const sections: Section[] = [];
      for (const spec of [
${sectionLines}
      ]) {
        if (!spec.visible) continue;
        const sql = SQL[spec.entity];
        if (!sql) continue; // unreachable: the key is this page's own, never a value from a request
        const ownerId = spec.ownerScoped && !req.user?.isAdmin ? req.user?.id : undefined;
        const rows = ownerId ? all<Row>(sql.owner, [earliest, latest, ownerId]) : all<Row>(sql.all, [earliest, latest]);
        const entries: Entry[] = rows
          .filter((row) => typeof row.at === 'string' && row.at !== '')
          .map((row) => ({
            href: \`\${spec.href}/\${row.id}\`,
            name: spec.hasName && typeof row.name === 'string' ? row.name : '',
            at: String(row.at),
          }));
        if (entries.length === 0) continue;
        sections.push({
          heading: spec.heading,
          dateLabel: spec.dateLabel,
          href: spec.href,
          entries,
          more: rows.length >= ${plan.perSection},
          nameWithheld: spec.nameWithheld,
        });
      }

      renderPage(req, res, '${plan.moduleDir}/index', {
        title: ${JSON.stringify(plan.title)},
        days,
        daysBack: DAYS_BACK,
        from,
        to,
        sections,
      });
    },
  );
}
`;
}

export function emitView(plan: AttentionPlan): string {
  // Every value goes through `<%= %>`, including the text a person typed into a record's name.
  return `<section class="card">
  <h1><%= title %></h1>
  <form method="get" action="${plan.path}" class="filters">
    <div class="field">
      <label for="days">Days ahead to look</label>
      <input id="days" name="days" type="number" min="1" max="365" value="<%= days %>">
    </div>
    <button type="submit" class="button">Show</button>
  </form>
  <p class="muted">Anything dated between <%= from %> and <%= to %> — the last <%= daysBack %> days and the next <%= days %>. Nothing here says a record is late; it only says when it is.</p>
  <% if (sections.length === 0) { %>
    <p class="muted">Nothing is dated in that stretch of time.</p>
  <% } %>
  <% for (const s of sections) { %>
    <h2><%= s.heading %></h2>
    <% if (s.nameWithheld) { %>
      <p class="muted">Listed by <%= s.dateLabel.toLowerCase() %> only: you marked <%= s.nameWithheld.toLowerCase() %> sensitive, so it is not shown on this page.</p>
    <% } %>
    <table class="table">
      <thead><tr><th><%= s.dateLabel %></th><th></th></tr></thead>
      <tbody>
        <% for (const e of s.entries) { %>
          <tr data-section="<%= s.heading %>" data-at="<%= e.at %>">
            <td><%= e.at %></td>
            <td><a href="<%= e.href %>"><%= e.name || 'Open' %></a></td>
          </tr>
        <% } %>
      </tbody>
    </table>
    <% if (s.more) { %>
      <p class="muted">There may be more. <a href="<%= s.href %>">See all <%= s.heading.toLowerCase() %></a>.</p>
    <% } %>
  <% } %>
</section>
`;
}
