[package]
name = "sv-report"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
sv-check = { path = "../sv-check" }
sv-frameworks = { path = "../sv-frameworks" }
sv-manifest = { path = "../sv-manifest" }
sv-scan = { path = "../sv-scan" }

[dev-dependencies]
serde_json = { workspace = true }
anyhow = { workspace = true }
