/**
 * Static metadata for every `eslint-plugin-security` rule the lint scanner runs (recommended config, minus
 * `detect-object-injection`, which CONTRACTS §3 turns off — it is far too noisy on plain object indexing).
 * Keyed by the short rule name (without the `security/` prefix).
 */
import type { RuleMeta } from '../sast/findings.js';

function meta(id: string, input: Omit<RuleMeta, 'id' | 'remediation' | 'whoCanFix'> & { fix: string; steps?: string[]; references?: string[] }): RuleMeta {
  const { fix, steps, references, ...rest } = input;
  return { id, ...rest, remediation: { summary: fix, steps: steps ?? [], references: references ?? [] } };
}

const REF = ['https://github.com/eslint-community/eslint-plugin-security#rules'];

/** Short eslint-plugin-security rule name → Finding metadata. */
export const LINT_RULE_META: Record<string, RuleMeta> = {
  'detect-buffer-noassert': meta('lint.security/detect-buffer-noassert', {
    title: 'Buffer read/write skips its bounds check',
    severity: 'medium',
    confidence: 'medium',
    cwe: ['CWE-119'],
    asvs: [],
    aisvs: [],
    sbd: [],
    exploitability: 'theoretical',
    description: 'A Buffer method is called with noAssert set to true, which skips the offset bounds check.',
    impact: 'A miscalculated offset can read or write outside the buffer instead of throwing, which is hard to notice and can corrupt memory.',
    fix: 'Remove the noAssert argument (or set it to false) so out-of-range offsets throw instead of corrupting memory.',
    references: REF,
  }),
  'detect-child-process': meta('lint.security/detect-child-process', {
    title: 'A shell command is built from a variable',
    severity: 'high',
    confidence: 'medium',
    cwe: ['CWE-78'],
    asvs: ['V1.2.5'],
    aisvs: [],
    sbd: [],
    exploitability: 'trivial',
    description: 'child_process.exec/execSync (or similar) is called with an argument that is not a fixed string.',
    impact: 'If any part of that value comes from a user, they can run arbitrary commands on the server.',
    fix: 'Use execFile/spawn with an argument array instead of a shell string, or remove the child process call.',
    references: REF,
  }),
  'detect-disable-mustache-escape': meta('lint.security/detect-disable-mustache-escape', {
    title: 'Template auto-escaping is turned off',
    severity: 'high',
    confidence: 'high',
    cwe: ['CWE-79'],
    asvs: ['V1.1.2'],
    aisvs: [],
    sbd: [],
    exploitability: 'requires-auth',
    description: 'A templating engine\'s automatic output escaping is disabled.',
    impact: 'Text that reaches the page unescaped can run as script in another person\'s browser (cross-site scripting).',
    fix: 'Keep escaping on; use an explicit, reviewed helper only for the few values that must render as HTML.',
    references: REF,
  }),
  'detect-eval-with-expression': meta('lint.security/detect-eval-with-expression', {
    title: 'eval() is called with a non-literal argument',
    severity: 'high',
    confidence: 'high',
    cwe: ['CWE-95'],
    asvs: ['V1.3.2'],
    aisvs: [],
    sbd: [],
    exploitability: 'trivial',
    description: 'eval() (or an equivalent) runs a string that is not a fixed piece of code.',
    impact: 'If any part of that string comes from outside the program, it can run arbitrary code.',
    fix: 'Remove the eval() call and use a plain function, JSON.parse, or a small allow-listed switch instead.',
    references: REF,
  }),
  'detect-new-buffer': meta('lint.security/detect-new-buffer', {
    title: 'Buffer is allocated with the legacy new Buffer() call',
    severity: 'medium',
    confidence: 'medium',
    cwe: ['CWE-908'],
    asvs: [],
    aisvs: [],
    sbd: [],
    exploitability: 'theoretical',
    description: 'new Buffer(...) is used instead of Buffer.alloc()/Buffer.from().',
    impact: 'The legacy constructor can return uninitialised memory, which may leak whatever was previously in it.',
    fix: 'Use Buffer.alloc(size) (zero-filled) or Buffer.from(data) instead of new Buffer(...).',
    references: REF,
  }),
  'detect-no-csrf-before-method-override': meta('lint.security/detect-no-csrf-before-method-override', {
    title: 'CSRF protection is registered before method-override',
    severity: 'medium',
    confidence: 'medium',
    cwe: ['CWE-352'],
    asvs: ['V3.3.2'],
    aisvs: [],
    sbd: [],
    exploitability: 'requires-network-exposure',
    description: 'A CSRF-protection middleware is set up before the method-override middleware in the same file.',
    impact: 'method-override can turn a GET into a POST/PUT/DELETE after the CSRF check already ran, letting a request bypass it.',
    fix: 'Register method-override before the CSRF middleware (the template does not use method-override at all).',
    references: REF,
  }),
  'detect-non-literal-fs-filename': meta('lint.security/detect-non-literal-fs-filename', {
    title: 'A file system path is built from a variable',
    severity: 'high',
    confidence: 'medium',
    cwe: ['CWE-22'],
    asvs: ['V5.3.2'],
    aisvs: [],
    sbd: [],
    exploitability: 'requires-auth',
    description: 'A node:fs call receives a path that is not a fixed string.',
    impact: 'If part of that path comes from a user, they can read or write files outside the intended folder (path traversal).',
    fix: 'Build the path with a safe join helper, resolve it, and confirm it stays inside the intended directory before use.',
    references: REF,
  }),
  'detect-non-literal-regexp': meta('lint.security/detect-non-literal-regexp', {
    title: 'A regular expression is built from a variable',
    severity: 'medium',
    confidence: 'medium',
    cwe: ['CWE-1333'],
    asvs: ['V1.2.9'],
    aisvs: [],
    sbd: [],
    exploitability: 'requires-network-exposure',
    description: 'new RegExp(...) is called with an argument that is not a fixed string.',
    impact: 'A crafted pattern from outside the program can make matching take an extremely long time (denial of service) or match unintended text.',
    fix: 'Use a fixed pattern, or escape the dynamic part and cap its length before building the expression.',
    references: REF,
  }),
  'detect-non-literal-require': meta('lint.security/detect-non-literal-require', {
    title: 'require() is called with a non-literal argument',
    severity: 'medium',
    confidence: 'medium',
    cwe: ['CWE-829'],
    asvs: ['V1.5.2'],
    aisvs: [],
    sbd: [],
    exploitability: 'theoretical',
    description: 'require(...) (or a dynamic import) is called with a module path that is not a fixed string.',
    impact: 'If that value can be influenced from outside the program, arbitrary code on disk could be loaded and run.',
    fix: 'Use a fixed import path, or resolve the name against a small allow-list before loading it.',
    references: REF,
  }),
  'detect-object-injection': meta('lint.security/detect-object-injection', {
    title: 'A variable is used as an object property key',
    severity: 'medium',
    confidence: 'low',
    cwe: ['CWE-915'],
    asvs: [],
    aisvs: [],
    sbd: [],
    exploitability: 'theoretical',
    description: 'An object or array is indexed with a variable instead of a fixed key.',
    impact: 'If the key comes from outside the program it can, in rare cases, reach properties like __proto__ and modify behaviour app-wide.',
    fix: 'Validate the key against an allow-list, or use a Map instead of a plain object for dynamic keys.',
    references: REF,
  }),
  'detect-possible-timing-attacks': meta('lint.security/detect-possible-timing-attacks', {
    title: 'A secret is compared with the == or === operator',
    severity: 'medium',
    confidence: 'medium',
    cwe: ['CWE-208'],
    asvs: ['V11.2.4'],
    aisvs: [],
    sbd: [],
    exploitability: 'theoretical',
    description: 'A value with a name like password, token or secret is compared with ==/=== instead of a constant-time comparison.',
    impact: 'The comparison can return slightly faster on a wrong guess, which — measured many times — can let an attacker guess the value character by character.',
    fix: 'Compare secrets with crypto.timingSafeEqual (the template\'s security/password.ts and csrf.ts already do this).',
    references: REF,
  }),
  'detect-pseudoRandomBytes': meta('lint.security/detect-pseudoRandomBytes', {
    title: 'A weak random number generator is used',
    severity: 'high',
    confidence: 'high',
    cwe: ['CWE-338'],
    asvs: ['V11.5.1'],
    aisvs: [],
    sbd: [],
    exploitability: 'theoretical',
    description: 'Math.random() or crypto.pseudoRandomBytes() is used somewhere a value needs to be unguessable.',
    impact: 'These generators are predictable; an attacker who can observe enough output can predict tokens, ids or codes generated this way.',
    fix: 'Use crypto.randomBytes() / crypto.randomUUID() for anything that must not be guessable.',
    references: REF,
  }),
  'detect-unsafe-regex': meta('lint.security/detect-unsafe-regex', {
    title: 'A regular expression can take exponential time to match',
    severity: 'medium',
    confidence: 'medium',
    cwe: ['CWE-1333'],
    asvs: ['V1.3.12'],
    aisvs: [],
    sbd: [],
    exploitability: 'requires-network-exposure',
    description: 'The pattern has nested repetition (e.g. (a+)+) that can force catastrophic backtracking on certain input.',
    impact: 'A short, crafted input can make this pattern take seconds or minutes to match, freezing the server (denial of service).',
    fix: 'Rewrite the pattern without nested quantifiers, or validate the input length before matching.',
    references: REF,
  }),
  'detect-bidi-characters': meta('lint.security/detect-bidi-characters', {
    title: 'Hidden bidirectional text characters found',
    severity: 'medium',
    confidence: 'high',
    cwe: ['CWE-451'],
    asvs: [],
    aisvs: [],
    sbd: [],
    exploitability: 'theoretical',
    description: 'The file contains Unicode bidirectional-override characters, which can make code display in an order different from how it runs.',
    impact: 'Source that looks safe to a reviewer can actually do something else (the "Trojan Source" technique).',
    fix: 'Remove the bidirectional control characters; they have no legitimate use in source code.',
    references: ['https://trojansource.codes/', ...REF],
  }),
};
