/**
 * Renders the design artifacts to the Markdown files written under workspace/projects/<id>/design/ at design freeze
 * (CONTRACTS §9.6): design.md, security-contract.md, threat-model.md, diagram.mmd and one file per ADR.
 */
import type { Adr, DesignArtifacts, SbdChecklistEntry, Threat } from '@shared/design.js';
import type { DesignProfile } from '@shared/profile.js';
import { ADR_FILES } from './adrs.js';
import { DATA_CATEGORY_LABELS, audiencePhrase, deploymentPhrase, listWords } from './conditions.js';

export interface RenderedDesign {
  'design.md': string;
  'security-contract.md': string;
  'threat-model.md': string;
  'diagram.mmd': string;
  /** File name (e.g. ADR-001-authentication-model.md) → Markdown. */
  adrs: Record<string, string>;
}

function cell(text: string | number | boolean | undefined): string {
  if (text === undefined) return '';
  return String(text).replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function table(headers: string[], rows: (string | number | boolean | undefined)[][]): string {
  const lines = [`| ${headers.map(cell).join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`];
  for (const row of rows) lines.push(`| ${row.map(cell).join(' | ')} |`);
  return lines.join('\n');
}

function bullets(items: string[], empty = '_none_'): string {
  return items.length ? items.map((i) => `- ${i}`).join('\n') : empty;
}

function checklistStatus(entry: SbdChecklistEntry): string {
  return { yes: 'Yes', no: 'No', 'n-a': 'N-A' }[entry.status];
}

function dataLabel(item: string): string {
  return (DATA_CATEGORY_LABELS as Record<string, string>)[item] ?? item;
}

/** "owner:Sam Rivera" → "Sam Rivera (owner)"; "hosting-provider" → "the hosting provider". */
function ownerLabel(owner: string): string {
  if (owner.startsWith('owner:')) return `${owner.slice('owner:'.length)} (owner)`;
  if (owner === 'developer') return 'a developer';
  if (owner === 'hosting-provider') return 'the hosting provider';
  return owner;
}

export function renderDesignMarkdown(design: DesignArtifacts, profile: DesignProfile): RenderedDesign {
  const adrs: Record<string, string> = {};
  for (const adr of design.adrs) adrs[ADR_FILES[adr.id] ?? `${adr.id}.md`] = renderAdr(adr);
  return {
    'design.md': renderDesignDoc(design, profile),
    'security-contract.md': renderContract(design),
    'threat-model.md': renderThreatModel(design),
    'diagram.mmd': design.architecture.mermaid.endsWith('\n') ? design.architecture.mermaid : `${design.architecture.mermaid}\n`,
    adrs,
  };
}

function renderDesignDoc(design: DesignArtifacts, profile: DesignProfile): string {
  const arch = design.architecture;
  const name = profile.app.name;
  const sections: string[] = [];

  sections.push(
    [
      `# ${name} — design document`,
      '',
      `Generated by SecureVibe on ${design.generatedAt.slice(0, 10)} from the design profile (hash \`${design.profileHash.slice(0, 12)}\`), following the OWASP Secure by Design Framework v0.5. This document is derived by rules from the answers given in the wizard; it is not a certification.`,
      '',
      `- Used by: ${audiencePhrase(profile)}`,
      `- Runs: ${deploymentPhrase(profile)}`,
      `- Security contact: ${profile.deployment.owner.name} (${profile.deployment.owner.contactEmail})`,
      `- Target verification level: ${design.applicability.targetLevel} — ${design.applicability.targetLevelRule}`,
      `- Care level: ${design.riskTriage.extraCareLabel}`,
    ].join('\n'),
  );

  sections.push(['## What we will build', '', design.plainLanguageSummary, '', '### What this means for you', '', bullets(design.consequences)].join('\n'));

  if (design.assumptionsMade.length) {
    sections.push(['## Assumptions we made for you', '', bullets(design.assumptionsMade)].join('\n'));
  }

  sections.push(
    [
      '## 1. Security requirements (SbD step 1)',
      '',
      table(
        ['Id', 'Requirement', 'Category', 'Driven by', 'ASVS', 'AISVS', 'SbD'],
        design.securityRequirements.map((r) => [r.id, r.statement, r.category, r.drivenBy.join(', '), r.asvs.join(', '), r.aisvs.join(', '), r.sbd.join(', ')]),
      ),
    ].join('\n'),
  );

  sections.push(
    [
      '## 2. Architecture (SbD step 2)',
      '',
      arch.plainLanguage,
      '',
      '### Trust zones',
      '',
      table(['Zone', 'Trust', 'Description'], arch.trustZones.map((z) => [`${z.name} (\`${z.id}\`)`, z.level, z.description])),
      '',
      '### Components',
      '',
      table(['Id', 'Name', 'Kind', 'Zone', 'Description'], arch.components.map((c) => [c.id, c.name, c.kind, c.trustZone, c.description])),
      '',
      '### Data flows',
      '',
      table(
        ['Id', 'From → To', 'Protocol', 'Data', 'Crosses boundary', 'Controls', 'Description'],
        arch.dataFlows.map((fl) => [fl.id, `${fl.from} → ${fl.to}`, fl.protocol, fl.data.map(dataLabel).join(', '), fl.crossesTrustBoundary ? 'yes' : 'no', fl.controls.join(', '), fl.description]),
      ),
      '',
      '### Outside dependencies',
      '',
      table(
        ['Name', 'Purpose', 'Trust', 'Data shared', 'Mitigations'],
        arch.externalDependencies.map((d) => [d.name, d.purpose, d.trust, d.dataShared.join(', ') || 'none', d.mitigations.join('; ')]),
      ),
      '',
      '### Assumptions',
      '',
      bullets(arch.assumptions),
      '',
      '### Diagram',
      '',
      '```mermaid',
      arch.mermaid,
      '```',
    ].join('\n'),
  );

  sections.push(
    [
      '## 3. Patterns applied (SbD step 3)',
      '',
      table(
        ['Pattern', 'Principle', 'Domain', 'Why', 'Implemented by', 'Checklist'],
        design.patterns.map((p) => [`${p.name} (\`${p.id}\`)`, p.principle, p.sbdDomain, p.why, p.implementedBy.join(', '), p.sbdChecklist.join(', ')]),
      ),
    ].join('\n'),
  );

  const yes = design.checklist.filter((e) => e.status === 'yes').length;
  const no = design.checklist.filter((e) => e.status === 'no').length;
  const na = design.checklist.filter((e) => e.status === 'n-a').length;
  sections.push(
    [
      '## 4. SbD review checklist (SbD step 4)',
      '',
      `Yes: ${yes} · No: ${no} · N-A: ${na} · Score: ${design.riskTriage.score} (threshold ${design.riskTriage.threshold}) · Critical "No": ${design.riskTriage.criticalNo.join(', ') || 'none'}`,
      '',
      table(
        ['Id', 'Control', 'Critical', 'Status', 'Severity if No', 'Justification', 'Evidence', 'Actions', 'ADRs'],
        design.checklist.map((e) => [
          e.id,
          e.statement,
          e.critical ? 'yes' : '',
          checklistStatus(e),
          e.severityIfNo,
          e.justification,
          e.evidence.join(', '),
          e.actions.map((a) => `${a.text} (${ownerLabel(a.owner)}${a.dueBy ? `, ${a.dueBy}` : ''})`).join('; '),
          e.adrIds.join(', '),
        ]),
      ),
      '',
      '### Mitigation plans for critical controls answered "No"',
      '',
      bullets(
        design.checklist
          .filter((e) => e.mitigationPlan)
          .map((e) => `${e.id}: ${e.mitigationPlan?.action} — responsible: ${ownerLabel(e.mitigationPlan?.owner ?? '')}, due ${e.mitigationPlan?.dueBy}`),
      ),
      '',
      '### What changes when the app is deployed',
      '',
      bullets(design.checklist.filter((e) => e.deploymentNote).map((e) => `${e.id}: ${e.deploymentNote}`)),
    ].join('\n'),
  );

  const peer = design.peerReview;
  sections.push(
    [
      '## 5. Second opinion (SbD step 5)',
      '',
      peer
        ? `Performed by: ${peer.performedBy}${peer.model ? ` (${peer.model})` : ''} on ${peer.performedAt.slice(0, 10)}. ${peer.summary}${peer.skippedReason ? ` Skipped: ${peer.skippedReason}` : ''}`
        : 'Not performed yet (or skipped in preview mode). The report states this plainly.',
      '',
      ...(peer?.suggestions.length
        ? [
            '',
            table(
              ['Id', 'Kind', 'Severity', 'Title', 'Decision'],
              peer.suggestions.map((s) => [s.id, s.kind, s.severity, s.title, s.accepted === null ? 'pending' : s.accepted ? (s.applied ? 'accepted and applied' : 'accepted') : `dismissed${s.dismissReason ? `: ${s.dismissReason}` : ''}`]),
            ),
          ]
        : []),
    ].join('\n'),
  );

  const triage = design.riskTriage;
  sections.push(
    [
      '## 6. Risk triage (SbD step 6)',
      '',
      `**${triage.extraCareLabel}.** ${triage.plainLanguage}`,
      '',
      table(['Trigger', 'Applies', 'Reason'], triage.triggers.map((t) => [t.name, t.triggered ? 'yes' : 'no', t.reason])),
      '',
      `Level: ${triage.level}. Escalation: ${triage.escalate ? 'required' : 'not required'}. ${triage.escalationHandling}`,
      '',
      bullets(triage.escalationReasons),
    ].join('\n'),
  );

  sections.push(
    [
      '## 7. Threat model (SbD step 7)',
      '',
      design.threatModel ? `${design.threatModel.summary} See threat-model.md for the full register.` : 'No threat model was generated.',
    ].join('\n'),
  );

  sections.push(
    [
      '## 8. Decisions (ADRs)',
      '',
      table(['Id', 'Title', 'Date', 'File'], design.adrs.map((a) => [a.id, a.title, a.date, `adr/${ADR_FILES[a.id] ?? `${a.id}.md`}`])),
    ].join('\n'),
  );

  const asvs = design.applicability.asvs;
  const aisvs = design.applicability.aisvs;
  const appendixC = design.applicability.appendixC;
  sections.push(
    [
      '## 9. What will be verified after the build',
      '',
      `- ASVS 5.0.0 at level ${design.applicability.targetLevel}: ${asvs.applicable.length} applicable requirements, ${asvs.notApplicable.length} not applicable, ${asvs.outOfLevel.length} out of level.`,
      `- AISVS 1.0: ${aisvs.enabled ? `${aisvs.applicable.length} applicable requirements, ${aisvs.notApplicable.length} not applicable, ${aisvs.outOfLevel.length} out of level.` : 'not evaluated.'} ${aisvs.reason}`,
      `- AISVS Appendix C (the build process): ${appendixC.applicable.length} applicable, ${appendixC.notApplicable.length} not applicable.`,
      `- Security contract: ${design.securityContract.rules.length} rules (security-contract.md).`,
    ].join('\n'),
  );

  const feats = design.buildSpec.features;
  sections.push(
    [
      '## 10. Build settings',
      '',
      `Package name: \`${design.buildSpec.packageName}\`. Sessions: ${design.buildSpec.sessionPolicy.idleMinutes} min idle, ${design.buildSpec.sessionPolicy.absoluteHours} h absolute, ${design.buildSpec.sessionPolicy.maxConcurrent} concurrent.`,
      '',
      table(
        ['Feature', 'On'],
        Object.entries(feats).map(([k, v]) => [k, String(v)]),
      ),
    ].join('\n'),
  );

  return sections.join('\n\n') + '\n';
}

function renderContract(design: DesignArtifacts): string {
  const c = design.securityContract;
  const lines = [
    `# Security contract (version ${c.version})`,
    '',
    'These are the rules the code generator must obey. Every rule is checked after generation by the tools named under "Enforced by"; a broken rule appears as a finding in the security report.',
    '',
  ];
  for (const r of c.rules) {
    lines.push(`## ${r.id}`, '', r.rule, '', `_Why:_ ${r.rationale}`, '');
    const maps: string[] = [];
    if (r.asvs.length) maps.push(`ASVS ${r.asvs.join(', ')}`);
    if (r.aisvs.length) maps.push(`AISVS ${r.aisvs.join(', ')}`);
    lines.push(`_Verifies:_ ${maps.join('; ') || 'template convention'}. _Enforced by:_ ${r.enforcedBy.join(', ') || 'review'}.`, '');
  }
  return lines.join('\n');
}

function threatRow(t: Threat): (string | undefined)[] {
  return [t.id, t.stride, t.target, t.riskLevel, t.likelihood, t.impact, t.residualRisk, t.status, t.description];
}

function renderThreatModel(design: DesignArtifacts): string {
  const tm = design.threatModel;
  if (!tm) return '# Threat model\n\nNo threat model was generated for this design.\n';
  const lines = [
    `# Threat model (${tm.method})`,
    '',
    `Performed by: ${tm.performedBy}${tm.model ? ` (${tm.model})` : ''} on ${tm.performedAt.slice(0, 10)}.`,
    '',
    tm.summary,
    '',
    '## Scope',
    '',
    tm.scope,
    '',
    '## Assets',
    '',
    bullets(tm.assets),
    '',
    '## Entry points',
    '',
    bullets(tm.entryPoints),
    '',
    '## Trust boundaries',
    '',
    bullets(tm.trustBoundaries),
    '',
    '## Risk register (highest risk first)',
    '',
    table(['Id', 'STRIDE', 'Target', 'Risk', 'Likelihood', 'Impact', 'Residual', 'Status', 'Threat'], tm.threats.map(threatRow)),
    '',
    '## Threats in detail',
    '',
  ];
  for (const t of tm.threats) {
    lines.push(`### ${t.id} — ${t.description}`, '');
    lines.push(`STRIDE: ${t.stride}. Target: ${t.target}. Risk: ${t.riskLevel} (likelihood ${t.likelihood}, impact ${t.impact}); residual ${t.residualRisk}; status ${t.status}.`, '');
    lines.push('Mitigations:', '');
    lines.push(bullets(t.mitigations.map((m) => `${m.control}: ${m.description}${m.requirementIds.length ? ` (${m.requirementIds.join(', ')})` : ''}`)), '');
    if (t.actionItems.length) lines.push('Actions before use:', '', bullets(t.actionItems), '');
  }
  const open = tm.threats.filter((t) => t.status !== 'mitigated');
  lines.push('## Action items', '', bullets(open.flatMap((t) => t.actionItems.map((a) => `${t.id}: ${a}`)), '_none — every threat is covered by built-in protections_'), '');
  return lines.join('\n');
}

function renderAdr(adr: Adr): string {
  return [
    `# ${adr.id}: ${adr.title}`,
    '',
    `Status: ${adr.status} · Date: ${adr.date}`,
    '',
    '## Context',
    '',
    adr.context,
    '',
    '## Decision',
    '',
    adr.decision,
    '',
    '## Alternatives considered',
    '',
    bullets(adr.alternatives),
    '',
    '## Consequences',
    '',
    adr.consequences,
    '',
    `Related controls: ${listWords(adr.relatedControls) || 'none'}. Related requirements: ${listWords(adr.relatedRequirements) || 'none'}.`,
    '',
  ].join('\n');
}
