/**
 * Code emitters for the CRUD expander. Every string produced here must be erasable TypeScript with explicit
 * ".ts" import extensions, and must follow the conventions of `src/features/_example` (route registry, strict
 * zod schemas, DTOs, transactions, optimistic concurrency, per-user quota).
 */
import type { EntityPlan, FieldPlan } from './fields.js';

const HEADER = (runId: string) => `// Generated by SecureVibe (expanded from your answers) — run ${runId}\n`;

function sqlColumn(f: FieldPlan): string {
  const nullable = f.field.required && !f.encrypted ? ' NOT NULL' : '';
  return `  ${f.column} ${f.sqlType}${nullable}`;
}

export function emitMigration(plan: EntityPlan, runId: string): string {
  const columns = plan.fields.map(sqlColumn).join(',\n');
  const indexes = [`CREATE INDEX IF NOT EXISTS idx_${plan.table}_owner ON ${plan.table}(owner_id);`, `CREATE INDEX IF NOT EXISTS idx_${plan.table}_updated ON ${plan.table}(updated_at);`];
  return `-- Generated by SecureVibe (expanded from your answers) — run ${runId}
-- ${plan.entity.label}${plan.entity.description ? `: ${plan.entity.description}` : ''}
CREATE TABLE IF NOT EXISTS ${plan.table} (
  id TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
${columns}${columns ? ',' : ''}
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
${indexes.join('\n')}
`;
}

export function emitSchema(plan: EntityPlan, runId: string): string {
  const create = plan.fields.map((f) => `  ${f.prop}: ${f.zod},`).join('\n');
  const patch = plan.fields.map((f) => `  ${f.prop}: ${f.zodOptional},`).join('\n');
  return `${HEADER(runId)}/**
 * Validation rules for ${plan.entity.label}. Every schema is strict: unknown fields are rejected, so a form or
 * API call cannot set a column that was not meant to be writable (mass assignment).
 */
import { z } from 'zod';
import { schemas } from '../../security/validate.ts';

export const ${plan.pascalName}Params = z.strictObject({ id: schemas.id });
export const ${plan.pascalName}ListQuery = z.strictObject({ page: schemas.page, limit: schemas.limit });

export const ${plan.pascalName}Body = z.strictObject({
${create}
});

/** Page updates send the whole form plus the updatedAt the browser last saw (optimistic concurrency). */
export const ${plan.pascalName}UpdateBody = ${plan.pascalName}Body.extend({ updatedAt: schemas.isoDate });

/** API updates may send only the fields that change, plus updatedAt. */
export const ${plan.pascalName}PatchBody = z.strictObject({
${patch}
  updatedAt: schemas.isoDate,
});

export type ${plan.pascalName}Input = z.infer<typeof ${plan.pascalName}Body>;
`;
}

export function emitRepo(plan: EntityPlan, runId: string): string {
  const rowFields = plan.fields.map((f) => `  ${f.column}: ${f.sqlType === 'TEXT' ? 'string | null' : 'number | null'};`).join('\n');
  const insertColumns = ['id', 'owner_id', ...plan.fields.map((f) => f.column), 'created_at', 'updated_at'];
  const insertPlaceholders = insertColumns.map(() => '?').join(', ');
  const insertValues = ['id', 'ownerId', ...plan.fields.map((f) => f.toDb(`input.${f.prop}`)), 'now', 'now'].join(', ');
  const updateAssignments = plan.fields.map((f) => `${f.column} = ?`).concat('updated_at = ?').join(', ');
  const updateValues = plan.fields.map((f) => f.toDb(`merged.${f.prop}`)).concat('now', 'id', 'expectedUpdatedAt').join(', ');
  const mergeLines = plan.fields.map((f) => `    ${f.prop}: input.${f.prop} ?? current${plan.pascalName}Value(existing, ${JSON.stringify(f.prop)}),`).join('\n');
  const dtoLines = plan.fields.map((f) => `    ${f.prop}: ${f.fromDb(`row.${f.column}`)},`).join('\n');
  const sensitiveList = plan.fields.filter((f) => f.encrypted).map((f) => JSON.stringify(f.column)).join(', ');
  const publicDtoLines = plan.fields
    .filter((f) => !f.field.sensitive)
    .map((f) => `    ${f.prop}: ${f.fromDb(`row.${f.column}`)},`)
    .join('\n');
  const seedValues = plan.fields
    .map((f) => {
      switch (f.control) {
        case 'number':
        case 'money':
          return `    ${f.prop}: 1,`;
        case 'checkbox':
          return `    ${f.prop}: false,`;
        case 'date':
          return `    ${f.prop}: '2026-01-01',`;
        case 'datetime-local':
          return `    ${f.prop}: '2026-01-01T09:00',`;
        case 'email':
          return `    ${f.prop}: 'sample@example.com',`;
        case 'url':
          return `    ${f.prop}: 'https://example.com',`;
        case 'select':
          return `    ${f.prop}: ${JSON.stringify((f.field.choices ?? [''])[0] ?? '')},`;
        default:
          return `    ${f.prop}: 'Sample ${plan.entity.label.toLowerCase()}',`;
      }
    })
    .join('\n');

  const cryptoImport = plan.hasEncrypted ? `import { decryptField, encryptField, registerEncryptedColumn } from '../../db/field-crypto.ts';\n` : '';
  const decryptHelper = plan.hasEncrypted
    ? `
/** Decrypts a stored value, returning '' if it cannot be read (a rotated-away key, for example). */
function decryptOrEmpty(stored: string | null, column: string, rowId: string): string {
  if (stored === null || stored === '') return '';
  try {
    return decryptField(stored, TABLE, column, rowId);
  } catch {
    return '';
  }
}
`
    : '';
  const registerEncrypted = plan.hasEncrypted
    ? plan.fields
        .filter((f) => f.encrypted)
        .map((f) => `  registerEncryptedColumn({ table: TABLE, column: ${JSON.stringify(f.column)}, idColumn: 'id' });`)
        .join('\n')
    : '';

  return `${HEADER(runId)}/**
 * Data access for ${plan.entity.label}. Mirrors src/features/_example/repo.ts: parameterised queries only,
 * LIMIT on every list, a per-user quota enforced inside a transaction, optimistic concurrency on update, and
 * DTOs (never raw rows) returned to pages and the API.
 */
import { randomUUID } from 'node:crypto';
import { all, get, nowIso, run, withTransaction } from '../../db/index.ts';
${cryptoImport}import { registerEntity } from '../../security/authz.ts';
import type { ${plan.pascalName}Input } from './schema.ts';

export const TABLE = '${plan.table}';
export const ${plan.camelName.toUpperCase()}_QUOTA_PER_USER = ${plan.quota};

export interface ${plan.rowType} {
  id: string;
  owner_id: string;
${rowFields}
  created_at: string;
  updated_at: string;
}
${decryptHelper}
export function get${plan.pascalName}(id: string): ${plan.rowType} | undefined {
  return get<${plan.rowType}>(\`SELECT * FROM \${TABLE} WHERE id = ?\`, [id]);
}

export function list${plan.pascalName}ForOwner(ownerId: string, limit: number, offset: number): ${plan.rowType}[] {
  return all<${plan.rowType}>(\`SELECT * FROM \${TABLE} WHERE owner_id = ? ORDER BY updated_at DESC LIMIT ? OFFSET ?\`, [ownerId, limit, offset]);
}

export function listAll${plan.pascalName}(limit: number, offset: number): ${plan.rowType}[] {
  return all<${plan.rowType}>(\`SELECT * FROM \${TABLE} ORDER BY updated_at DESC LIMIT ? OFFSET ?\`, [limit, offset]);
}

export function count${plan.pascalName}ForOwner(ownerId: string): number {
  return get<{ n: number }>(\`SELECT COUNT(*) AS n FROM \${TABLE} WHERE owner_id = ?\`, [ownerId])?.n ?? 0;
}

/** The DTO value currently stored for one property (used when a PATCH omits a field). */
function current${plan.pascalName}Value(row: ${plan.rowType}, prop: string): unknown {
  return (toOwnerDto(row) as Record<string, unknown>)[prop];
}

export type CreateResult = { ok: true; record: ${plan.rowType} } | { ok: false; reason: 'quota' };

/** The quota check and the insert share one transaction, so parallel requests cannot both slip under the limit. */
export function create${plan.pascalName}(ownerId: string, input: ${plan.pascalName}Input): CreateResult {
  return withTransaction<CreateResult>(() => {
    if (count${plan.pascalName}ForOwner(ownerId) >= ${plan.camelName.toUpperCase()}_QUOTA_PER_USER) return { ok: false, reason: 'quota' };
    const id = randomUUID();
    const now = nowIso();
    run(\`INSERT INTO \${TABLE} (${insertColumns.join(', ')}) VALUES (${insertPlaceholders})\`, [${insertValues}]);
    const record = get${plan.pascalName}(id);
    if (!record) throw new Error('The record was not created.');
    return { ok: true, record };
  });
}

export type UpdateResult = { ok: true; record: ${plan.rowType} } | { ok: false; reason: 'conflict' | 'not-found' };

/** Optimistic concurrency: the row changes only while its updated_at still matches what the caller last saw. */
export function update${plan.pascalName}(id: string, input: Partial<${plan.pascalName}Input>, expectedUpdatedAt: string): UpdateResult {
  return withTransaction<UpdateResult>(() => {
    const existing = get${plan.pascalName}(id);
    if (!existing) return { ok: false, reason: 'not-found' };
    if (existing.updated_at !== expectedUpdatedAt) return { ok: false, reason: 'conflict' };
    const merged = {
${mergeLines}
    } as ${plan.pascalName}Input;
    const now = nowIso();
    const result = run(\`UPDATE \${TABLE} SET ${updateAssignments} WHERE id = ? AND updated_at = ?\`, [${updateValues}]);
    if (result.changes !== 1) return { ok: false, reason: 'conflict' };
    const record = get${plan.pascalName}(id);
    if (!record) return { ok: false, reason: 'not-found' };
    return { ok: true, record };
  });
}

export function delete${plan.pascalName}(id: string): boolean {
  return run(\`DELETE FROM \${TABLE} WHERE id = ?\`, [id]).changes === 1;
}

/** Seen by the owner (and, with the owner id added, by administrators). */
export function toOwnerDto(row: ${plan.rowType}) {
  return {
    id: row.id,
${dtoLines}
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

/** Seen by other signed-in people: sensitive fields are left out. */
export function toPublicDto(row: ${plan.rowType}) {
  return {
    id: row.id,
${publicDtoLines}
    updatedAt: row.updated_at,
  };
}

export function toAdminDto(row: ${plan.rowType}): ReturnType<typeof toOwnerDto> & { ownerId: string } {
  return { ...toOwnerDto(row), ownerId: row.owner_id };
}

export function register${plan.pascalName}Entity(): void {
${registerEncrypted}${registerEncrypted ? '\n' : ''}  registerEntity({
    name: '${plan.entity.name}',
    table: TABLE,
    ownerField: 'owner_id',
    label: ${JSON.stringify(plan.entity.label)},
    sensitiveFields: [${sensitiveList}],
    seed: (ownerId) => {
      create${plan.pascalName}(ownerId, {
${seedValues}
      } as ${plan.pascalName}Input);
    },
    sampleId: (ownerId) => get<{ id: string }>(\`SELECT id FROM \${TABLE} WHERE owner_id = ? ORDER BY created_at ASC LIMIT 1\`, [ownerId])?.id,
    exportForUser: (userId) => list${plan.pascalName}ForOwner(userId, 1000, 0).map(toOwnerDto),
    deleteForUser: (userId) => {
      run(\`DELETE FROM \${TABLE} WHERE owner_id = ?\`, [userId]);
    },
  });
}
`;
}

export function emitRoutes(plan: EntityPlan, runId: string): string {
  const owner = plan.ownerScoped ? `owner: OWNER, ` : '';
  const formValues = plan.fields.map((f) => `      ${f.prop}: values?.${f.prop} ?? ${f.control === 'checkbox' ? 'false' : "''"},`).join('\n');
  const label = plan.entity.label;
  const lower = label.toLowerCase();
  const aLabel = `${/^[aeiou]/.test(lower) ? 'an' : 'a'} ${lower}`;
  // Summaries are emitted as JSON strings so a label with a quote cannot break the generated code.
  const say = (text: string) => JSON.stringify(text);
  const listTitle = plan.entity.pluralLabel ?? `${label}s`;

  return `${HEADER(runId)}/**
 * ${label} pages and JSON API. Every route is registered through defineRoute with an explicit \`auth\` value,
 * strict schemas and (where records belong to one person) an ownership check, exactly as
 * src/features/_example demonstrates.
 */
import type { Request, Response, Router } from 'express';
import { clampLimit } from '../../db/index.ts';
import { errors } from '../../lib/errors.ts';
import { renderPage } from '../../lib/views.ts';
import { defineRoute } from '../../security/routes.ts';
import type { FieldErrors } from '../../security/validate.ts';
import { ${plan.pascalName}Body, ${plan.pascalName}ListQuery, ${plan.pascalName}Params, ${plan.pascalName}PatchBody, ${plan.pascalName}UpdateBody } from './schema.ts';
import {
  ${plan.camelName.toUpperCase()}_QUOTA_PER_USER,
  create${plan.pascalName},
  delete${plan.pascalName},${plan.ownerScoped ? '' : `
  get${plan.pascalName},`}
  listAll${plan.pascalName},
  list${plan.pascalName}ForOwner,
  register${plan.pascalName}Entity,
  toAdminDto,
  toOwnerDto,
  toPublicDto,
  update${plan.pascalName},
  type ${plan.rowType},
} from './repo.ts';

const OWNER = { entity: '${plan.entity.name}', param: 'id' } as const;

${
  plan.ownerScoped
    ? `function recordFromRequest(req: Request): ${plan.rowType} {
  // The route's ownership check (owner: OWNER) already loaded the record and confirmed it belongs to this user.
  const row = req.entity as unknown as ${plan.rowType} | undefined;
  if (!row) throw errors.notFound();
  return row;
}`
    : `function recordFromRequest(req: Request): ${plan.rowType} {
  // Shared records: any signed-in user may read them, so the record is looked up by the validated id here.
  const row = get${plan.pascalName}((req.valid.params as { id: string }).id);
  if (!row) throw errors.notFound();
  return row;
}`
}

function dtoFor(req: Request, row: ${plan.rowType}) {
  if (req.user?.isAdmin) return toAdminDto(row);
${
  plan.ownerScoped
    ? `  // Only the owner can reach an owner-only record (the route checks it), so the owner view applies.
  return toOwnerDto(row);`
    : `  if (req.user?.id === row.owner_id) return toOwnerDto(row);
  return toPublicDto(row);`
}
}

function renderForm(req: Request, res: Response, fields: FieldErrors, status = 400): void {
  const body = (req.body ?? {}) as Record<string, unknown>;
  const values = body as Record<string, never>;
  renderPage(
    req,
    res,
    '${plan.moduleDir}/form',
    {
      title: ${JSON.stringify(label)},
      errors: fields,
      values: {
${formValues}
      },
      record: req.entity ? toOwnerDto(req.entity as unknown as ${plan.rowType}) : null,
      quota: ${plan.camelName.toUpperCase()}_QUOTA_PER_USER,
    },
    status,
  );
}

export function register(router: Router): void {
  register${plan.pascalName}Entity();

  // ---------- Pages ----------
  defineRoute(router, { method: 'GET', path: '${plan.base}', auth: ${plan.readAuth}, entity: '${plan.entity.name}', schema: { query: ${plan.pascalName}ListQuery }, summary: ${say(`List ${listTitle.toLowerCase()}`)} }, (req, res) => {
    const { page, limit } = req.valid.query;
    const size = clampLimit(limit);
    const rows = ${plan.ownerScoped ? `req.user?.isAdmin ? listAll${plan.pascalName}(size, (page - 1) * size) : list${plan.pascalName}ForOwner(req.user!.id, size, (page - 1) * size)` : `listAll${plan.pascalName}(size, (page - 1) * size)`};
    renderPage(req, res, '${plan.moduleDir}/list', { title: ${JSON.stringify(listTitle)}, records: rows.map((r) => dtoFor(req, r)), page, hasMore: rows.length === size, quota: ${plan.camelName.toUpperCase()}_QUOTA_PER_USER });
  });

  defineRoute(router, { method: 'GET', path: '${plan.base}/new', auth: ${plan.writeAuth}, entity: '${plan.entity.name}', summary: ${say(`New ${lower} form`)} }, (req, res) => {
    renderPage(req, res, '${plan.moduleDir}/form', { title: 'New ${label.toLowerCase()}', record: null, values: {}, quota: ${plan.camelName.toUpperCase()}_QUOTA_PER_USER });
  });

  defineRoute(
    router,
    { method: 'POST', path: '${plan.base}', auth: ${plan.writeAuth}, entity: '${plan.entity.name}', schema: { body: ${plan.pascalName}Body }, onInvalid: (req, res, fields) => renderForm(req, res, fields), summary: ${say(`Create ${aLabel}`)} },
    (req, res) => {
      const result = create${plan.pascalName}(req.user!.id, req.valid.body);
      if (!result.ok) return renderForm(req, res, { _: \`You can keep up to \${${plan.camelName.toUpperCase()}_QUOTA_PER_USER} ${listTitle.toLowerCase()}. Delete one to make room.\` }, 409);
      req.session.flash('success', '${label} saved.');
      res.redirect(303, \`${plan.base}/\${result.record.id}\`);
    },
  );

  defineRoute(router, { method: 'GET', path: '${plan.base}/:id', auth: ${plan.readAuth}, ${owner}entity: '${plan.entity.name}', schema: { params: ${plan.pascalName}Params }, summary: ${say(`View ${aLabel}`)} }, (req, res) => {
    renderPage(req, res, '${plan.moduleDir}/show', { title: ${JSON.stringify(label)}, record: dtoFor(req, recordFromRequest(req)) });
  });

  defineRoute(router, { method: 'GET', path: '${plan.base}/:id/edit', auth: ${plan.writeAuth}, ${owner}entity: '${plan.entity.name}', schema: { params: ${plan.pascalName}Params }, summary: ${say(`Edit ${aLabel}`)} }, (req, res) => {
    const record = toOwnerDto(recordFromRequest(req));
    renderPage(req, res, '${plan.moduleDir}/form', { title: 'Edit ${label.toLowerCase()}', record, values: record, quota: ${plan.camelName.toUpperCase()}_QUOTA_PER_USER });
  });

  defineRoute(
    router,
    {
      method: 'POST',
      path: '${plan.base}/:id',
      auth: ${plan.writeAuth},
      ${owner}entity: '${plan.entity.name}',
      schema: { params: ${plan.pascalName}Params, body: ${plan.pascalName}UpdateBody },
      onInvalid: (req, res, fields) => renderForm(req, res, fields),
      summary: ${say(`Save changes to ${aLabel}`)},
    },
    (req, res) => {
      const record = recordFromRequest(req);
      const { updatedAt, ...input } = req.valid.body;
      const result = update${plan.pascalName}(record.id, input, updatedAt);
      if (!result.ok) {
        const message =
          result.reason === 'conflict'
            ? 'This ${label.toLowerCase()} was changed since you opened it. Reload the page, then apply your change again.'
            : 'This ${label.toLowerCase()} no longer exists.';
        return renderForm(req, res, { _: message }, result.reason === 'not-found' ? 404 : 409);
      }
      req.session.flash('success', '${label} saved.');
      res.redirect(303, \`${plan.base}/\${record.id}\`);
    },
  );

  defineRoute(router, { method: 'POST', path: '${plan.base}/:id/delete', auth: ${plan.writeAuth}, ${owner}entity: '${plan.entity.name}', schema: { params: ${plan.pascalName}Params }, summary: ${say(`Delete ${aLabel}`)} }, (req, res) => {
    delete${plan.pascalName}(recordFromRequest(req).id);
    req.session.flash('success', '${label} deleted.');
    res.redirect(303, '${plan.base}');
  });

  // ---------- JSON API ----------
  defineRoute(router, { method: 'GET', path: '/api${plan.base}', auth: ${plan.readAuth}, kind: 'api', entity: '${plan.entity.name}', schema: { query: ${plan.pascalName}ListQuery }, summary: ${say(`List ${listTitle.toLowerCase()}`)} }, (req, res) => {
    const { page, limit } = req.valid.query;
    const size = clampLimit(limit);
    const rows = ${plan.ownerScoped ? `req.user?.isAdmin ? listAll${plan.pascalName}(size, (page - 1) * size) : list${plan.pascalName}ForOwner(req.user!.id, size, (page - 1) * size)` : `listAll${plan.pascalName}(size, (page - 1) * size)`};
    res.json({ records: rows.map((r) => dtoFor(req, r)), page, limit: size });
  });

  defineRoute(
    router,
    { method: 'POST', path: '/api${plan.base}', auth: ${plan.writeAuth}, kind: 'api', entity: '${plan.entity.name}', idempotent: true, schema: { body: ${plan.pascalName}Body }, summary: ${say(`Create ${aLabel} (supports Idempotency-Key)`)} },
    (req, res) => {
      const result = create${plan.pascalName}(req.user!.id, req.valid.body);
      if (!result.ok) throw errors.quota(\`You can keep up to \${${plan.camelName.toUpperCase()}_QUOTA_PER_USER} ${listTitle.toLowerCase()}.\`);
      res.status(201).json(toOwnerDto(result.record));
    },
  );

  defineRoute(router, { method: 'GET', path: '/api${plan.base}/:id', auth: ${plan.readAuth}, kind: 'api', ${owner}entity: '${plan.entity.name}', schema: { params: ${plan.pascalName}Params }, summary: ${say(`Read one ${lower}`)} }, (req, res) => {
    res.json(dtoFor(req, recordFromRequest(req)));
  });

  defineRoute(
    router,
    { method: 'PATCH', path: '/api${plan.base}/:id', auth: ${plan.writeAuth}, kind: 'api', ${owner}entity: '${plan.entity.name}', schema: { params: ${plan.pascalName}Params, body: ${plan.pascalName}PatchBody }, summary: ${say(`Update ${aLabel}`)} },
    (req, res) => {
      const record = recordFromRequest(req);
      const { updatedAt, ...input } = req.valid.body;
      const result = update${plan.pascalName}(record.id, input, updatedAt);
      if (!result.ok) {
        if (result.reason === 'not-found') throw errors.notFound();
        throw errors.conflict();
      }
      res.json(toOwnerDto(result.record));
    },
  );

  defineRoute(router, { method: 'DELETE', path: '/api${plan.base}/:id', auth: ${plan.writeAuth}, kind: 'api', ${owner}entity: '${plan.entity.name}', schema: { params: ${plan.pascalName}Params }, summary: ${say(`Delete ${aLabel}`)} }, (req, res) => {
    delete${plan.pascalName}(recordFromRequest(req).id);
    res.status(204).end();
  });
}
`;
}
