/**
 * Test emitter for the CRUD expander. Every generated feature ships the four checks the Security Contract
 * requires (SC-17): anonymous denied, wrong role denied, validation rejects bad input, ownership enforced —
 * plus a create/read/update/delete round trip and a DTO check for sensitive fields.
 */
import type { EntityPlan, FieldPlan } from './fields.js';

/** A valid value for a field, used to build a create/update payload in the generated tests. */
function sampleValue(f: FieldPlan, variant: 'a' | 'b'): string {
  const suffix = variant === 'a' ? 'one' : 'two';
  switch (f.control) {
    case 'number':
      return variant === 'a' ? '1' : '2';
    case 'money':
      return variant === 'a' ? '9.99' : '19.99';
    case 'checkbox':
      return variant === 'a' ? "'on'" : "'on'";
    case 'date':
      return variant === 'a' ? "'2026-01-01'" : "'2026-02-02'";
    case 'datetime-local':
      return variant === 'a' ? "'2026-01-01T09:00'" : "'2026-02-02T10:30'";
    case 'email':
      return variant === 'a' ? "'sample.one@example.com'" : "'sample.two@example.com'";
    case 'url':
      return "'https://example.com'";
    case 'tel':
      return "'+1 555 0100'";
    case 'select': {
      const choices = f.field.choices ?? [];
      const pick = variant === 'a' ? choices[0] : (choices[1] ?? choices[0]);
      return JSON.stringify(pick ?? '');
    }
    case 'textarea':
      return `'Sample text ${suffix}'`;
    default:
      return `'Sample ${suffix}'`;
  }
}

export function emitTest(plan: EntityPlan, runId: string): string {
  const label = plan.entity.label;
  // File fields hold the id of an upload; the test has none to point at, so they stay out of the payloads.
  const payloadFields = plan.fields.filter((f) => f.field.type !== 'file');
  const payloadA = payloadFields.map((f) => `  ${f.prop}: ${sampleValue(f, 'a')},`).join('\n');
  const payloadB = payloadFields.map((f) => `  ${f.prop}: ${sampleValue(f, 'b')},`).join('\n');
  const requiredField = plan.fields.find((f) => f.field.required);
  const invalidPayload = requiredField
    ? `{ ...PAYLOAD_A, ${requiredField.prop}: ${requiredField.control === 'number' || requiredField.control === 'money' ? "'not-a-number'" : requiredField.control === 'select' ? "'not-a-choice'" : requiredField.control === 'email' ? "'not-an-email'" : requiredField.control === 'date' || requiredField.control === 'datetime-local' ? "'yesterday'" : "''"} }`
    : `{ ...PAYLOAD_A, somethingUnknown: 'x' }`;
  const sensitive = plan.fields.filter((f) => f.field.sensitive);

  return `// Generated by SecureVibe (expanded from your answers) — run ${runId}
/** ${label}: the security checks every generated feature must pass (SC-17). */
import { after, before, describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { CookieJar, startApp, type RunningApp } from '../helpers/app.ts';
import { users } from '../helpers/conventions.ts';

const BASE = '${plan.base}';
const API = '/api${plan.base}';

const PAYLOAD_A = {
${payloadA}
};
const PAYLOAD_B = {
${payloadB}
};
/** Everything the owner view may contain: the form fields plus record metadata. */
const OWNER_FIELDS = new Set([${plan.fields.map((f) => JSON.stringify(f.prop)).join(', ')}${plan.fields.length > 0 ? ', ' : ''}'id', 'createdAt', 'updatedAt']);

describe('${plan.entity.name}', () => {
  let app: RunningApp;
  before(async () => {
    app = await startApp();
  });
  after(async () => {
    await app?.stop();
  });

  test('${plan.entity.name}: a signed-out visitor cannot reach the records', async () => {
    const res = await app.fetch(API, { jar: new CookieJar() });
    await res.text();
    ${plan.publicRead ? `assert.ok(res.status === 200 || res.status === 401, 'a public list either answers or asks for a sign-in');` : `assert.ok(res.status === 401 || res.status === 403, \`expected a denial, got \${res.status}\`);`}
    const write = await app.json('POST', API, PAYLOAD_A, new CookieJar());
    await write.text();
    assert.ok(write.status === 401 || write.status === 403, \`creating without signing in must be refused, got \${write.status}\`);
  });

  test('${plan.entity.name}: validation rejects input that does not fit the form', async () => {
    const jar = await app.login(${plan.adminOnly ? 'users.admin' : 'users.member'});
    const res = await app.json('POST', API, ${invalidPayload}, jar);
    await res.text();
    assert.equal(res.status, 400, 'invalid input must be refused with 400');
    const unknown = await app.json('POST', API, { ...PAYLOAD_A, notAField: 'x' }, jar);
    await unknown.text();
    assert.equal(unknown.status, 400, 'unknown fields must be refused (mass assignment)');
  });

  test('${plan.entity.name}: create, read, update and delete work for the owner', async () => {
    const jar = await app.login(${plan.adminOnly ? 'users.admin' : 'users.member'});
    const created = await app.json('POST', API, PAYLOAD_A, jar);
    const record = (await created.json()) as { id: string; updatedAt: string };
    assert.equal(created.status, 201, 'the record must be created');
    assert.ok(record.id, 'the created record must have an id');

    const read = await app.fetch(\`\${API}/\${record.id}\`, { jar });
    assert.equal(read.status, 200, 'the owner must be able to read it back');
    await read.text();

    const updated = await app.json('PATCH', \`\${API}/\${record.id}\`, { ...PAYLOAD_B, updatedAt: record.updatedAt }, jar);
    assert.equal(updated.status, 200, \`the owner must be able to update it (got \${updated.status})\`);
    await updated.text();

    const removed = await app.json('DELETE', \`\${API}/\${record.id}\`, undefined, jar);
    assert.equal(removed.status, 204, 'the owner must be able to delete it');
    await removed.text();
  });

  test('V2.3.3 ${plan.entity.name}: the list never returns an unbounded result set', async () => {
    const jar = await app.login(${plan.adminOnly ? 'users.admin' : 'users.member'});
    const res = await app.fetch(\`\${API}?limit=100000\`, { jar, headers: { Accept: 'application/json' } });
    const text = await res.text();
    if (res.status === 400) return; // an oversized page size is refused outright
    assert.equal(res.status, 200, \`the list must answer (got \${res.status})\`);
    const body = JSON.parse(text) as { records: unknown[]; limit: number };
    assert.ok(body.limit <= 200, \`the page size must be capped (got \${body.limit})\`);
    assert.ok(body.records.length <= 200, 'no more than one capped page of records is returned');
  });

  test('V8.2.3 ${plan.entity.name}: each audience sees only the fields meant for it', async () => {
    const jar = await app.login(${plan.adminOnly ? 'users.admin' : 'users.member'});
    const created = await app.json('POST', API, PAYLOAD_A, jar);
    const record = (await created.json()) as Record<string, unknown> & { id: string };
    assert.equal(created.status, 201);
    const extra = Object.keys(record).filter((k) => !OWNER_FIELDS.has(k)${plan.adminOnly ? " && k !== 'ownerId'" : ''});
    assert.deepEqual(extra, [], 'the response must contain only form fields and record metadata (no raw columns or owner ids)');
${
  plan.adminOnly
    ? ''
    : `
    const admin = await app.login(users.admin);
    const read = await app.fetch(\`\${API}/\${record.id}\`, { jar: admin, headers: { Accept: 'application/json' } });
    const adminView = read.status === 200 ? ((await read.json()) as Record<string, unknown>) : (await read.text(), undefined);
    if (adminView) {
      const adminExtra = Object.keys(adminView).filter((k) => !OWNER_FIELDS.has(k) && k !== 'ownerId');
      assert.deepEqual(adminExtra, [], 'the administrator view adds only the owner id');
    }`
}
  });
${
  plan.ownerScoped
    ? `
  test('${plan.entity.name}: another signed-in person cannot read or change a record they do not own', async () => {
    const owner = await app.login(users.member);
    const created = await app.json('POST', API, PAYLOAD_A, owner);
    const record = (await created.json()) as { id: string; updatedAt: string };
    assert.equal(created.status, 201);

    const other = await app.login(users.member2);
    const read = await app.fetch(\`\${API}/\${record.id}\`, { jar: other });
    await read.text();
    assert.ok(read.status === 403 || read.status === 404, \`a non-owner must not read the record (got \${read.status})\`);

    const write = await app.json('PATCH', \`\${API}/\${record.id}\`, { ...PAYLOAD_B, updatedAt: record.updatedAt }, other);
    await write.text();
    assert.ok(write.status === 403 || write.status === 404, \`a non-owner must not change the record (got \${write.status})\`);

    const remove = await app.json('DELETE', \`\${API}/\${record.id}\`, undefined, other);
    await remove.text();
    assert.ok(remove.status === 403 || remove.status === 404, \`a non-owner must not delete the record (got \${remove.status})\`);
  });
`
    : ''
}${
    plan.adminOnly
      ? `
  test('${plan.entity.name}: a person without the administrator role is refused', async () => {
    const member = await app.login(users.member);
    const res = await app.fetch(API, { jar: member });
    await res.text();
    assert.ok(res.status === 403 || res.status === 404, \`a non-administrator must be refused (got \${res.status})\`);
  });
`
      : ''
  }${
    sensitive.length > 0
      ? `
  test('${plan.entity.name}: sensitive fields are not shown to other people', async () => {
    const owner = await app.login(users.member);
    const created = await app.json('POST', API, PAYLOAD_A, owner);
    const record = (await created.json()) as Record<string, unknown> & { id: string };
    assert.equal(created.status, 201);
${sensitive.map((f) => `    assert.ok(${JSON.stringify(f.prop)} in record, 'the owner sees ${f.field.label}');`).join('\n')}

    const list = await app.fetch(API, { jar: await app.login(users.member2) });
    const body = (await list.json()) as { records?: Record<string, unknown>[] };
    for (const r of body.records ?? []) {
${sensitive.map((f) => `      assert.ok(!(${JSON.stringify(f.prop)} in r), '${f.field.label} must not be listed for other people');`).join('\n')}
    }
  });
`
      : ''
  }});
`;
}
