/**
 * Code emitters for the record-chart recipe: one page per record type that draws how it changed, month by month.
 *
 * The picture is a plain drawing written into the page itself — no chart library, no script, no stylesheet, and
 * nothing fetched from anywhere. Four decisions make it that way, and each one is there to remove a risk rather
 * than to be clever:
 *
 *  - **The drawing is built in the view with escaped output only** (`<%= %>`). A chart library would mean either a
 *    file from somewhere else or a script assembling markup in the browser; instead every number the page draws
 *    with goes through the template's own escaping, the same way a name in a table does.
 *  - **Only whole numbers reach the drawing.** The route turns every figure into a position or a length with
 *    `Math.round`, and refuses anything that is not a finite number, so a stored value can never become a
 *    coordinate the browser has to guess at.
 *  - **Nothing a person typed is drawn.** The labels are the app's own field names and the months themselves; the
 *    values are counts and totals. There is no path by which text from a record reaches the picture.
 *  - **The same figures are repeated underneath as a table**, which is what a screen reader reads, what the app's
 *    own tests measure, and what someone sees if the drawing does not render.
 *
 * The page lives at `/charts/<plural>` for the same reason the report lives at `/reports/<plural>`: the record
 * type's own `<base>/:id` route is registered first and would otherwise match `chart` as a record id.
 */
import type { EntityPlan, SummaryField } from '../record-type/fields.js';
import { commentText } from '../js-literal.js';

const HEADER = (runId: string) => `// Generated by SecureVibe (recipe record-chart) — run ${runId}\n`;

/** One line the chart can draw over time: how many records, or the total of one amount field. */
export interface ChartSeries {
  /** The column being totaled, or `records` for the count. */
  key: string;
  label: string;
  kind: 'count' | 'number' | 'money';
}

export interface ChartPlan {
  entity: EntityPlan;
  series: ChartSeries[];
  moduleDir: string;
  /** `/charts/items`. */
  path: string;
  title: string;
}

/**
 * What the chart draws: always how many records were added each month, and then one line per amount the records
 * carry. Choices and yes/no fields are deliberately not here — the report page already tallies those, and a tally
 * of options over time is a different and much harder picture to read honestly.
 *
 * A field the person marked sensitive never appears, for the same reason it is left off the report: a monthly total
 * can give away as much as the values, and a chart makes a small number of records easy to read off the page.
 */
export function chartSeriesOf(entity: EntityPlan): ChartSeries[] {
  const amounts = entity.summaries.filter((f): f is SummaryField & { kind: 'number' | 'money' } => f.kind === 'number' || f.kind === 'money');
  const plural = (entity.entity.pluralLabel ?? `${entity.entity.label}s`).toLowerCase();
  return [
    { key: 'records', label: `How many ${plural} added`, kind: 'count' },
    ...amounts.map((f): ChartSeries => ({ key: f.column, label: `Total ${f.label.toLowerCase()}`, kind: f.kind })),
  ];
}

export function chartPlan(entity: EntityPlan): ChartPlan {
  const plural = entity.entity.pluralLabel ?? `${entity.entity.label}s`;
  return {
    entity,
    series: chartSeriesOf(entity),
    moduleDir: `${entity.moduleDir}-chart`,
    path: `/charts${entity.base}`,
    title: `${plural} over time`,
  };
}

/**
 * Who may open the chart. A record type anyone may read still gets a chart that needs a sign-in, for the reason the
 * report page needs one: the list shows one page of records, while a chart is a shape taken over all of them.
 */
export function chartAuth(plan: ChartPlan): string {
  return plan.entity.publicRead ? "'user'" : plan.entity.readAuth;
}

export function emitRoutes(plan: ChartPlan, runId: string): string {
  const entity = plan.entity;
  const amounts = plan.series.filter((s) => s.kind !== 'count');
  const plural = (entity.entity.pluralLabel ?? `${entity.entity.label}s`).toLowerCase();

  // The aggregate columns are written out here, at generation time, so the emitted SQL is a fixed string.
  const aggregateColumns = ['COUNT(*) AS records', ...amounts.map((s) => `SUM(${s.key}) AS sum_${s.key}`)].join(', ');
  const rowType = ['  month: string;', '  records: number | null;', ...amounts.map((s) => `  sum_${s.key}: number | null;`)].join('\n');
  const seriesLines = plan.series
    .map((s) => {
      // Money is stored as whole cents, so the figure shown is the amount again.
      const value = s.kind === 'count' ? 'finite(row?.records)' : s.kind === 'money' ? `finite(row?.sum_${s.key}) / 100` : `finite(row?.sum_${s.key})`;
      return `    { key: ${JSON.stringify(s.key)}, label: ${JSON.stringify(s.label)}, kind: ${JSON.stringify(s.kind)} as const, valueFor: (row: MonthRow | undefined) => ${value} },`;
    })
    .join('\n');

  const ownerScoped = entity.ownerScoped;

  return `${HEADER(runId)}/**
 * ${commentText(plan.title)}: a read-only page that draws how the ${commentText(plural)} changed, month by month.
 *
 * The database groups the rows by month (\`substr(created_at, 1, 7)\`, a plain string slice rather than a date
 * calculation), so the page costs one query however many records there are, and the query is a fixed string.
 *
 * Everything the drawing is made of is a whole number worked out here: a bar's height, its position, the width of
 * the picture. \`finite()\` turns anything that is not a real number into nothing, and \`Math.round\` makes every
 * coordinate a whole number, so the view never writes a value into the drawing that the browser has to guess at.
 * No text from a record is drawn: the labels are this app's own field names and the months themselves.${
   ownerScoped
     ? `
 *
 * Records here belong to one person, so the chart is drawn from the signed-in person's own records. An
 * administrator, who may already read every record, sees the shape over all of them.`
     : ''
 }
 */
import type { Request, Response, Router } from 'express';
import { z } from 'zod';
import { all } from '../../db/index.ts';
import { renderPage } from '../../lib/views.ts';
import { defineRoute } from '../../security/routes.ts';

/**
 * The record type's table. Written out here rather than imported so that every query below is plainly a fixed
 * string: nothing about a query is assembled while the app runs.
 */
const TABLE = '${entity.table}';

/** How the picture is laid out. Fixed numbers, so no measurement ever depends on what is in the database. */
const BAR_WIDTH = 22;
const BAR_GAP = 8;
const PLOT_HEIGHT = 120;
const TOP = 16;
const LEFT = 10;
const AXIS_HEIGHT = 20;

const MONTHS_ALL = \`SELECT substr(created_at, 1, 7) AS month, ${aggregateColumns} FROM \${TABLE} WHERE created_at >= ? GROUP BY month\`;
const MONTHS_FOR_OWNER = \`SELECT substr(created_at, 1, 7) AS month, ${aggregateColumns} FROM \${TABLE} WHERE created_at >= ? AND owner_id = ? GROUP BY month\`;

interface MonthRow {
${rowType}
}

/** How many months to draw. A number the person chose, within limits, or twelve. */
const ChartQuery = z.strictObject({
  months: z.preprocess((v) => (v === '' || v === null ? undefined : v), z.coerce.number().int().min(3).max(36).optional()),
});

/** Anything that is not a real number is treated as nothing at all, rather than drawn. */
function finite(value: unknown): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

/** The months to draw, oldest first, as the \`YYYY-MM\` strings the query groups by. */
function monthsBack(count: number): string[] {
  const now = new Date();
  const out: string[] = [];
  for (let i = count - 1; i >= 0; i -= 1) {
    const month = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - i, 1));
    out.push(\`\${month.getUTCFullYear()}-\${String(month.getUTCMonth() + 1).padStart(2, '0')}\`);
  }
  return out;
}

/** Each line the chart can draw, and how to read its figure off a month's row. */
const SERIES = [
${seriesLines}
];

interface Bar {
  /** \`2026-03\`, for the table underneath. */
  month: string;
  /** \`03\`, for the label under the bar. */
  short: string;
  /** The figure as the page shows it. */
  shown: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

interface Chart {
  label: string;
  bars: Bar[];
  /** The largest figure in this chart, as the page shows it, so the reader knows what full height means. */
  peak: string;
  width: number;
  height: number;
  baseline: number;
}

/** How a figure is written: an amount of money to the penny, a count as a whole number. */
function show(kind: 'count' | 'number' | 'money', value: number): string {
  if (kind === 'money') return value.toFixed(2);
  return Number.isInteger(value) ? String(value) : value.toFixed(2);
}

export function register(router: Router): void {
  defineRoute(
    router,
    {
      method: 'GET',
      path: '${plan.path}',
      auth: ${chartAuth(plan)},
      entity: '${entity.entity.name}',
      kind: 'page',
      schema: { query: ChartQuery },
      summary: ${JSON.stringify(plan.title)},
      // In the menu under its own name: the owner of the first app built with charts went looking for hers at
      // app level rather than from the record's list page, which is also where the home page shows it.
      menu: ${JSON.stringify(plan.title)},
    },
    (req: Request, res: Response) => {
      const months = monthsBack((req.valid.query as { months?: number }).months ?? 12);
      const earliest = \`\${months[0]}-01T00:00:00.000Z\`;
      // Only the signed-in person's own records are drawn where records belong to one person; an administrator,
      // who may read them all, sees the shape over all of them.
      const ownerId = ${ownerScoped ? `req.user?.isAdmin ? undefined : req.user?.id` : 'undefined'};
      const rows = ownerId ? all<MonthRow>(MONTHS_FOR_OWNER, [earliest, ownerId]) : all<MonthRow>(MONTHS_ALL, [earliest]);
      const byMonth = new Map(rows.map((row) => [String(row.month), row]));

      const width = LEFT * 2 + months.length * (BAR_WIDTH + BAR_GAP);
      const height = TOP + PLOT_HEIGHT + AXIS_HEIGHT;
      const charts: Chart[] = SERIES.map((series) => {
        const values = months.map((month) => series.valueFor(byMonth.get(month)));
        const peak = values.reduce((most, v) => (v > most ? v : most), 0);
        const bars: Bar[] = months.map((month, i) => {
          const value = values[i] ?? 0;
          // A bar is a whole number of units tall, and is never taller than the plot: the peak is full height.
          const barHeight = peak > 0 ? Math.max(0, Math.min(PLOT_HEIGHT, Math.round((value / peak) * PLOT_HEIGHT))) : 0;
          return {
            month,
            short: month.slice(5),
            shown: show(series.kind, value),
            x: Math.round(LEFT + i * (BAR_WIDTH + BAR_GAP)),
            y: Math.round(TOP + PLOT_HEIGHT - barHeight),
            width: BAR_WIDTH,
            height: barHeight,
          };
        });
        return { label: series.label, bars, peak: show(series.kind, peak), width, height, baseline: TOP + PLOT_HEIGHT };
      });

      renderPage(req, res, '${plan.moduleDir}/index', {
        title: ${JSON.stringify(plan.title)},
        recordsPath: '${entity.base}',
        months: months.length,
        firstMonth: months[0] ?? '',
        lastMonth: months[months.length - 1] ?? '',
        charts,
      });
    },
  );
}
`;
}

export function emitView(plan: ChartPlan): string {
  const plural = (plan.entity.entity.pluralLabel ?? `${plan.entity.entity.label}s`).toLowerCase();
  // Every value in the drawing goes through `<%= %>`. There is no `<%- %>` here and there must never be one: the
  // whole point of building the picture in the view is that the template's own escaping is what writes it.
  return `<section class="card">
  <h1><%= title %></h1>
  <form method="get" action="${plan.path}" class="filters">
    <div class="field">
      <label for="months">Months to show</label>
      <input id="months" name="months" type="number" min="3" max="36" value="<%= months %>">
    </div>
    <button type="submit" class="button">Show</button>
  </form>
  <p class="muted"><%= firstMonth %> to <%= lastMonth %>. The tallest bar in each picture is the largest figure in it; the same numbers are in the table underneath.</p>
  <% for (const c of charts) { %>
    <h2><%= c.label %></h2>
    <p class="muted">Tallest bar: <%= c.peak %></p>
    <%
      /* Drawn with the page's own text color, so it follows the theme without a stylesheet of its own. */
    %>
    <svg viewBox="0 0 <%= c.width %> <%= c.height %>" width="100%" height="<%= c.height %>" role="img" aria-label="<%= c.label %>, by month" preserveAspectRatio="xMinYMin meet">
      <title><%= c.label %>, by month</title>
      <line x1="0" y1="<%= c.baseline %>" x2="<%= c.width %>" y2="<%= c.baseline %>" stroke="currentColor" stroke-width="1" opacity="0.3"></line>
      <% for (const b of c.bars) { %>
        <rect x="<%= b.x %>" y="<%= b.y %>" width="<%= b.width %>" height="<%= b.height %>" fill="currentColor" opacity="0.65"></rect>
        <text x="<%= b.x + b.width / 2 %>" y="<%= c.baseline + 14 %>" text-anchor="middle" font-size="9" fill="currentColor" opacity="0.7"><%= b.short %></text>
      <% } %>
    </svg>
    <table class="table">
      <thead><tr><th>Month</th><th><%= c.label %></th></tr></thead>
      <tbody>
        <% for (const b of c.bars) { %>
          <tr data-series="<%= c.label %>" data-month="<%= b.month %>" data-value="<%= b.shown %>"><td><%= b.month %></td><td><%= b.shown %></td></tr>
        <% } %>
      </tbody>
    </table>
  <% } %>
  <p class="muted"><a href="<%= recordsPath %>">Back to ${plural}</a></p>
</section>
`;
}
