/**
 * Code emitters for the record-summary recipe: one read-only page per record type that adds up what is there.
 *
 * Two things shape the emitted code. First, every query is a fixed string built from constants declared in the same
 * file — the aggregates are spelled out in full, because a query assembled while the app runs is exactly what the
 * static scan objects to, and rightly. Second, the totals are computed by the database with `COUNT`, `SUM` and
 * `AVG` rather than by loading the rows, so a summary over a large table is one cheap query instead of a page's
 * worth of memory.
 *
 * The page lives at `/reports/<plural>` rather than `<base>/summary`, because the record type's own
 * `<base>/:id` route is registered first and would match `summary` as an id.
 */
import type { EntityPlan, SummaryField } from '../record-type/fields.js';
import { commentText } from '../js-literal.js';

const HEADER = (runId: string) => `// Generated by SecureVibe (recipe record-summary) — run ${runId}\n`;

export interface SummaryPlan {
  entity: EntityPlan;
  fields: SummaryField[];
  moduleDir: string;
  /** `/reports/items`. */
  path: string;
  /** What the page is called. */
  title: string;
}

export function summaryPlan(entity: EntityPlan): SummaryPlan {
  const plural = entity.entity.pluralLabel ?? `${entity.entity.label}s`;
  return {
    entity,
    fields: entity.summaries,
    moduleDir: `${entity.moduleDir}-report`,
    path: `/reports${entity.base}`,
    title: `${plural} report`,
  };
}

/**
 * Who may read the report. A record type anyone may read still gets a report that needs a sign-in: the list shows
 * one page at a time, while a total is taken over every record, so the report can say more than the list does.
 */
export function reportAuth(plan: SummaryPlan): string {
  return plan.entity.publicRead ? "'user'" : plan.entity.readAuth;
}

/** Amounts and yes/no fields are totalled in one query; choice fields each need their own grouped query. */
function totalFields(plan: SummaryPlan): SummaryField[] {
  return plan.fields.filter((f) => f.kind !== 'choice');
}

function choiceFields(plan: SummaryPlan): SummaryField[] {
  return plan.fields.filter((f) => f.kind === 'choice');
}

export function emitRoutes(plan: SummaryPlan, runId: string): string {
  const entity = plan.entity;
  const totals = totalFields(plan);
  const choices = choiceFields(plan);
  // The aggregate columns are written out here, at generation time, so the emitted SQL is a fixed string.
  const aggregateColumns = [
    'COUNT(*) AS records',
    ...totals.flatMap((f) =>
      f.kind === 'boolean'
        ? [`SUM(CASE WHEN ${f.column} = 1 THEN 1 ELSE 0 END) AS yes_${f.column}`]
        : [`SUM(${f.column}) AS sum_${f.column}`, `AVG(${f.column}) AS avg_${f.column}`],
    ),
  ].join(', ');

  const rowType = [
    '  records: number;',
    ...totals.flatMap((f) => (f.kind === 'boolean' ? [`  yes_${f.column}: number | null;`] : [`  sum_${f.column}: number | null;`, `  avg_${f.column}: number | null;`])),
  ].join('\n');

  const choiceSql = choices
    .map(
      (f) => `  ${JSON.stringify(f.column)}: {
    all: \`SELECT ${f.column} AS value, COUNT(*) AS records FROM \${TABLE} WHERE created_at >= ? AND created_at <= ? GROUP BY ${f.column}\`,
    owner: \`SELECT ${f.column} AS value, COUNT(*) AS records FROM \${TABLE} WHERE created_at >= ? AND created_at <= ? AND owner_id = ? GROUP BY ${f.column}\`,
  },`,
    )
    .join('\n');

  const totalLines = totals
    .map((f) => {
      if (f.kind === 'boolean') {
        return `    { label: ${JSON.stringify(f.label)}, kind: 'boolean' as const, total: Number(row.yes_${f.column} ?? 0), average: null },`;
      }
      // Money is stored as whole cents, so it is turned back into an amount for display.
      const divisor = f.kind === 'money' ? ' / 100' : '';
      return `    { label: ${JSON.stringify(f.label)}, kind: ${JSON.stringify(f.kind)} as const, total: row.sum_${f.column} === null ? 0 : Number(row.sum_${f.column})${divisor}, average: row.avg_${f.column} === null ? null : Number(row.avg_${f.column})${divisor} },`;
    })
    .join('\n');

  const choiceLines = choices
    .map(
      (f) => `    {
      label: ${JSON.stringify(f.label)},
      options: countsFor(${JSON.stringify(f.column)}, ${JSON.stringify(f.choices)}, range, ownerId),
    },`,
    )
    .join('\n');

  const ownerScoped = entity.ownerScoped;

  return `${HEADER(runId)}/**
 * ${commentText(plan.title)}: a read-only page that adds up the ${commentText((entity.entity.pluralLabel ?? `${commentText(entity.entity.label)}s`).toLowerCase())} that are there.
 *
 * The database does the adding up (COUNT, SUM, AVG), so the page costs one query per section however many records
 * there are, and every query below is a fixed string.${
   ownerScoped
     ? `

 * Records here belong to one person, so the totals are taken over the signed-in person's own records. An
 * administrator, who may already read every record, sees the totals over all of them.`
     : ''
 }
 * Fields the person marked as sensitive are not summarised at all: a total or a breakdown can give away as much as
 * the values would.
 */
import type { Request, Response, Router } from 'express';
import { z } from 'zod';
import { all, get } from '../../db/index.ts';
import { renderPage } from '../../lib/views.ts';
import { defineRoute } from '../../security/routes.ts';

/**
 * The record type's table. Written out here rather than imported so that every query below is plainly a fixed
 * string: nothing about a query is assembled while the app runs.
 */
const TABLE = '${entity.table}';

/** Both ends of the range are always bound, so one statement covers "everything" and "between two dates". */
const EARLIEST = '0000-01-01T00:00:00.000Z';
const LATEST = '9999-12-31T23:59:59.999Z';

const TOTALS_ALL = \`SELECT ${aggregateColumns} FROM \${TABLE} WHERE created_at >= ? AND created_at <= ?\`;
const TOTALS_FOR_OWNER = \`SELECT ${aggregateColumns} FROM \${TABLE} WHERE created_at >= ? AND created_at <= ? AND owner_id = ?\`;
${
  choices.length > 0
    ? `
/** One grouped statement per choice field, each written out in full. */
const CHOICE_SQL: Record<string, { all: string; owner: string }> = {
${choiceSql}
};
`
    : ''
}
interface TotalsRow {
${rowType}
}

/** A date the person typed, or nothing. Anything else is refused before it reaches a query. */
const ReportQuery = z.strictObject({
  from: z
    .string()
    .trim()
    .regex(/^\\d{4}-\\d{2}-\\d{2}$/, 'Please use the date picker.')
    .optional(),
  to: z
    .string()
    .trim()
    .regex(/^\\d{4}-\\d{2}-\\d{2}$/, 'Please use the date picker.')
    .optional(),
});

interface Range {
  from: string;
  to: string;
}

/** Turns the two optional dates into the timestamps the queries are given. */
function rangeOf(query: { from?: string; to?: string }): Range {
  return {
    from: query.from ? \`\${query.from}T00:00:00.000Z\` : EARLIEST,
    to: query.to ? \`\${query.to}T23:59:59.999Z\` : LATEST,
  };
}
${
  choices.length > 0
    ? `
/** How many records carry each option of one choice field, including the options nothing uses yet. */
function countsFor(column: string, options: string[], range: Range, ownerId: string | undefined): { value: string; records: number }[] {
  const sql = CHOICE_SQL[column];
  if (!sql) return []; // unreachable: the column is one of this page's own, never a value from a request
  const rows = ownerId
    ? all<{ value: string | null; records: number }>(sql.owner, [range.from, range.to, ownerId])
    : all<{ value: string | null; records: number }>(sql.all, [range.from, range.to]);
  const counted = new Map(rows.map((r) => [r.value ?? '', Number(r.records)]));
  const known = options.map((value) => ({ value, records: counted.get(value) ?? 0 }));
  // Anything stored that is not one of the described options (an older record, say) is shown as "not set".
  const other = [...counted.entries()].filter(([value]) => !options.includes(value)).reduce((sum, [, n]) => sum + n, 0);
  return other > 0 ? [...known, { value: '(not set)', records: other }] : known;
}
`
    : ''
}
export function register(router: Router): void {
  defineRoute(
    router,
    {
      method: 'GET',
      path: '${plan.path}',
      auth: ${reportAuth(plan)},
      entity: '${entity.entity.name}',
      kind: 'page',
      schema: { query: ReportQuery },
      summary: ${JSON.stringify(plan.title)},
    },
    (req: Request, res: Response) => {
      const range = rangeOf(req.valid.query as { from?: string; to?: string });
      // Only the signed-in person's own records are counted where records belong to one person; an administrator,
      // who may read them all, sees the totals over all of them.
      const ownerId = ${ownerScoped ? `req.user?.isAdmin ? undefined : req.user?.id` : 'undefined'};
      const row =
        (ownerId
          ? get<TotalsRow>(TOTALS_FOR_OWNER, [range.from, range.to, ownerId])
          : get<TotalsRow>(TOTALS_ALL, [range.from, range.to])) ?? ({ records: 0 } as TotalsRow);

      renderPage(req, res, '${plan.moduleDir}/index', {
        title: ${JSON.stringify(plan.title)},
        recordsPath: '${entity.base}',
        records: Number(row.records ?? 0),
        from: (req.valid.query as { from?: string }).from ?? '',
        to: (req.valid.query as { to?: string }).to ?? '',
        totals: [
${totalLines}
        ],
        breakdowns: [
${choiceLines}
        ],
      });
    },
  );
}
`;
}

export function emitView(plan: SummaryPlan): string {
  const plural = (plan.entity.entity.pluralLabel ?? `${plan.entity.entity.label}s`).toLowerCase();
  return `<section class="card">
  <h1><%= title %></h1>
  <form method="get" action="${plan.path}" class="filters">
    <div class="field">
      <label for="from">Added from</label>
      <input id="from" name="from" type="date" value="<%= from %>">
    </div>
    <div class="field">
      <label for="to">Added up to</label>
      <input id="to" name="to" type="date" value="<%= to %>">
    </div>
    <button type="submit" class="button">Show</button>
  </form>
  <p class="total" data-records="<%= records %>"><strong><%= records %></strong> ${plural}<% if (from || to) { %> added<% if (from) { %> from <%= from %><% } %><% if (to) { %> up to <%= to %><% } %><% } %>.</p>
  <% if (totals.length > 0) { %>
    <table class="table">
      <thead><tr><th></th><th>Total</th><th>Average</th></tr></thead>
      <tbody>
        <% for (const t of totals) { %>
          <%
            /* The figure is also put on the row as data, so the app's own tests can read it without parsing prose. */
            const shown = t.kind === 'money' ? Number(t.total).toFixed(2) : String(Number(t.total));
          %>
          <tr data-total="<%= t.label %>" data-value="<%= shown %>">
            <td><%= t.label %></td>
            <td><%= t.kind === 'boolean' ? shown + ' of ' + records : shown %></td>
            <td><%= t.average === null ? '' : Number(t.average).toFixed(2) %></td>
          </tr>
        <% } %>
      </tbody>
    </table>
  <% } %>
  <% for (const b of breakdowns) { %>
    <h2><%= b.label %></h2>
    <table class="table">
      <thead><tr><th><%= b.label %></th><th>How many</th></tr></thead>
      <tbody>
        <% for (const o of b.options) { %>
          <tr data-total="<%= b.label %>: <%= o.value %>" data-value="<%= o.records %>"><td><%= o.value %></td><td><%= o.records %></td></tr>
        <% } %>
      </tbody>
    </table>
  <% } %>
  <p class="muted"><a href="<%= recordsPath %>">Back to ${plural}</a></p>
</section>
`;
}
