#!/usr/bin/env node
/**
 * `npm run self-assess` (CONTRACTS §0, DESIGN §11): runs SecureVibe's own verification pipeline against itself,
 * using `self-assessment/profile.json`, and writes the reports to `artifacts/self-assessment/`.
 *
 * SecureVibe ships no `securevibe.manifest.json` of its own (that file describes an application *generated by*
 * SecureVibe) — a minimal, honest stand-in is built below so the manifest-control check finds nothing to credit
 * rather than crashing, and the static scanners (sast/secrets/config/deps/lint) still run against this repository.
 * Differences from a generated app, all reported in the output:
 *  - `unit-tests` uses SecureVibe's own vitest suite, run here just before the pipeline (`--skip-tests` to omit);
 *  - `dast` probes SecureVibe started in this process on a free loopback port with a scratch workspace, signed in
 *    with this process's startup token; probes that need the generated-app test mode report `not attempted`;
 *  - test code, fixtures and the app template are not scanned (the template is verified by building an app);
 *  - reviewed decisions from `self-assessment/triage.json` mark accepted risks and false positives, with reasons.
 */
import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import type { Server } from 'node:http';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { TemplateManifestSchema, type TemplateManifest } from '@shared/knowledge.js';
import type { Evidence } from '@shared/compliance.js';
import { DesignProfileSchema } from '@shared/profile.js';
import { createProvider, deriveDesign, loadFrameworks, loadKnowledge, startupTokenAuthBootstrap } from '../integration.js';
import { effectiveAiSettings, loadConfig } from '../config.js';
import { SELF_PROJECT_NAME } from '../verification/index.js';
import { RunBusRegistry, runPipeline } from '../pipeline/index.js';
import { ProjectStore } from '../store/index.js';
import { SessionManager } from '../security/token.js';
import { createApp } from '../app.js';
import { createLogger } from '../security/logger.js';
import type { TestResult } from '../compliance/types.js';
import { freePort } from '../scanners/dast/harness.js';
import { addSessionCookieName } from '../scanners/dast/http.js';
import { SESSION_COOKIE } from '../security/token.js';
import type { AppInstance } from '../scanners/dast/types.js';
import { NOT_APPLICABLE_TO_SECUREVIBE, selfRoutes, type ExpressLayer } from './self-assess-support.js';
import type { RuleDecision } from '../scanners/normalize.js';

// Test code and fixtures (deliberately vulnerable apps, fake keys) are not shipped; the template is verified by the
// pipeline whenever it builds an app from it.

const SELF_ASSESS_IGNORE = ['node_modules', 'dist', 'workspace', 'artifacts', 'web/dist', '.claude', 'server/tests/**', 'web/tests/**', 'templates/**'];

interface TriageFile {
  reviewedBy: string;
  reviewedAt: string;
  decisions: { ruleId: string; paths?: string[]; status: 'accepted' | 'false-positive'; reason: string; compensatingControl?: string }[];
}

function loadTriage(file: string): RuleDecision[] {
  if (!existsSync(file)) return [];
  const raw = JSON.parse(readFileSync(file, 'utf8')) as TriageFile;
  return raw.decisions.map((d) => ({
    ruleId: d.ruleId,
    ...(d.paths ? { paths: d.paths } : {}),
    status: d.status,
    triage: { reason: d.reason, by: raw.reviewedBy, at: raw.reviewedAt, ...(d.compensatingControl ? { compensatingControl: d.compensatingControl } : {}) },
  }));
}

/** Requirements the latest finished self-assessment rated `pass` (from automated evidence). */
function previouslyVerified(store: ProjectStore, projectId: string | undefined): Set<string> {
  const ids = new Set<string>();
  if (!projectId) return ids;
  for (const runId of store.listRunIds(projectId).reverse()) {
    const compliance = store.readRun(projectId, runId)?.compliance;
    if (!compliance) continue;
    for (const standard of [compliance.asvs, compliance.aisvs, compliance.appendixC]) {
      for (const r of standard?.results ?? []) if (r.status === 'pass') ids.add(r.id);
    }
    break;
  }
  return ids;
}

interface VitestJson {
  testResults: { name: string; assertionResults: { ancestorTitles: string[]; title: string; status: string; duration?: number | null; failureMessages?: string[] }[] }[];
}

/** Runs SecureVibe's own test suite with vitest's JSON reporter and converts the results. */
function runOwnTests(repoRoot: string): { tool: string; results: TestResult[] } | undefined {
  const vitest = join(repoRoot, 'node_modules', 'vitest', 'vitest.mjs');
  if (!existsSync(vitest)) return undefined;
  const outDir = mkdtempSync(join(tmpdir(), 'securevibe-self-tests-'));
  const outFile = join(outDir, 'vitest.json');
  try {
    process.stdout.write('Running SecureVibe\'s own test suite…\n');
    spawnSync(process.execPath, [vitest, 'run', '--reporter=json', `--outputFile=${outFile}`], {
      cwd: join(repoRoot, 'server'),
      stdio: 'ignore', // results come from the JSON report; the suite's own logging would only add noise
      shell: false,
      timeout: 15 * 60_000,
    });
    if (!existsSync(outFile)) return undefined;
    const report = JSON.parse(readFileSync(outFile, 'utf8')) as VitestJson;
    const results: TestResult[] = report.testResults.flatMap((file) =>
      file.assertionResults.map((t) => ({
        name: [...t.ancestorTitles, t.title].join(' > '),
        ok: t.status === 'passed' || t.status === 'skipped' || t.status === 'pending' || t.status === 'todo',
        file: file.name.startsWith(repoRoot) ? file.name.slice(repoRoot.length).replace(/^\//, '') : file.name,
        ...(t.status === 'skipped' || t.status === 'pending' || t.status === 'todo' ? { skipped: true } : {}),
        ...(typeof t.duration === 'number' ? { durationMs: t.duration } : {}),
        ...(t.failureMessages?.length ? { detail: t.failureMessages.join('\n').slice(0, 2000) } : {}),
      })),
    );
    const version = (JSON.parse(readFileSync(join(repoRoot, 'node_modules', 'vitest', 'package.json'), 'utf8')) as { version: string }).version;
    return { tool: `vitest ${version}`, results };
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
}

function selfManifest(): TemplateManifest {
  return TemplateManifestSchema.parse({
    name: 'securevibe',
    version: '0.1.0',
    description: 'SecureVibe itself, not a generated application. No template controls apply; this manifest exists only so the compliance engine has a well-formed (empty) one to check.',
    stack: ['Node.js', 'TypeScript', 'Express 5'],
    engines: { node: '>=22.13.0' },
    features: [],
    protectedPaths: [],
    writablePaths: [],
    allowedImports: [],
    controls: [],
    conventions: [],
    testMode: {
      envFlag: 'SECUREVIBE_TEST_MODE',
      readyLinePrefix: '{"securevibe":"listening"',
      routesEndpoint: '/__securevibe/routes',
      seededUsers: [],
    },
  });
}

interface ImportedAiReview {
  modelId: string;
  requestIds: string[];
  promptHash: string;
  responseHash: string;
  importedBy: string;
  assessments: { requirementId: string; summary: string }[];
}

function loadImportedEvidence(file: string): Evidence[] {
  const raw = JSON.parse(readFileSync(file, 'utf8')) as ImportedAiReview;
  for (const field of ['modelId', 'requestIds', 'promptHash', 'responseHash', 'importedBy', 'assessments'] as const) {
    if (raw[field] === undefined) throw new Error(`--ai-review-file is missing "${field}".`);
  }
  const now = new Date().toISOString();
  return raw.assessments.map((a, i) => ({
    id: `IMPORTED-${i + 1}`,
    type: 'manual' as const,
    tier: 'weak' as const,
    ref: a.requirementId,
    summary: `Imported AI review (manual evidence): ${a.summary}`,
    passed: true,
    tool: raw.modelId,
    capturedAt: now,
    producedBy: `manual (imported AI review by ${raw.importedBy}); model ${raw.modelId}; requests ${raw.requestIds.join(', ')}; promptHash ${raw.promptHash}; responseHash ${raw.responseHash}`,
  }));
}

async function main(): Promise<void> {
  const aiReviewFlagIndex = process.argv.indexOf('--ai-review-file');
  const aiReviewFile = aiReviewFlagIndex >= 0 ? process.argv[aiReviewFlagIndex + 1] : undefined;

  const config = loadConfig();
  const profileFile = config.paths.selfAssessmentProfile;
  if (!existsSync(profileFile)) {
    process.stderr.write(`${profileFile} is missing. It should be committed to the repository.\n`);
    process.exitCode = 1;
    return;
  }
  const profile = DesignProfileSchema.parse(JSON.parse(readFileSync(profileFile, 'utf8')));

  const store = new ProjectStore(config.paths.home);
  const knowledge = loadKnowledge();
  const frameworks = loadFrameworks();

  // One project holds every self-assessment, so runs compare with the previous one and the project list stays tidy.
  const existing = store.list().find((p) => p.name === SELF_PROJECT_NAME);
  const project = existing ? store.mustGet(existing.id) : store.create({ name: SELF_PROJECT_NAME, mode: 'quick', profile });
  project.profile = profile;
  project.design = deriveDesign(profile, { knowledge, frameworks, selfAssessment: true });
  project.profileHash = project.design.profileHash;
  store.save(project);

  const sessions = new SessionManager();
  addSessionCookieName(SESSION_COOKIE);
  const extraEvidence = aiReviewFile ? loadImportedEvidence(resolve(aiReviewFile)) : [];
  // --skip-verified: leave out of the AI review the requirements the previous self-assessment already verified as
  // passing with automated checks (an AI opinion adds nothing there and costs money).
  const aiReviewSkip = process.argv.includes('--skip-verified') ? previouslyVerified(store, existing?.id) : undefined;
  if (aiReviewSkip) process.stdout.write(`Leaving ${aiReviewSkip.size} already-verified requirement(s) out of the AI review.\n`);
  // --no-ai: skip the AI review even when a key is configured (it costs money).
  // The "Use AI" switch in Settings and SECUREVIBE_AI=off apply here too.
  const noAi = process.argv.includes('--no-ai') || !config.settings.get().aiEnabled || config.aiDisabled;
  if (noAi && !process.argv.includes('--no-ai')) process.stdout.write('AI is switched off, so the AI review is skipped.\n');
  // --max-usd <n>: spending limit for the AI review (default: the limit in Settings).
  const maxUsdIndex = process.argv.indexOf('--max-usd');
  const maxUsd = maxUsdIndex >= 0 ? Number(process.argv[maxUsdIndex + 1]) : undefined;
  if (maxUsd !== undefined && !(maxUsd > 0)) throw new Error('--max-usd needs a positive number of US dollars.');
  const ruleDecisions = loadTriage(join(config.paths.repoRoot, 'self-assessment', 'triage.json'));
  const importedTests = process.argv.includes('--skip-tests') ? undefined : runOwnTests(config.paths.repoRoot);
  if (!importedTests && !process.argv.includes('--skip-tests')) {
    process.stdout.write("SecureVibe's own test suite could not be run; the report will show the tests as not run.\n");
  }

  // The runtime scan talks to SecureVibe started here, with a scratch workspace so probes never touch real projects.
  const scratchHome = mkdtempSync(join(tmpdir(), 'securevibe-self-dast-'));
  const makeApp = (appConfig: typeof config) =>
    createApp({
      config: appConfig,
      sessions,
      logger: createLogger({ silent: true }),
      store: new ProjectStore(scratchHome),
      knowledge,
      frameworks,
      getProvider: () => createProvider({ forceProvider: 'null' }),
      busRegistry: new RunBusRegistry(),
    });
  const routes = selfRoutes(makeApp(config) as unknown as { router?: { stack?: ExpressLayer[] } });
  const dastStart = async (phase: AppInstance['phase']): Promise<AppInstance> => {
    if (phase !== 'test') throw new Error('SecureVibe has a single local mode; there is no separate production mode to start.');
    const port = await freePort();
    const scratchConfig = { ...config, port, openBrowser: false, paths: { ...config.paths, home: scratchHome, projectsDir: join(scratchHome, 'projects') } };
    mkdirSync(scratchConfig.paths.projectsDir, { recursive: true });
    const app = makeApp(scratchConfig);
    const server = await new Promise<Server>((resolveServer, reject) => {
      const s = app.listen(port, '127.0.0.1', () => resolveServer(s));
      s.on('error', reject);
    });
    return {
      phase,
      baseUrl: `http://127.0.0.1:${port}`,
      port,
      pid: process.pid,
      dataDir: scratchHome,
      // Probes that sign in "with the right credentials" use this value; for SecureVibe that is the startup token.
      env: { SECUREVIBE_TEST_PASSWORD: sessions.startupToken },
      tlsMode: 'off',
      sandboxMode: 'in-process (SecureVibe itself, scratch workspace)',
      output: () => ({ stdout: '', stderr: '' }),
      resetRateLimits: async () => {
        await (app.locals['resetRateLimits'] as () => Promise<void>)();
        return true;
      },
      stop: () => new Promise<void>((done) => server.close(() => done())),
    };
  };

  process.stdout.write('Running SecureVibe self-assessment…\n');
  const run = await runPipeline(
    project,
    {
      mode: 'verify-only',
      spendingCapUsd: maxUsd ?? config.settings.get().defaultSpendingCapUsd,
      appDir: config.paths.repoRoot,
      manifestOverride: selfManifest(),
      extraIgnore: SELF_ASSESS_IGNORE,
      dastAuth: startupTokenAuthBootstrap({
        token: sessions.startupToken,
        field: 't',
        csrfPath: '/api/status',
        extraSessionLabels: ['member2'],
        user: { label: 'member', email: 'owner@localhost', role: 'owner' },
      }),
      extraEvidence,
      ruleDecisions,
      dastExtra: { start: dastStart, routes, notApplicable: NOT_APPLICABLE_TO_SECUREVIBE },
      ...(aiReviewSkip ? { aiReviewSkip } : {}),
      ...(importedTests ? { importedTests } : {}),
    },
    { store, config, knowledge, frameworks, provider: createProvider(noAi ? { forceProvider: 'null' } : { model: effectiveAiSettings(config.settings.get()).model, reviewEffort: effectiveAiSettings(config.settings.get()).reviewEffort }), busRegistry: new RunBusRegistry() },
  );

  rmSync(scratchHome, { recursive: true, force: true });

  // Publish this run's reports as SecureVibe's own artifacts (replacing the previous self-assessment).
  const runReportsDir = store.reportsDir(project.id, run.id);
  rmSync(config.paths.selfAssessmentDir, { recursive: true, force: true });
  mkdirSync(config.paths.selfAssessmentDir, { recursive: true });
  if (existsSync(runReportsDir)) cpSync(runReportsDir, config.paths.selfAssessmentDir, { recursive: true });
  writeFileSync(join(config.paths.selfAssessmentDir, 'latest-run-id.txt'), `${run.id}\n`);

  process.stdout.write(`\nRun ${run.id}: ${run.status}\n`);
  for (const stage of run.stages) process.stdout.write(`  ${stage.id.padEnd(14)} ${stage.status.padEnd(9)} ${stage.summary}\n`);
  process.stdout.write(`\nReports written to ${config.paths.selfAssessmentDir} (run copy: ${runReportsDir})\n`);
  process.exitCode = run.status === 'succeeded' ? 0 : 1;
}

main().catch((err) => {
  process.stderr.write(`self-assess failed: ${err instanceof Error ? err.stack ?? err.message : String(err)}\n`);
  process.exitCode = 1;
});
